### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by scantineau** [blakeblackshear/frigate#101]
Have you thougth about clustering ?

I'm running frigate on my rpi4 and it is perfectly working with up to 3 cameras.

When I look at htop, I can see the bottleneck seems to be on ffmpeg process, each one is taking 100% of a core.

I was thinking about using docker swarm with leader election, only some instances (at least one) should need the Coral device and the others will fill the queue with all images to detect objects.

Please let me know what do you think about this idea !

**Comment by blakeblackshear** [comment]
I have thought about it. The next version will do a better job with multi processing, so that may help. Before clustering, it would be better to try and get hardware acceleration working for ffmpeg decoding. Frigate benefits from a shared memory store on a single device. What FPS do your cameras use?

**Comment by scantineau** [comment]
I'm using a specific uri exposed by my NVR, to get a lower quality stream but I don't find any information about the FPS...
