### ISSUE TITLE
[RFC] Trigger Clips and Snapshots via API

### ISSUE THREAD

**Issue by herostrat** [blakeblackshear/frigate#1063]
## Idea:
Allow triggering of clips and snapshots via external command.

## Implementation:
Implement API endpoints for:

- Webinterface
  - In camera view two buttons
- HTTP
  - /api/<camera_name>/create-snapshot
  - /api/<camera_name>/create-clip
- MQTT
  - frigate/<camera_name>/snapshots/create
  - frigate/<camera_name>/clips/create

The configuration of the created object is according to the user config and therefore the same as triggered via internal detection.

## Background/Usecases:
 
- motion/PIR/light barrier sensors in home automation as trigger condition
- timer based trigger condition
- ...

@blakeblackshear is this acceptable or according to the projects vision?
I am interested in implementing this myself, so it is no FR

@all Additional ideas and suggestions?

---

Relevant Issues/Discussions:
https://github.com/blakeblackshear/frigate/issues/1040
https://github.com/blakeblackshear/frigate/issues/926
https://github.com/blakeblackshear/frigate/issues/345
https://github.com/blakeblackshear/frigate/discussions/1008

**Comment by blakeblackshear** [comment]
I am not completely convinced a few other enhancements wouldn't obviate the need for this feature. What if the 24/7 recordings could be set to only retain segments that had motion? Also, what if 24/7 recordings could be turned on and off like detection, clips, and snapshots? I don't see any use cases in the linked tickets that wouldn't be covered by these two enhancements.

If this is implemented, my gut says this should be done by manually saving a frame as a snapshot and putting an event into the [event queue](https://github.com/blakeblackshear/frigate/blob/master/frigate/object_processing.py#L441) for processing. I think it will need to have a predetermined length, and the properties on the event table will need to be reconciled to accommodate a manual recording. It should fit fairly easily into the existing event handling and clip creation.

**Comment by herostrat** [comment]
I am not sure I understand correctly and/or made it clear enough what my idea is.

Basically I want to use the event queue, but add additional triggers for it.

My understanding is that currently the only way to add something to.the event queue is when frigate has detected something.

Please correct me if I am wrong, I am most certaintly not too familiar with the codebase.

How would you use external sensors to generate clips oe snapshots and save them?

**Comment by blakeblackshear** [comment]
I understand the idea and agree with the implementation of using the event queue. That's basically what I said.

I just don't see the need to use external sensors to trigger clips or snapshots if Frigate is working properly. I would rather ensure Frigate has the features to capture anything of interest than rely on external systems to turn things on and off.

**Comment by herostrat** [comment]
Ah I see, sorry for the confusion. English is not my mother rongue.

I agree for the most part.
In my mind there are a few usecases where frigate is working and detecting properly, but also could use this feature.
Sometimes there is just nothing to detect in the video feed but I want a clip nonetheless.

Thanks for your feedback!

**Comment by Whytey** [comment]
Additional use case - video doorbell.  Doorbell is pressed so trigger a clip/recording.  Frigate might not have detected motion (maybe the local kids are being tricky and hiding themselves??) but you would like to have a clip so you can see what was going on in the background??

**Comment by blakeblackshear** [comment]
If they were hiding themselves and frigate doesn't detect any motion, wouldn't you just be recording a static image?

**Comment by Whytey** [comment]
I was thinking more along the lines of them being in the distance but too small to be within the detection threshold. Corner cases admittedly.

**Comment by blakeblackshear** [comment]
And those far away objects are related to your doorbell ringing? I'm trying to understand if this is a hypothetical scenario or if you have a use case I haven't considered.

**Comment by Whytey** [comment]
Purely hypothetical. 

I like the idea of externally triggering Frigate... Though purely due to having had poor experiences of false positives with other NVR solutions.

**Comment by stephengolub** [comment]
I like the idea of triggering a recording with "custom events" and was actually looking into the code to see how complicated it would be. I ran out of free time a while back, so maybe I'll revisit it.

Here's where I think just relying on motion/object detection could fail: Say you only have person detection set up, and a delivery driver comes up with a load of packages or big jacket or something and the model just doesn't quite recognize them. Then you miss the recording.

Having the "custom event" (in this case a "ding dong" or "ring" event) that you can send a payload to Frigate and say:
```
{
  "camera": "front_door",
  "event": "ring"
}
```

I can also imagine triggering perimeter recording if my door bell rings, or almost any other type of thing.

As an MVP, I'd just accept event and camera and use the default clip recordings. Maybe in the future add the ability to specify length, etc.

**Comment by blakeblackshear** [comment]
If 24/7 recordings had the ability to only retain segments where motion was detected, wouldn't you cover the edge cases where the model didn't detect for some reason?

Also seems like a switch to turn off 24/7 recordings would address the use case of turning on recording based on an event.

**Comment by stephengolub** [comment]
My thinking is that it would tag a point in time by leveraging the existing concept of "events".

By adding a custom "ding" event or whatever, I will see those separated out in the UI and database and could even have a "last_ding" camera in home assistant.

Another use case I would use was "garage" event. So if someone opens or closes my garage, I would run a snapshot of the driveway camera as well and have the specific point in time tagged.

**Comment by blakeblackshear** [comment]
Those seem like worthwhile use cases. This should fit reasonably well into the the existing architecture as I mentioned above.

**Comment by ravetam** [comment]
Ideally, I would use object detection in frigate but I don't have a coral and I rather not max up my CPU for object detection. Since I have a PIR sensor in home assistant, it would be great to use that to trigger an event in frigate and record a clip. (E.g. If someone enters my room when I'm away)

Ability to control 24/7 recording with Mqtt/hass is important as well for certain use case (e.g. using hass automation to stop recording when I'm home and start recording when I'm away)

**Comment by blakeblackshear** [comment]
@herostrat please don't spend any time on this. Upcoming changes will make manually triggered events much easier to implement, so any work here would be a waste of time.

**Comment by vhbramos** [comment]
I have a few use cases that could leverage this feature:

1) Audio Detection: My Amcrest cameras can detect audio and it would be great to manually trigger a clip recording in Frigate. There is no motion, but the camera audio can provide important insights about ongoing events.
Example: Detection of fire/smoke alarms or any other audio alarms. ( Wize cameras have a specific event to alert users of Fire/Smoke alarms )

2) Tripwire: This can be a Frigate core feature in the future, but in the meantime I could use an external sensor ( some cameras also have it embedded ) to trigger a recording and a **specific** alert if motion is detected from a specific area to a specific area. This would be an additional alert, since I would still want Frigate to monitor a larger area for objects ( like people and cars )

3) Other AI detection: I am looking to deploy a couple of cameras with more advanced AI capabilities, like detecting parked cars and objects left in specific areas. I can get motion events for those situations in Frigate today but those extra labels would help me get better notifications

**Comment by zaPure** [comment]
I agree that this would be a useful feature to trigger recording from MQTT events, e.g. my alarm or electrical fence triggers or garden beams go off. I would like the camera to start recording so that I can get a sense of what triggered it. As I have my cameras are set up only to record on people detection.

**Comment by oramirite** [comment]
I'd like to chine in on the need for this as well. I regards to Frigate working properly obfuscating the need for this feaure: I feel it's anything but. Frigate itself, when working correctly, can benefit from manual event triggering.

I have an overhead street camera that's at a perfect angle for person detection. My doorbell camera points out at a busy street however, and unless I can get some kind of z-depth detection it's impossible to mask things out in a way that will only detect people on my stoop. The overhead camera, however, is perfect for drawing zones. But the doorbell camera is the only one that can capture faces.

It would be great to rely on the overhead camera's detection, and be able to roll my own logic for capturing the same clips on my doorbell camera. This way, the media library of my Doorbell would only ever contain events where people were accurately detected on my stoop.

The doorbell camera angle I have is REALLY bad for detection, but works perfect for faces and general viewing when I have a visitor. While I appreciate that Frigate wants to cover and and all use-cases through detection, I feel like there's always going to be edge cases where complimenting the detection with an additional sensor will work perfectly.

**Comment by blakeblackshear** [comment]
You should create a zone for your stoop and add that zone to required zones for your doorbell camera. Then you will only get events where the person stepped onto your stoop.

Either way, this feature is coming. No need to continue to advocate for it.

**Comment by oramirite** [comment]
That's great news @blakeblackshear, thanks so much!! And thanks for such a quick reply before.

I can't see the ground due to this doorbell camera's angle so detection via another camera is really the only way. The overhead camera I mentioned works flawlessly with zones. It's no fault of Frigate at all - my house is elevated from the street so the doorbell camera only sees humans from the waist up. Detection works great it's just not possible to differentiate someone walking past my house from being at the door.

Excited for this addition. Thank you so much for creating what might be the best NVR solution out there!!

**Comment by Notrial** [comment]
Has this feature been implemented in the recent version updates?

**Comment by herostrat** [comment]
Unfortunately not, I tried to add it but was not able to integrate it properly into the event queue.

I will probably not have time to continue for a bit, but if someone finds a easy way to implement it feel free!

**Comment by Notrial** [comment]
That's really too bad...having on-demand clips would be really useful.
Are there any workarounds to getting screenshots/clips from Home Assistant on button press for example?

**Comment by herostrat** [comment]
afaik not

**Comment by oramirite** [comment]
Dang, that's really disappointing. I appreciate the attempt. Sounds like this is no longer on the official roadmap though? 

I don't mean to be the peanut gallery here, but the solutions being discussed feel really overcomplicated. Integration into the event queue would be nice, but it sounds like an uphill battle since you then need to re-create the conditions of a detection. We really just want to manually trigger a clip recording. Simple. It should be as un-related to motion detection as possible.

@blakeblackshear you mentioned this as well:
"I just don't see the need to use external sensors to trigger clips or snapshots if Frigate is working properly. I would rather ensure Frigate has the features to capture anything of interest than rely on external systems to turn things on and off."

While I appreciate that Frigate really wants to lean in to AI detection, you're always going to have situations that won't cover, even when it's working perfectly. Also, Frigate is built to integrate extremely closely with Home Assistant - a platform for automation and sensor data. The strength of this integration very much SHOULD be manual input from other sources. I don't really understand the logic that Frigate shouldn't allow external data sources.

Frigate isn't failing by needing manual intervention. It is, in fact, a testament to how WELL the AI detection is implemented that we're already seeing it's limits. There will always be situations where AI + motion detection isn't the whole picture, and we really need the tools to fill in that last 5% of situations.

**Comment by blakeblackshear** [comment]
@oramirite As I stated [a few comments up](https://github.com/blakeblackshear/frigate/issues/1063#issuecomment-1004042764).

> Either way, this feature is coming. No need to continue to advocate for it.

**Comment by herostrat** [comment]
Yes, sorry if I gave you the impression it is not or no longer planned.

I just meant I was not able to add it in a satisfactory way. This does not mean it is not possible, just that I was not able to within the time I had available.

**Comment by NickM-27** [comment]
@Notrial I have been able to implement a lite version of this on the HASS side. When someone presses my doorbell I send a notification to my TV / Mobile Devices using the `http://frigate/api/<camera_name>/latest.jpg` as the image source. Could also use that to save an image. 

As stated this is coming to frigate natively, but thought I would share for anyone trying to create something similar to my use case I mentioned.

**Comment by raintonr** [comment]
> When someone presses my doorbell I send a notification to my TV / Mobile Devices using the `http://frigate/api/<camera_name>/latest.jpg` as the image source.

In fact this is exactly how a Loxone intercom block functions. It works very well but guess it would be nice to see all events of all types in the same UI.

**Comment by Bernix01** [comment]
Is it out yet? Planned/scheduled?

**Comment by strarsis** [comment]
Maybe I think too unpractical here, but isn't the job of frigate to offer unified feature detection, while other tools like Home Assistant/Node RED or some script/tool can be triggered by frigate and decide what to do, e.g. take a screenshot from the camera stream?

**Comment by NickM-27** [comment]
> Maybe I think too unpractical here, but isn't the job of frigate to offer unified feature detection, while other tools like Home Assistant/Node RED or some script/tool can be triggered by frigate and decide what to do, e.g. take a screenshot from the camera stream?

I think the other side of the argument is that users use frigates `Events` as a way to see everything and I suppose there are some edge cases where a recording would be helpful even if it was just audio (no objects to detect) or a further pre-trigger. And it is nice to have something like `doorbell press` in the event list.

Either way, I have a draft PR up for this. Still working out how it will best be implemented especially on the HA integration side.

**Comment by strarsis** [comment]
@NickM-27: I want to use a `Ubiquiti G4 Doorbell` with Home Assistant + Frigate. Would this new Event also play a role here, like the doorbell button press?

**Comment by NickM-27** [comment]
> @NickM-27: I want to use a `Ubiquiti G4 Doorbell` with Home Assistant + Frigate. Would this new Event also play a role here, like the doorbell button press?

You could, for example, use the API to create a frigate event called `doorbell press`. Naturally Frigate would have its own event for person detected, but as has been discussed previously there are cases where a feature like this is useful.

**Comment by strarsis** [comment]
@NickM-27: I see, this makes things more convenient when Frigate is the sole "consumer" of that device (using its stream and button press events (HTTP?)), so no extra listeners are needed for the button press event, correct?

**Comment by NickM-27** [comment]
> @NickM-27: I see, this makes things more convenient when Frigate is the sole "consumer" of that device (using its stream and button press events (HTTP?)), so no extra listeners are needed for the button press event, correct?

No, not at all really. The event still needs to be initiated by the user via the API through an automation or otherwise. 

This is just simply a way for a user to create events in a case where perhaps frigate is unable to. (I personally do not have these, but they've been discussed in this issue and is why the feature request is pinned).

**Comment by oramirite** [comment]
I hope more here realize that manual event triggering goes beyond "nice to have" - it's a must for some homes. Zones are NOT the silver bullet they keep being referenced as, there are geographical features of many homes that make person detection not possible for certain areas where there will DEFINITELY be a contact sensor or a doorbell. This is why security systems aren't just cameras. Since Frigate puts itself out there as an NVR solution, and has it's own media browsing experience, this creates a divergence between any footage that's able to be captured through AI person detection and anything else I'd like to do. I'm forced to browse 2 completely different UIs.

I have cited my example of a doorbell in the city that constantly has people walking by a few times in this thread now. To Frigate, a person walking by my door looks EXACTLY the same as a person ringing my doorbell. AI person detection will never be a solution here. @blakeblackshear you said this support was coming officially, was this canned? Thank you so much for taking this up @NickM-27 .

@strarsis Yes, this would be fine, except as it currently stands those manual clips exist in an entirely different part of the media interface that we need to navigate to. So my manually triggered doorbell footage would be totally separate from Frigate's clips which makes no sense. We really just need a simple manual input for capturing events or clips, and then yes, the logic could easily be elsewhere.

**Comment by NickM-27** [comment]
> I hope more here realize that manual event triggering goes beyond "nice to have" - it's a must for some homes. Zones are NOT the silver bullet they keep being referenced as, there are geographical features of many homes that make person detection not possible for certain areas where there will DEFINITELY be a contact sensor or a doorbell.

Zones are very powerful but of course have limitations in certain edge cases, which is why this issue is pinned and being implemented.

> was this canned?

This issue is pinned and not closed, so it was not canned.

> @blakeblackshear you said this support was coming officially, was this canned? Thank you so much for taking this up @NickM-27 .

 I don't know what the distinction is here. This FR was pinned to be implemented in the future, I'm an active contributor to frigate and had the time to start working on this. I'm unsure what may be unofficial about it?

**Comment by oramirite** [comment]
I apologize, I've had this bookmarked for so long that I was going right to the thread and didn't actually realized it was pinned, and also did not realize you were an active contributor (thought you were just a kind soul picking this up). I'll do my homework a little more next time. Very excited for this!

**Comment by NickM-27** [comment]
> Ability to manually create events through the API #3184

No problem, appreciate it. 

If you have any feedback on the open questions in the PR feel free to comment in the PR on them

**Comment by strarsis** [comment]
@NickM-27: If I may ask an OT question here, where or how can I find out what PoE+Ethernet+ONVIF Doorbell would have the best support from Frigate/Home Assistant? The previously mentioned `Ubiquiti G4 Doorbell` (Pro) needs an extra USB adapter for PoE+Ethernet and a bit pricey, so I am looking for other doorbells as well. But their button press and camera should just work out of the box, without workarounds like DNS logs scanning. Is there a list of known "definitive" supported models?

**Comment by NickM-27** [comment]
> Is there a list of known, supported, "definitive" models?

No, there's not many doorbells really. I use the Amcrest AD410, I'm sure there's a few others as well.

**Comment by strarsis** [comment]
@NickM-27: And the `Amcrest AD410` would be fully supported by Frigate/Home Assistant, camera stream, doorbell button and two-way audio, without the need for a 3rd party app and such? 🐱

**Comment by NickM-27** [comment]
> @NickM-27: And the `Amcrest AD410` would be fully supported by Frigate/Home Assistant, camera stream, doorbell button and two-way audio, without the need for a 3rd party app and such? 🐱

Camera stream and doorbell press have a number of options. two-way audio isn't really supported by HA at all currently. The doorbell does have an API where you can manually send an mp4 file for it to play. 

This is not relevant to this issue so I'd recommend directly any further questions / queries to a dedicated discussion: https://github.com/blakeblackshear/frigate/discussions

**Comment by bagobones** [comment]
Going to add my own comments here which mirror some others on why and what would be useful.

Enhancing the Event timeline: injecting door open/close, garage door open/close, gate open/close, doorbell press events into the timeline makes for VERY fast review of the timeline even if there are people events. I COULD look at all people detections at the doorbell camera but what if the kids where playing in the front yard all day? Would be far better to filter the events on doorbell press.

Missed detections: Forcing an event and recording on a reliable hard sensor event like a door sensor or doorbell ensures there is a recording even if someone shows up in a gorilla suite and doesn't get detected as a person. Same goes for vehicles passing through a gate.. if the gate opens we want a recording / event. In the home it could also be as simple as did the lights get turned on or off in a room, that might be an important event to some.

Integration opportunity: If the HA integration registered a notification type it would be trivial to send "notifications" to frigate to inject events.

**Comment by skynet01** [comment]
> @NickM-27, @oramirite: If I may ask an OT question here, where or how can I find out what PoE+Ethernet+ONVIF Doorbell would have the best support from Frigate/Home Assistant? The previously mentioned `Ubiquiti G4 Doorbell` (Pro) needs an extra USB adapter for PoE+Ethernet and a bit pricey, so I am looking for other doorbells as well. But their button press and camera should just work out of the box, without workarounds like DNS logs scanning. Is there a list of known, supported, "definitive" models?

I have the Reolink POE doorbell. Just got it yesterday, it's fairly new, not that expensive but it works great with frigate already. 

> **Missed detections:** Forcing an event and recording on a reliable hard sensor event like a door sensor or doorbell ensures there is a recording even if someone shows up in a gorilla suite and doesn't get detected as a person. Same goes for vehicles passing through a gate.. if the gate opens we want a recording / event. In the home it could also be as simple as did the lights get turned on or off in a room, that might be an important event to some.

Exactly this!! I literally have a backup automation in place that checks if there was no Frigate event but the gate was opened and then I use the built-in HA stream component to record a video. 🙄

**Comment by scaytrase** [comment]
I think we can extend this idea to somehow represent "external event detections". As far as I understand some protocols like ONVIF allow transfer camera events, so we can write external software (or maybe later internal) which reads onvif events and translates them into "event detected externally" calls for Frigate. This will allow to delegate some detecting tasks to capable cameras.

just "start recording" in this case will also work of course, but I think creating Frigate events will be more useful in terms of timeline filtering and reviewing

**Comment by NickM-27** [comment]
> just "start recording" in this case will also work of course, but I think creating Frigate events will be more useful in terms of timeline filtering and reviewing

My draft implementation of this already creates events when the API is triggered https://github.com/blakeblackshear/frigate/pull/3184#issuecomment-1116408094

**Comment by chrisella** [comment]
If I understand, this issue solved the case I'm after which is my 433Mhz doorbell is picked by my my 433 receiver on ESPHome, which in turn runs an automation in HomeAssistant, I then want that automation to tell Frigate to save a recording (/create an event) of the last X seconds + next Y seconds and save that... am I right that this helps fill that last piece of the puzzle ? If so what is the current state of this, if not yet ready then is there an alternative way I could achieve this people are using ?

**Comment by NickM-27** [comment]
It's in draft PR, will he added in a future version. And yes it should solve what you're describing.

**Comment by chrisella** [comment]
Great, ok thanks I'll just be patient and wait then.

**Comment by bagobones** [comment]
Playing around with double-take the ability to force a snapshot / event when someone presses the door bell and is likely looking at it would be very nice for face detection / custom events based on specific people.

I am currently getting the walk up to the doorbell but since the event starts when the person is far away, face detection is very poor.

**Comment by raintonr** [comment]
> I am currently getting the walk up to the doorbell but since the event starts when the person is far away, face detection is very poor.

Sounds like the detection target you have configured is 'person' but you really want a target of 'face'. Then you would also like the target 'face' to be further classified to the actual individual.

Seems like a new feature request and nothing to do with triggering via API.

**Comment by scaytrase** [comment]
> Seems like a new feature request and nothing to do with triggering via API.

as far as I understand @bagobones he doesn't asks for built-in face recognition here, but for a way to make a clip\snapshot for doing so with trigger API (maybe in existing external software we don't know). so looks like relevant use case - trigger clip\snapshot by doorbell press.

**Comment by bagobones** [comment]
All I am asking for is to trigger an "event" and then integrations like double-take can add sub labels for faces

**Comment by roger-** [comment]
Adding a related request: ability to trigger a full object detection over the entire frame (perhaps respecting configured masks).

**Comment by blakeblackshear** [comment]
> ability to trigger a full object detection over the entire frame

This might seem like it is related, but it's very different and it wouldn't make sense to do this at the same time as this feature as it would be implemented in completely different parts of the code base. I would open a different request.

**Comment by NickM-27** [comment]
> > ability to trigger a full object detection over the entire frame
> 
> This might seem like it is related, but it's very different and it wouldn't make sense to do this at the same time as this feature as it would be implemented in completely different parts of the code base. I would open a different request. 

That's my bad, misunderstood the request as a duplicate

**Comment by Guisin** [comment]
Hello, is there any forecast for this implementation?

**Comment by chrislauyp** [comment]
@blakeblackshear @herostrat @stephengolub
 Hi there,
 Any update in the customer external event feature?
Thanks

**Comment by NickM-27** [comment]
@bagobones all of that is already supported in this implementation

**Comment by MrSiO** [comment]
> @bagobones all of that is already supported in this implementation

Hi Nick.

Can you identify in the documentation where this is explained? 
Eighter by MQTT or HTTP API, I cannot find how to manually trigger start/stop recording on a specified camera.

(I'm running latest Beta)

Thx

**Comment by NickM-27** [comment]
Are you looking at beta or normal docs? https://deploy-preview-6262--frigate-docs.netlify.app/integrations/api#post-apieventscamera_namelabelcreate

**Comment by bagobones** [comment]
Do be clear the fictionally of the api does NOT trigger recording it triggers events.

As per the big warning in the beta doc if you are using motion recording you can end up with empty / deleted events.

"Recording retention config still applies to manual events, if frigate is configured with mode: motion then the manual event will only keep recording segments when motion occurred."

**Comment by MrSiO** [comment]
> Are you looking at beta or normal docs? https://deploy-preview-6262--frigate-docs.netlify.app/integrations/api#post-apieventscamera_namelabelcreate

I was looking at Normal docs.
Didn't realize there was a separate doc for Beta. It's bookmarked now.

Thx! Will implement asap!

**Comment by kirilnedev** [comment]
Maybe I missed that it was implemented, but one more use case... Currently there are plenty of inexpensive camera's which have surprisingly good Human detection + most of them have some Output alarm... this may be quite useful as it may offload the Human detection to a camera consuming 1W which already has the required hardware...

**Comment by oramirite** [comment]
> Maybe I missed that it was implemented, but one more use case... Currently there are plenty of inexpensive camera's which have surprisingly good Human detection + most of them have some Output alarm... this may be quite useful as it may offload the Human detection to a camera consuming 1W which already has the required hardware...

This was added  :)

https://github.com/blakeblackshear/frigate/pull/3184#issuecomment-1745007914

**Comment by kirilnedev** [comment]
Thanks a lot for the link, @oramirite ! :) Great to hear
