### ISSUE TITLE
Config option to wait longer for ffmpeg to get frames

### ISSUE THREAD

**Issue by raidenlal** [blakeblackshear/frigate#11041]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to get stream when it takes longer time to receive it. VLC is able to receive the stream but it takes 40+ seconds to see the video stream.

**Describe the solution you'd like**
I want to be able to set longer timeout for waiting ffmpeg frames.

**Describe alternatives you've considered**
n/a

**Additional context**
`watchdog.camera_name        INFO    : No frames received from camera_name in 20 seconds. Exiting ffmpeg...`
If only Frigate would be able to wait for 60 seconds, this would be great.

**Comment by NickM-27** [comment]
why does it take so long to start the stream? if the camera has an iframe interval that far apart that is going to cause many other problems

**Comment by bench66517** [comment]
I have the same problem. Vlc is easy able to connect to the stream. But with frigate i‘m not able to connect because it takes a long time…

**Comment by villasenor** [comment]
I've seen this with IMOU (off-brand Dahua) cameras over the years sporadically, even when the cameras are on ethernet (although it happens less when wired)

The reality is that _some_ kind of image, even if it is delayed or low quality is better than no image at all. When this does happen for me, I notice that Frigate will show "no frames detected" for this particular camera for hours, but all the while VLC works fine. Furthermore, this really does seem like a case of runaway exponential back off because restarting Frigate brings the cameras back half the time.

I know this is anecdotal but I can collect any logs you need the next time this happens :)

**Comment by coldkevin** [comment]
Im having the exact issue as described by @villasenor . The stream at some point has an issue which causes the "no frames detected" sceen in frigate and goes on normally until i restart frigate entirely. But when viewing the stream in vlc its alive and well.

**Comment by aburow** [comment]
I have the same issues with timeouts on Dahua cams. Can't create or edit regions on Dahua cameras either.
There was some improvement in the last upgrade (with auto-PTZ) but there are still issues with packet drops.
