### ISSUE TITLE
option to define different motion settings by zone

### ISSUE THREAD

**Issue by kirsch33** [blakeblackshear/frigate#11116]
**Describe what you are trying to accomplish and why in non technical terms**
I have a couple of cameras that are constantly detecting motion due to shadows/leaves/trees blowing in wind but only on one side of the frame. if i tune motion down to reduce these boxes, motion isnt sensitive enough on the other side of the frame.

**Describe the solution you'd like**
add the ability to, optionally, apply motion parameters to zones. when detection is ran on a region, if it falls within a zone that has specific zone motion settings, use these instead of the camera level/global level

**Comment by NickM-27** [comment]
> I have a couple of cameras that are constantly detecting motion due to shadows/leaves/trees blowing in wind but only on one side of the frame

sounds like a good place to use motion masks

motion detection isn't run on the full size frame, so zones likely wouldn't scale very well.

**Comment by NickM-27** [comment]
in general motion being detected during windy times is not a big issue, I don't think aiming to only ever have interesting motion detected as motion is a good goal because that is why object detection exists - to verify the motion that is detected.

If your concerns are around resource usage, we already have ideas on how to reduce that considerably in a future version of frigate. 

It is possible that far in the future frigate could have some sort of "dynamic" motion detection by knowing what motion was due to a real object historically and do something like this automatically but I am not sure if that effort is worth it due to the reasons outlined above

**Comment by NickM-27** [comment]
right, I think even if you consider just the part behind the branches, different motion settings would be needed for a person walking vs the branches moving on a windy day. In general I would recommend just using a motion setting that ensures all true objects are detected. Some uninteresting motion being detected is not a problem in of itself

**Comment by Viceman256** [comment]
Just commenting that this is something that is needed for me as well. I do hope it will be considered to be able to configure motion threshold for zones in some way.
