### ISSUE TITLE
option to include bounding boxes/motion boxes on export

### ISSUE THREAD

**Issue by kirsch33** [blakeblackshear/frigate#11125]
**Describe what you are trying to accomplish and why in non technical terms**
it would be nice to have toggles when creating an export to include bounding boxes/motion boxes/etc on the clip.

**Describe the solution you'd like**
this would be useful in some cases for debugging full clips without needing to setup a camera entity with a looped mp4 which is the only other way I know to accomplish this. 

i also just like having the boxes shown since im typically only doing exports of interesting events where its helpful to see these.

**Comment by NickM-27** [comment]
there is no way to do this, we don't keep the detection data for every single frame as that would be loads of data to store for every single event.

**Comment by NickM-27** [comment]
right but running detection is not deterministic, so the results of the detection won't be the same as when it was originally run. 

the other concern is that this would be very computationally expensive because it would be an additional detection resource (taking resources away from the currently running detections) and it would also require encoding using the GPU and CPU as well. 

There might be some way to run and view detection inside the webui for an event but I don't think exporting is viable

**Comment by inotv** [comment]
Hi all,

thanks for the information and for Frigate!

I'm also interested to export bounding boxes to clips, snapshots and birdseye, this would be a great improvement

Thank you again

Toni
