### ISSUE TITLE
Adopt system stats to specific platforms

### ISSUE THREAD

**Issue by MarcA711** [blakeblackshear/frigate#11298]
I would like to suggest to design frigates system stats in a more generic way, because each platform can report different stats.
For example most arm based socs don't have dedicated gpu memory. However, when adding load stats for the gpu there is automatically a "GPU Memory" column created:  
![Screenshot from 2024-05-08 20-22-57](https://github.com/blakeblackshear/frigate/assets/40744649/f329d6f5-7f4f-4fac-bf01-921049e33262)

Also rockchip socs are able to report detailed usage stats for each NPU core. However, I found no direct way to add this to the "Detectors" section, since this section seems to work with process ids and automatically read the stats from the system.

It would be nice if frigate is able to report all relevant stats for each platform in a nice way and without empty columns that might be confusing to the user.

**Comment by NickM-27** [comment]
The empty GPU memory is a bug, it should be hidden unless perhaps Rockchip is not returning the correct values in the backend, will need to check. 

In terms of NPU usage, I could maybe see that but it is difficult because no other platforms support anything like that. I don't see a generic way to do it, it would just need to be supported specifically in the frontend. 

In general this is referring to an unreleased and unfinished version of frigate so going to close this and recommend using the 0.14 discussion

**Comment by MarcA711** [comment]
Thank you for your clarification! I wasn't aware of this discussion. I will maybe post my suggestion there. But I understand if this is not implemented because rockchip is the only platform that supports npu statistics.

**Comment by NickM-27** [comment]
you can see there is special handling for coral (PCI based) temparatures, so a contribution would be acceptable to do something similar for rockchip npu
