### ISSUE TITLE
Start Frigate even with an invalid config to make editing the config less painful

### ISSUE THREAD

**Issue by nomonkeynodeal** [blakeblackshear/frigate#11356]
I was told the config editor checks the config, and that because of this restarting with an invalid config is basically impossible. Well, I still manage to do this every few months. Last time I did so by forgetting to comment out a line that is valid according to the editor.

It seems like it might be good if users could edit the config, even if invalid, without trying to remember in what folder of what container it resides.

**Comment by NickM-27** [comment]
You can't start with an invalid config, any core piece of the logic could be incorrect and in general the config can't be parsed. 

In Frigate 0.14 a config is automatically created if it doesn't exist so that will solve the case for new users. The new UI also makes more fields configurable in the UI which in general will help. 

But the built in config editor checks that the config is valid before allowing the config to be saved among many other features, as long as this is used then there should be no issues. If there is a case where it does allow a bad config to be saved then a support discussion with an example would be great so we can try to reproduce and fix that bug
