### ISSUE TITLE
Support other backend databases (Postgres?)

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#11460]
**Describe what you are trying to accomplish and why in non technical terms**
I want to use Postgres instead of SQLite, since my database is 15GB, and when Frigate tries to vacuum it every two weeks, it basically just hangs forever until I stop frigate, manually do a `VACUUM INTO 'frigate2.db';`, overwrite the original database, and then update the .vacuum file to prevent Frigate from trying to vacuum it itself again.

**Describe the solution you'd like**
A setting in the config to provide a database connection string of some sort, to be able to tell Frigate how to connect to a different database, not managed by Frigate. By using Postgres, I can use a proven enterprise-grade vacuuming system that doesn't require 30+GB of temporary space, or locking out the rest of the app while such a vacuum is underway.

**Describe alternatives you've considered**
I've looked at trying to set various auto-vacuums in SQLite, but they seem to have major pitfalls that essentially negate any progress towards actually vacuuming the database. Overall, the general advice seems to be "don't use SQLite for medium-to-large sized database"

**Additional context**
I have a very large Frigate install - 30+ cameras - generating thousands of events per hour. I keep data for 90 days, which means I end up with millions of events in my database.

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/pull/3644#issuecomment-1215996502

**Comment by blakeblackshear** [comment]
Not really. I still believe we are a very long way away from the limits of what sqlite can manage in terms of performance. Even modest hardware can handle far more than what 99.999% of frigate users will ever need. Newer versions of sqlite will resolve many of the other pain points too. 

A different database engine isn't going to magically make the disks faster by introducing a networking layer for communication, nor is it going to resolve any inefficient database patterns that exist. Performance is not the reason to introduce a different database option. Making the architecture distributed across multiple servers or high availability would be reasons, but I'm not sure that will ever make sense for Frigate. 

Before introducing another database option for performance reasons, I want to exhaust every attempt at improving performance with sqlite.

**Comment by Serverfrog** [comment]
@blakeblackshear , i don't want to create another Ticket with the same Topic, so sorry that i necro that ticket.
I would like to bring up another thing where i would like another Database:
If the Frigate Container/Process is killed rather fast, so it can't close any IO/ execute a current statement full, it can result (and sooner or later will) in a malformed sqlite database.

That happens to me to different software which uses it, and currently it happen to me in Frigate too.

Basically it will result in Frigate crashing as the "database disk image is malformed". This can happen for multiple reasons, but one thing is always the case: the Container/Frigate was not shut down gracefully while a database operation was taking place. An external Database (like Postgresql/MariaDB/Mysql,..) would in that case just roll back and the database would be consistent.

TBH, performance is not really a big argument for that, maybe for IO Performance, but i agree that performance is not really the best argument for adding another Database option, but reliability and integrity, even in a worst case scenario

**Comment by blakeblackshear** [comment]
Other databases have situations that can result in corrupted database files too. Sqlite has ways to attempt recovery.

**Comment by Serverfrog** [comment]
True, but way harder. If Sqlite has ways to attempt recovery, it fails for me quite often, compare to other DBMS.
Additionally, if Frigate is not the only Application one hosts on his Homeservers, most of them have a Postgresql via cloudnative postgresql running, which most of the times means an HA Setup etc. Which is then not only used by frigate, but other applications as well. What i mean with that is, that for the user that wants a psql Database, they most likely already have one running. And i think that a DBMS like that is more robust than a flat file based one as sqlite.
For my personal experience, i never really had any corruption Problem with things like Postgres or MariaDB, but in sqlite i had that way to often. Specially as i noticed that my setup had sometimes hiccups with IO (either Network, Software or Hardware) over the last years which resulted in many corrupted sqlilte Database

**Comment by NickM-27** [comment]
This is anecdotal, but I've been running the same sqlite file with Frigate for 3 years, Frigate runs on my unraid NAS which has high IO and network activity, I've never had a corruption or any issues. 

If that's happening often to you, it seems like an issue not inherent to sqlite but something else, which may affect postgres too even if it doesn't lead to corruption 

Sqlite has tools to recover, some of which are not automatic, but we've helped users before recover without losing data.

**Comment by hawkeye217** [comment]
Another consideration with additional database engines is the way we store vector information for embeddings. This would require separate code paths and a significant refactor.

**Comment by wuast94** [comment]
i run a kubernetes cluster with network storage and thats another point where sqlite fails horrible. every project i used so far taht uses sqlite in the backend will fail. performance is not the problem on any of them, but reliability, and its not just one person having trouble with it, its a known problem with sqlite. so i also would really like to see a proper database support. until then frigate is just unusable for me sadly.

**Comment by joneshf** [comment]
Here's another anecdote. I've been running Frigate in a Kubernetes cluster for 2.5 years, and the database has corrupted itself 3 times so far (with the latest happening 2-3 days ago). Similarly, other SQLite-based services have corrupted their databases a handful of times over that period. But none of the Postgres databases have corrupted themselves in the same amount of time.

I fully agree that _in theory_ any database can get corrupted. But _in practice_, SQLite is much more likely to get corrupted than Postgres. That's just how it is with SQLite.

At the end of the day, I'm going to continue to use Frigate with its SQLite database, because it solves a problem for me. And unless something changes with SQLite, I'll probably continue to have to deal with Frigate's SQLite database getting corrupted from time to time. That's the trade-off I'm accepting in order to use Frigate.

But I feel like y'all are trying really hard to defend your position with counter arguments, when you don't need to. Just say, "We're not going to support anything other than SQLite, because we don't want to." and be done with it. There's no reason y'all need to come up with explanations about why Frigate won't support a different database aside from "we don't want to." That's a perfectly valid reason to stand behind for a project like this. I personally don't agree with it, but that's not the point here. The point is that no mount of evidence is going to change "we don't want to." But giving counter arguments as the reasoning makes it seem like enough evidence could convince y'all to support another database, when I think any reasonable person can see that's not going to happen.

Sorry for the rant. I'm just a little annoyed at the moment, because this is the third time I've stumbled upon this GitHub Issue when wondering if there's another way for me to deal with Frigate's database decisions. And trying to read the conversation from the maintainer's perspective ends up annoying me more as a user of this software.

**Comment by blakeblackshear** [comment]
We have no intention of ever supporting anything other than SQLite. Said plainly and clearly. We aren't really interesting in rehashing any of the reasons why either or hearing more from users on why we should support alternatives. I have been running Frigate on multiple machines with SQLite since its inception and never had a single issue. These types of issues are exceptionally rare and we support users across Github, reddit, and home assistant forums. It will never make the priority list to consider it.
