### ISSUE TITLE
Forward & backward day buttons for Review

### ISSUE THREAD

**Issue by mcozzo** [blakeblackshear/frigate#12509]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to review alerts and detections easier. 

Reviewing alerts over multiple days requires selecting the calendar icon _and then_ the day. When reviewing multiple days from the previous month, the selection defaults to _today_ regardless of the day being reviewed. This means that it is _calendar > month > day_ to select the next day. 

**Describe the solution you'd like**
I would like a _previous day_ & _next day_ buttons on either side of the _date_ button.
I would like a toggle for _Alerts_ & _Detections_ so that I can combine them for review. 

**Describe alternatives you've considered**
Continually scroll the _alerts_ and _detections_ section. 

**Additional context**

**Comment by hawkeye217** [comment]
> I would like a toggle for Alerts & Detections so that I can combine them for review.

If you open the filter menu from the Review screen, you'll see a switch to enable you to see both reviews and detections together.

**Comment by NickM-27** [comment]
Also worth mentioning that on the latest versions the calendar will start on the month that the selected date is on. 

Can you describe the scenario where you are looking through historical reviews so much at one point in time?

**Comment by NickM-27** [comment]
Thanks for the elaboration. I will say, I imagine many users would be reviewing Frigate daily while away, but I understand some users don't expose Frigate externally. 

> To view the events on 6/28 I select the calendar, the month, the day. Then I want to review 6/29, so I click the calendar button and it defaults to 7/7 so I have to select the month, day again.

that is no longer how it works. If you choose a day on a previous month then the calendar will reopen on the previous month. 

At that point, besides the first selection, it would be a similar number of clicks so I think this behavior being fixed mostly addresses the concern. Adding dedicated buttons for this would only work on desktop (not mobile) as well. I think for now it makes sense to close this since the month selection issue has been fixed, we can revisit in the future if feedback from more users regarding this is received
