### ISSUE TITLE
non-standard aspect ration in >= v0.14 live view

### ISSUE THREAD

**Issue by Patrity** [blakeblackshear/frigate#12620]
**Describe what you are trying to accomplish and why in non technical terms**
I saw in a discussion [HERE](https://github.com/blakeblackshear/frigate/discussions/11767#discussioncomment-9689201) that only 16:9 aspect ratios were to be supported so I thought I'd get a feature request in to allow for other configurable aspect ratios. It seems like 180 degree cameras are becoming more common, which use a 32:9 aspect ratio.

**Describe the solution you'd like**
I'd like a way to configure live view aspect rations, per camera. Preferably in the configuration, but even on the client side, where the other live view configs are stored would be helpful.

**Additional context**
Notice the large amounts of wasted space between the two views.
![SS2024-07-25-19 26 22](https://github.com/user-attachments/assets/c197446a-7b9c-4711-b2bd-bff67af0f0a8)

**Comment by NickM-27** [comment]
Wide angle cameras are funny supported in the ui. I have been using one for many months and using it for development

**Comment by NickM-27** [comment]
The cameras in your screenshots don't appear to be 32:9, the UI still expects some combination multiple of 16:9, there is no feasible way to design the UI around different aspects ratios because there will always be wasted space somewhere.

**Comment by Patrity** [comment]
> The cameras in your screenshots don't appear to be 32:9, the UI still expects some combination multiple of 16:9, there is no feasible way to design the UI around different aspects ratios because there will always be wasted space somewhere when a camera is a different aspect like 4:3, 8:3, etc

You are correct, it appears to have slightly more height with the available resolutions at 4096x1152 and 7680x2160. This is a dual lens camera so I assume there is less vertical space to allow for the stitching to take place.
I completely get the sentiment of only supporting standard aspect ratios for UI consistency, but in instances like this, would it be possible to manually define the best fit for aspect ratio in the camera or dashboard config?

**Comment by NickM-27** [comment]
> This is a dual lens camera so I assume there is less vertical space to allow for the stitching to take place.

it seems to be specific to your camera. My hikvision is dual lens and the stream is a true 32:9

> but in instances like this, would it be possible to manually define the best fit for aspect ratio in the camera or dashboard config?

You already have the ability to re-arrange this camera group so you can make it look better than it does now. 

But full control of a camera's aspect ratio wouldn't, for multiple reasons:
1. Like I said the ratios can't fit together so there will always be black bars. If the camera was widened to become taller then it would force the other cameras to be smaller and it makes the math a lot more complicated
2. also, we have seen many cases where users streams for detect and live are different aspect ratios, so the math would become even more complicated to force a detect stream and a live stream into a different aspect ratio that the user defines.

**Comment by rockenrooster** [comment]
@Patrity 
It is indeed possible to remove those black bars and resize the live view to get rid of the black bars. I have the same issue with a 4:3 doorbell camera.

Since the grid layout can't handle anything that isn't a multiple of 16:9, you have to override the grid layout by editing the HTML of the page itself. The best way I have found to do this so far is by using the Tampermonkey Chrome extension and a userscript (javascript) that runs after the page loads.

Example (before):
![Image](https://github.com/user-attachments/assets/58fe9562-1292-4425-8a56-29c298f0102f)

Example (after):
![Image](https://github.com/user-attachments/assets/93b68d9f-c8cd-43c9-971b-dafcac7f8b0e)

As you can see it removed the black bars for the top right 4:3 doorbell camera.
Now you will have to mess around in the F12 Chrome Dev Tools (inspect element), to find the div that contains your non 16:9 camera stream and manually edit the width/height values until you get exactly what you want.

Here is what my userscript looks like:


```
// ==UserScript==
// @name         Fix 4:3 Stream Container
// @namespace    http://tampermonkey.net/
// @version      1.2
// @description  Adjust height and remove 16:9 aspect class from 4:3 stream container (3rd div)
// @author       You
// @match        https://192.168.137.29:*/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    const MAX_RETRIES = 20;
    const INTERVAL = 500;

    let attempts = 0;
    const interval = setInterval(() => {
        const container = document.querySelector('.react-grid-layout.grid-layout');
        if (container && container.children.length >= 1) {
            const thirdDiv = container.children[2];
            if (thirdDiv) {
                console.log('Modifying 3rd div...');
                // Change height
                //thirdDiv.style.height = '592px';
                //thirdDiv.style.width = '790px';
                thirdDiv.style.height = '61.5%';
                thirdDiv.style.width = '43.3%';
                thirdDiv.style.transform = "translate(134%, 3px)";
                clearInterval(interval);
            }
        }

        attempts++;
        if (attempts >= MAX_RETRIES) {
            console.warn('Tampermonkey script: Element not found after max retries.');
            clearInterval(interval);
        }
    }, INTERVAL);
})();
```

You'll need to change:
1. The div being modified (in my case it was the 3rd div)
2. Change desired height or the width (or both) of the div to match the aspect ratio of your stream. I recommend using percent (%) as to maintain relative size if you ever resize your window.
3. Change the translate values if you need to move the stream around to a different spot (x,y values) (in my case I moved the 4:3 stream closer to the 16:9 stream on the left so they are touching)

If you need to do this for more than one camera, then you'll have to do the same for each in the script too.
Once you have the script done and enabled, note that it will only run when you refresh the page in Frigate.
Also note that I have only tested this while having only one custom camera group, if you have multiple custom camera groups, then I would expect the script to mess up the size and positions of the camera streams in the divs specified by the script...
