### ISSUE TITLE
Nfs and samba support for addon

### ISSUE THREAD

**Issue by alekslyse** [blakeblackshear/frigate#1344]
With all data produced please add nfs and samba possible for the media folder. Its not possible for people on home assistant os to mount nfs except in core that will be overridden. 

Cant be too hard adding the possibility to save media remotely?

**Comment by alekslyse** [comment]
Just for clarification this is for the home assistant add-on to by default save to the media folder

**Comment by privatesam** [comment]
Just map your NFS to a local directory and pass that through to the Frigate conatiner.   Can't be too hard to do that.

**Comment by alekslyse** [comment]
> Just map your NFS to a local directory and pass that through to the Frigate conatiner. Can't be too hard to do that.

In a general docker setup this would be possible, but not with the home assistant addon. Home Assistant OS doesnt support NFS/CIFS in the root system so the docker image needs to do the mounting

**Comment by RobertusIT** [comment]
I use Home assistant OS with supervisor in proxmox, and i didn't understand how to change folder for clips and shot.

So i'm not alone.

Is very important a way to change it, when you use addon and also HA os with supervisor

**Comment by philipp089** [comment]
just for the activity. Bump..

**Comment by HSB-collab** [comment]
### Problem mapping Frigate Media folder to Samba Share
I am running the following setup:

- Home Assistant OS (HassOS) in a virtualbox virtual machine on an Ubuntu 20.04 host (I wanted a Supervised implementation of HA).
- Frigate NVR in a docker container on the same Ubuntu host (this was the only way I could get Frigate to recognise my PCI TPU because virtualbox does not support PCI passthrough)

Until recently, the way I would get the snapshots and clips from Frigate object detection to be visible inside the HA Lovelace UI was to mount the HA media folder on the host using the Samba addon in HA, map this in docker-composer to the Frigate media folder. This enabled me to view the Frigate clips and snapshots using the HA media browser.

Recently, I discovered the Frigate NVR Proxy which allows me to see the Frigate WebUI inside the HA UI which is much more convenient. 

However, when I opened the Frigate UI and went to the events tab it crashed the Frigate container. I enclose the output of the log file. These messages would just keep repeating themselves until I restarted the Frigate container. 

I was able to work around the problem by mapping the Frigate media folder inside the docker container to a local folder on the Ubuntu host machine. The error ### disappeared.

However, that means that I can't view the clips in the Media Browser in the HA Lovelace UI. This is not necessarily an issue as I am not sure I even need the media browser because I can view the clips from the Frigate WebUI. 

However I am curious to know why I can't map the Frigate media folder to a shared folder in the VM? I would appreciate any suggestions. 

[frigate_samba_error.txt](https://github.com/blakeblackshear/frigate/files/7190951/frigate_samba_error.txt)

**Comment by blakeblackshear** [comment]
That bug is fixed for the 0.9.0 release.

**Comment by gcorgnet** [comment]
Hi, to be clear, is there now a way to get Frigate to record (or move) recordings to a local smba shared drive?

**Comment by blakeblackshear** [comment]
If you are using docker directly, you can use any supported volume mount types to mount network shares. There is no functionality built into frigate directly for this.

**Comment by seanblanchfield** [comment]
I came up with a way to reliably map the `/media/frigate` directory to a SMB share on Home Assistant OS (on a Home Assistant Blue), with a security caveat. Hopefully this write-up is useful to someone.
https://seanblanchfield.com/2022/05/frigate-nas-in-homeassistant-os

**Comment by thundergreen** [comment]
@seanblanchfield  I tried to follow your instructions but fail already by uploading the public key :( Import from USB is not there anymore. any ideas?

**Comment by renarena** [comment]
In case it helps in adding this functionality - the LMS Addon let you mount an Samba share and uses it.
https://github.com/pssc/ha-addon-lms/

**Comment by NickM-27** [comment]
This is supported https://docs.frigate.video/guides/ha_network_storage
