### ISSUE TITLE
media to NAS, getting database locked or unable to open database file

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1409]
I got the frigate docker running with two cameras, and clips got stored in the media/clips folder, all worked fine and awesome project. thanks for that.

Now i am trying to use my NAS folder to store the clips and recordings.  so i changed the volumes in the docker-compose to 
volumes:
  - ~/Surveillance/frigate/media:/media/frigate
this location is the mount i made on my ubuntu, I am able to see/create files at this location from file explorer.

when i started frigate, it did create folders like media/clips and recordings and 0kb frigate.db
got error database is locked, upon looking the doc i noticed i can specify the db location.

so on frigate.yml I added this line:
database:
  path: ~/Surveillance/frigate/media/clips/frigate.db

now i get error "unable to open database file"

What should I be doing?

**Comment by D34DC3N73R** [comment]
IMO, it's probably best to keep the database on the local machine. I keep mine in /config/db/frigate.db (right next to the frigate config.yml file). But, to answer your question, you're specifying an external path from within the container. If you define a volume
~/Surveillance/frigate/media:/media/frigate
the db path in frigate config.yml would be 
/media/frigate/clips/frigate.db

**Comment by balajeek** [comment]
I don't know how I would create the volume in docker for the mounted drive on ubuntu, the share is from NAS.

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/issues/712#issuecomment-773586603

**Comment by balajeek** [comment]
Thank you, that helped.  
I set the db to local disk and clips to nas share.
now after few min i get error message that says "consider increasing tmp/cache". what would be best number for 3 1080p cameras.  (sorry if this is off topic)

**Comment by rickgitdone** [comment]
> IMO, it's probably best to keep the database on the local machine. I keep mine in /config/db/frigate.db (right next to the frigate config.yml file). But, to answer your question, you're specifying an external path from within the container. If you define a volume ~/Surveillance/frigate/media:/media/frigate the db path in frigate config.yml would be /media/frigate/clips/frigate.db

I have read through all the docs on how to adjust the location of the database after I also was stuck with database locked error after my initial install... None of the docs nor YouTube videos give any hints why the database error locked pops up... only these threads demonstrate the proper issue.

It would truly help everyone out there who wants to use the docker containers and have the external media separated from the database location because its "required" when mapping /media to a mounted file system. I assume this is a SQLite requirement that isn't documented in the Frigate Docs either... The default configuration should just show local db mapping which I tried several ways with total failure until I gave up removed "ro" from the config.yml mapping and placed the database in the same directory which also works .. was that wrong?

Simply letting everyone know the SQLite database "must" be mapped locally similar to the config.yml mapping but writeable and providing good examples would save hours of questioning what went wrong...
