### ISSUE TITLE
Reduce the number of dBFS and rms writes in MQTT

### ISSUE THREAD

**Issue by duylong** [blakeblackshear/frigate#14119]
Hi,

I have enabled audio on my cameras and I notice a number of writing impressions in the frigate/{cam}/audio/{rms,dBms} files
I have about ten messages per second.

For what use do we need this information in MQTT except to diagnose to determine the min_volume? Is it possible not to write the rms, dBms when the log level is >= info? or can we only write when we have an event?

**Comment by NickM-27** [comment]
many people use this information to show a sound visualizer or for other things like using it as a baby monitor. This is working as intended.

![image](https://github.com/user-attachments/assets/455c26a7-9e33-418c-ab47-e8d3514c82a2)

**Comment by NickM-27** [comment]
It is of course only written if the audio feature is enabled, MQTT can handle thousands of messages per second so the is really no issue with the 2 messages per second per camera. Adding a config option would just be another thing to maintain without any real point because the messages being written does not cause any issue.
