### ISSUE TITLE
A seekbar in the player

### ISSUE THREAD

**Issue by azsde** [blakeblackshear/frigate#14227]
Having a seekbar when reviewing a specific event would be really practical in addition to the current timeline on the far right.

![image](https://github.com/user-attachments/assets/68c4d6dc-176c-4176-a7e7-11b79815398b)

Is it something that could be feasible ?

**Comment by NickM-27** [comment]
A seekbar doesn't make sense because where does it start and end? It wouldn't make sense for the video player to stop playing when a single event stops as the recording view is meant to be used to view all activity not just the specific activity that was clicked. 

There is already a feature request for the ability to zoom the timeline in the case that more granularity is needed.

**Comment by azsde** [comment]
@NickM-27 I agree that with the current approach it doesn't make sense, the timeline zoom will definitely be a welcome addition.

Maybe there could be an option to put the timeline horizontally ? I find it would be way easier for "video seeking".
