### ISSUE TITLE
Compatible with other neural engine hardware ?

### ISSUE THREAD

**Issue by farnots** [blakeblackshear/frigate#143]
Hi, 

The Google Coral USB Accelerator can’t be shipped to my country. I was wondering if it’s possible to use Frigate with other neural engine hardware (Like the Intel Neural Compute Stick 2 for exemple) that support TensorFlow in order to increase the framerate on an raspberry pi.

Thanks a lot

**Comment by blakeblackshear** [comment]
If it is supported in tensorflow lite, probably. I'm sure it would require some modifications though.

**Comment by farnots** [comment]
> If it is supported in tensorflow lite, probably. I'm sure it would require some modifications though.

Ok thanks for your feedback. I just ordered it and I'll try to add a pull request if it's easy to add the Intel NCS2 compatibility.

**Comment by ne0ark** [comment]
Any luck on integrating it?

**Comment by farnots** [comment]
> Any luck on integrating it?

It's a little more complicated to integrate it to Frigate because it's build around Coral equipment

**Comment by frankhommers** [comment]
@farnots Still planning to do it? I have an NCS2 lying around ... Otherwise I have to buy a Coral...?

**Comment by blakeblackshear** [comment]
Closing old issues

**Comment by JavaMachine** [comment]
Any news on this one? Since USB accelerator is hard to find right now, it would be useful if we could use other alternatives

**Comment by alucryd** [comment]
Just ordered an intel ncs2 as the coral has been out of stock for a while now. Did you have the chance to revisit this? I will surely give it a try anyway, would you maybe have some pointers to where I could start? Note that I have zero experience with tensor flow or any other neural stuff, this is a good chance to get into it.

**Comment by blakeblackshear** [comment]
No change. Unless it supports tensorflow lite natively, I don't expect it to be a simple implementation.

**Comment by MostHated** [comment]
This is some information I found on it. https://movidius.github.io/ncsdk/tensorflow.html 

Not sure if it will be helpful, but I definitely, and probably many others, would love to have support for NCS2 or Jetson Nano. I bought the Jetson to try out Deepstack when I first heard about it, which then lead me to learning about this, and I was really hoping to use this with HomeAssistant once I looked into it, but unfortunately, Coral's were nowhere to be found. There seemed to be quite a few NCS2 devices around on the sites in which I looked. As for its compatibility, at the time, the only search results I had found online, prior to finding this thread, were of people asking about compatibility with Frigate and others. 

I am only just dipping my toes into this whole ecosystem, so I don't know much about what all is compatible and capable of working with each other, but seeing Tensorflow show up in searches related to the NCS2 had me hopeful, since I had bought the NCS2 right away a few weeks ago when I saw it was available in hopes that perhaps it might work. So, here's to hope! :partying_face:

**Comment by blakeblackshear** [comment]
It definitely won't be plug and play, but it could be added with some work. Probably not going be be on the priority list for a while, but I will keep it in mind.

**Comment by Proxicon** [comment]
I have a NC2 & Jetson Nano, the coral unfortunately do not ship to my country & its been out of stock everywhere or 2 years  that do - sad that there are no support for NC2 & Jetson Nano which are the more available choices vs coral :-( - will be trying the following over the Dec holz. - https://github.com/e1z0/jetson-frigate

**Comment by katsaplias** [comment]
I have also a NC2 lying around and would be very pleased for any development on this integration, 
thanks!
