### ISSUE TITLE
h265/h265+ support

### ISSUE THREAD

**Issue by mishoboss** [blakeblackshear/frigate#1484]
I plan to get around 10 pieces of Annke 4K cameras and as far as read the newer hardware revisions only support h265, not h264. And turns out this is a problem for Frigate as far as I read other issues here.

What exactly is the problem here and why this new and bandwidth optimized standard is a trouble to be supported? Is it a ffmpeg thing or a Frigate thing? Is it expected to be solved in a near future, or it is some kind of a fundamental issue? If later, maybe I just need to look at other camera models?

Thanks

**Comment by blakeblackshear** [comment]
It's not an issue with frigate or ffmpeg. The majority of browsers do not support h265 playback in a video player. Frigate and ffmpeg will gladly record h265 clips, but you won't be able to watch them on most devices. Until browser support expands for h265 (probably never), this issue will continue. I would strongly recommend getting cameras that support h264 instead. The bandwidth savings are not worth it. I would also recommend cameras that support a substream with a configurable resolution and frame rate.

**Comment by trythatagain** [comment]
Thats what I did, I sent back my Reolink 820a and bought a Amcrest camera, the model and firmware is 2 years old, but it works :)
I did follow a thread on here where a H265 was converted on the fly to H264 when saving, but just couldn't get it to work reliably.

Do as blakeblackshear says, get H264 camera

**Comment by digiblur** [comment]
Indeed..Amcrest/Dahua cameras with all their stream configs are nice especially the models that have the substream 2 option that can be set to 1080p or 720p, great midrange for motion.

**Comment by trythatagain** [comment]
I have Amcrest IP8M-T2499EB , one flashed with Dahua firmware and the latest left with Amcrest firmware. I don't believe the firmware will be updated by either firm, but their not EOL either. In fact the 1 I just received from Amazon needed the latest firmware as it was built with the same build date as my one from 2 years ago, and wanted a flash plugin :(

I actually think the 4k image from the Amcrest is still better than the Reolink 820A. But you do pay for it though :( here in the UK the Reolink 820A was on special at £65 instead of £85, but the Amcrest was £105 even though it's a 2 year old camera/design.
