### ISSUE TITLE
Occupancy detection (feature request, maybe?)

### ISSUE THREAD

**Issue by jcastro** [blakeblackshear/frigate#1493]
Hello!
First of all, thanks so much for this awesome software. I'm having such a fun time playing with it and using it to make my home smarter. In particular to detect occupancy at room level.

I was able to setup Frigate correctly so it can detect occupancy. Sadly to be able to do this I had to do some tweaks to the camera configuration, otherwise if I'm not moving it will think there's no one in the room

These are the 2 parameters I tweaked at camera level

First I increased this value, so it's currently 10x times my frames (10 fps)
```
detect:
      max_disappeared: 100
```

Secondly I had to lower the motion threshold to its minimum, otherwise if I wasn't moving, the detection will say there was no person there anymore
```
motion:
      threshold: 1
```

All this seems to work, however it makes the TPU to work constantly,

What I was thinking is that maybe it would be possible to have default/low resource settings values for threshold and motion but get a new preference specifically to do one last detection before setting the object detection (person) to 0. So let say I have this new preference occupancy enabled
```
motion:
      threshold: 25

detect:
      occupancy: True
      max_disappeared: 50
```
What this would do is right before setting object detection to 0, do one last check to see if the person is still there (but not moving).

Very rough idea but would be really cool I think!

Thanks once again

**Comment by blakeblackshear** [comment]
The current versions just aren't great for your use case. 0.9.0 lays the ground work to decouple events and clips in a way that will make it possible to track an object for a very long time even if they become stationary. There may be some way to creatively use the position of the tracked object form the events mqtt topic, but it's not going to be easy.

**Comment by salleq** [comment]
I don't know if this'll help you at all but I have a workaround for automating my lights by combining a PIR sensor and binary_sensor._camera_.person_motion in to a group (like group.living_room_motion) and using that for automations.
PIR isn't 100% reliable as it needs even more movement than the Frigate provided sensor - which, like you said - doesn't either work for totally stationary objects. However I also have a timer which goes off 5 minutes after the group is inactivated (instead of instantly) - with this I've had my living room lights on when I'm watching TV for instance.

Downsize is that the lights could be on for 5 minutes without anyone in the room but to be honest, most commercial occupancy sensors do not cut power to lights the second motion isn't detected, either.
