### ISSUE TITLE
API for single image for Object Detection

### ISSUE THREAD

**Issue by ledhed-jgh** [blakeblackshear/frigate#14969]
**Describe what you are trying to accomplish and why in non technical terms:**
I would like to take a snapshot at 9pm to check if my car is parked on the street. If the car is there then play a notification in Home Assistant telling me to move it to the driveway.  I currently can't do this because if the car is there for a period of time it becomes a stationary object and doesn't affect the object count in Home Assistant.
 
**Describe the solution you'd like:**
I would like to submit a single image to Frigate for object detection and have the results returned to Home Assistant. It could operate like a custom camera object with object counts.

**Describe alternatives you've considered:**
Installing DOODs 2, but an additional docker container and configuration seems excessive when Frigate can already do object detection and utilize a Coral Edge TPU.

**Additional context:**
An alternate solution might be for Frigate to provide a sensor to Home Assistant that reveals 'stationary object' counts.  However, I do think single image object detection might have more utility.

**Comment by NickM-27** [comment]
> I currently can't do this because if the car is there for a period of time it becomes a stationary object and doesn't affect the object count in Home Assistant.

That is incorrect, the object count is for all objects stationary or not 

In general single image detection doesn't make sense because frigate isn't able to apply the pre processing steps like it does when it detects motion and it also can't use the threshold to calculate if an object is a false positive or not. 

And moreso, you can use the /events API to know the current state of in progress objects as well
