### ISSUE TITLE
Multiple photos to AI to analyze

### ISSUE THREAD

**Issue by mrthosi** [blakeblackshear/frigate#15029]
**Describe what you are trying to accomplish and why in non technical terms**
It would be good, if not 1, but 2 or 3 snapshots would be sent to AI to analyze. Even for people it is hard to check behavior from 1 picture.

**Describe the solution you'd like**
As object lifecycle, it would be nice if multiple snapshots (thumbnails) would be created

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by hawkeye217** [comment]
This is already how Frigate works. Multiple thumbnails are sent to your GenAI provider during object tracking. These "in progress" thumbnails are not saved with the tracked object, so if you use the Regenerate button in the UI, only a single snapshot or thumbnail is sent. This is intentional and we don't intend to save more thumbnails for objects that have ended.
