### ISSUE TITLE
CPU doesn't scale

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#151]
Hi, I noticed that when frigate was trying to analyse detected motion that the overall CPU usage was really low, I then tried it on two cloud servers to see what the difference might be.

Cloud server 1, 2 cores, 2.5fps
Cloud server 2, 16 cores, 3fps

I would expect it to go up a bit more than 20% when I gave it 800% more CPU power, I can only imagine this isn't taking extra cores in to account and if I had a 1 core server I would get similar performance.

Are there any settings I can tweak to make use of multiple cores? Since the idea of AI is to perform many operations in parralel and make use of things like GPU's I can't understand why it's not using the CPU cores more.

I'm going to run a container per camera in the mean time as I think that might give me better performance, and look to order a USB accelerator after pay day :-)

**Comment by blakeblackshear** [comment]
It will use more CPUs for motion detection and decoding the video stream but not for the AI detection. This is because the Coral can only be accessed by a single process at a time and I don't want to bother rearchitecting for CPU mode. A container per camera is the recommended way to scale frigate in CPU mode.
