### ISSUE TITLE
Create a discord server

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#153]
I have lots of questions about Frigate, Coral.Ai, Tensorflow and ML in general but I don't feel these are worth opening as issues on Github. Plus it would be great to chat to like minded people and see what others are doing, again without flooding Github issues. 

Could you create a Discord server for this, I think they are free, you sign up to Discrod and just add a server to do with Frigate, then post an invite link in the Readme.md file.

Not sure if anyone else feels the same.

**Comment by PrplHaz4** [comment]
Matrix/Riot would be a more open solution for chat, but it sounds like you're actually looking for more documentation on how the components fit together.

**Comment by scstraus** [comment]
I personally would rather have Blake working on Frigate than doing AI/ML trainings.. There are already discord servers like this.

https://old.reddit.com/r/learnmachinelearning/comments/6mfwmf/introducing_rlearnmachinelearning_discord_chatroom/

**Comment by mattheys** [comment]
I was thinking more on the lines of stuff specific to frigate and not necessarily Blake answering them, hardly expect it to be a platform for training sessions.

I would like to know why the Dockerfile uses MobileNetv1 for the CPU model and not v2 as it's much more accurate at a small inference time cost. Why I get 2 - 4 MQTT messages to Snapshot on detection. Is anyone using an NVR that can start recording on an MQTT message (or made one themselves) so I can feed low quality streams into frigate and record high quality ones somewhere else. etc, etc. 

These are things that I don't think should warrant the maintainers attention but might be interesting for a community to talk about. Also newcomers might ask more noob like questions in a forum rather post issues on GitHub and I would be willing to help out where I could.

**Comment by blakeblackshear** [comment]
I use the v1 model for CPU because its the one readily available for Tensorflow lite [here](https://www.tensorflow.org/lite/models/object_detection/overview). If you know where I can find v2, please send it over. CPU support is really more for demonstration purposes so people can try it out before buying a Coral. It is so much more efficient that CPU mode just doesn't make sense when you can buy an Atomic Pi for <$50 and blow the performance of the latest i7 away.

You are getting multiple snapshots on detection because frigate sends the first image it gets, but updates it as it find images with a higher confidence scores for the same person it is tracking.

There have been some examples of people using motioneye to start recording on detection. I am also working on my own NVR solution that integrates with frigate.

For the discord server, I am not sure we have a large enough community for people to be in there. I like github issues because it's easier for me to respond when I have time between things in my real life, and the questions and answers are documented and searchable in the repo. It is unlikely I would be on the discord server often enough to answer any questions.

**Comment by mattheys** [comment]
I've put a pull request through for the v2 Model, got it from here ```https://github.com/google-coral/edgetpu/raw/master/test_data ```

The multiple snapshots usually appear identicle, I havn't run it through a hash algorithm yet to check though, going to put an RBE node in node red to see if that removes them.

Will look at Motioneye thanks, although a tight linked NVR would be amazing.

Fair enough about the community not being big enough and the other points, will close now.

**Comment by blakeblackshear** [comment]
Please open a new issue if you are finding multiple identical snapshots

**Comment by scstraus** [comment]
> Also newcomers might ask more noob like questions in a forum rather post issues on GitHub and I would be willing to help out where I could.

There's the [homeassistant forum thread here](https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107), I think it meets most of your criteria.

**Comment by onedr0p** [comment]
It would actually be very helpful to have a Discord server for Frigate, 3 years have passed and the community here has grown a lot.

**Comment by blakeblackshear** [comment]
There are many Frigate users in the #cameras channel for home assistant's discord. We don't have time to moderate or monitor another support channel.

I also don't like providing support via Discord because it's difficult to follow unless you can help in real time and it's not as searchable as github issues.

**Comment by Serverfrog** [comment]
Sory for Necro but one Important thing (which is exactly the reason this necro happend): Discord isn't searchable from normal SearchEngines!

If you "google" something, you will find github issues and discussions, but not a Post on a Discord server. And the first thing, most people resort to as default is to search it on the web.
