### ISSUE TITLE
Leverage on-camera object detection

### ISSUE THREAD

**Issue by mludvig** [blakeblackshear/frigate#15319]
**Describe what you are trying to accomplish and why in non technical terms**

AI-enable cameras that can run object detection models are becoming ever more prevalent and inexpensive too. 

@blakeblackshear - Is there any way to leverage those capabilities and reduce the load on the frigate server? If my camera can send not only the video stream but also the detected bounding boxes Frigate should be able to skip its own object detection (GPU, Coral, etc) and just use what it gets from the camera.

**Additional context**

For example [OAK-1](https://shop.luxonis.com/products/oak-1), [RPi AI Camera](https://www.raspberrypi.com/products/ai-camera/), etc.

**Comment by blakeblackshear** [comment]
Possibly someday. These cameras have relatively small sensors and I have yet to see one that provides enough metadata in real time. I see about as many downsides with this approach as running AI centrally for many cameras.

With a central device, you can share a single 4 TOPS device across many cameras. It's cheaper and more upgradable for both the device running AI and the cameras. When you bake it into the hardware, it becomes hard to make improvements at the pace we are currently doing with Frigate. The hardware available to run on the edge is also improving very fast, so cameras will become obsolete quickly.

The main benefit would come from avoiding the encoding and decoding of the video stream since you can run detection on the raw data.

If cameras become that good at this task, then I largely think Frigate fades away. It just becomes a dumb UI for the data coming from the cameras which is something else entirely. The hardware manufacturers will own that UI and the protocols are likely to be proprietary rather than open.

**Comment by NickM-27** [comment]
Frigate does more than just detect objects, if actively tracks them. The camera events metadata is not enough to do this and means many of frigates features would not work. You can use the event create API to create manual events based on the camera data

**Comment by leeprevost** [comment]
I think this is a valuable question.  

What if frigate is part of the edge device?   

I'm experimenting with RPIZ2 and the new imx500 camera for an underwater device.  The early results are that my custom yolo model performs very well detecting my objects, streaming webrtc, and recording upon detection all with about 25% cpu overhead and 50% ram utilization.  

I need small and low power for my edge device so this rules out RPi 4/5.

I need it to do edge detection and recording without dependence on the network as the network is unreliable in this environment.   Why couldn't frigate manage multiple instances of edge cams that feed frigates grid and rsync the detection videos?
