### ISSUE TITLE
Allow specifying a start timestamp when creating manual events

### ISSUE THREAD

**Issue by Zinurist** [blakeblackshear/frigate#15385]
**Describe what you are trying to accomplish and why in non technical terms**
I want to specify a timestamp when creating manual events via the API. 

I'm not interested in using frigate's motion detection, instead I'm recording 24/7 and want to mark events in that recorded stream.

**Describe the solution you'd like**
Add a start timestamp to the API for creating manual events. There's already an option to set the duration of the event.

From what I can tell, add a parameter [here](https://github.com/blakeblackshear/frigate/blob/bb86e71e6559963a8f562abedef650d9e4265390/frigate/api/event.py#L1132) and use it [here](https://github.com/blakeblackshear/frigate/blob/bb86e71e6559963a8f562abedef650d9e4265390/frigate/events/external.py#L51).

**Comment by NickM-27** [comment]
This isn't really possible because Frigate does not keep recording segments if there is no reason to keep them. So if you create an event with a start time of 30 seconds ago odds are the recordings are already deleted along with the frame data and the API will not be able to get a relevant frame or recordings and the manual event would not be usable. 

The only way this _could_ work is if you have continuous recording enabled, but I think it will complicate the API if there is an optional parameter that will cause an API error if the config is not a certain way.

and in any case, I think it would be helpful to understand your use case of the API where you don't just trigger the API right when something happens along with an indefinite end time and then call the event end api

**Comment by Zinurist** [comment]
I have continuous recording on.

My plan was to use motion events from the camera, simplest solution for me was to have the camera upload files via ftp, then watch for file changes and create events in frigate. Haven't tested it yet, but I think the files are created after the event, so the events in frigate would always be X seconds late.

I was hoping events are simply stored with timestamps in some database, and later overlayed on recorded streams in the UI.

**Comment by NickM-27** [comment]
> I was hoping events are simply stored with timestamps in some database, and later overlayed on recorded streams in the UI.

they are, but the only way that matters is if you have continuous recording on, otherwise it won't work because the recordings won't exist. 

We could make the API function such that if the start_timestamp parameter is provided but a user doesn't have continuous recordings on then the API throws an error but I personally am not a fan of that because I could see it being confusing that the parameter is only usable when continuous recordings are enabled. 

Even still we would have the concern of having to know how long recordings are retained and not letting a user create an event before that time, and the frame used for the snapshot would always be whenever the API was called not at the start of the event.

**Comment by Zinurist** [comment]
So I started using the frigate API now. For my use case I'm probably fine with the delay from the ftp events, I can just look before the event since I have continous recording. I'll also use the export endpoint to get a list of events I can watch directly, you can specify timestamps there (I think I like the export UI more anyway, it's easier to scrub through the event clip). I might try adding the parameter in the future if it helps my setup.

So I don't mind if this issue is closed, but just in case someones wants to still do it:

> a user doesn't have continuous recordings on then the API throws an error
> how long recordings are retained and not letting a user create an event before that time

IMO those 2 are the same error: Someone wants to create an event, but no recording data during the event time is available. But I also don't think it makes sense to tie events to recording data, I would treat them just as timestamps, and the UI can display what recorded streams are available during those timestamps. The API already has a "include_recording" parameter, so it seems like events can be without recordings already?

**Comment by NickM-27** [comment]
> so it seems like events can be without recordings already?

Only if it has a snapshot. And even then, if a user requests a recording and it can't be satisfied that should be an error not a silent occurrence.

I just realized we also wouldn't be able to create a review item from this event, so the main review UI wouldn't work anyway
