### ISSUE TITLE
Allow snapshots to be taken from record stream

### ISSUE THREAD

**Issue by iNIXer** [blakeblackshear/frigate#15455]
### Feature Description
Currently, Frigate takes snapshots from the detect stream, which often has lower resolution (e.g., 640x480) than the record stream (e.g., 1920x1080). It would be beneficial to have the option to take snapshots from the record stream instead.

### Use Case
- When running detection at lower resolution (640x480) for performance optimization
- But still wanting high-quality snapshots (1920x1080) for better visual details
- Without compromising system performance by running detection at high resolution

### Current Workaround
Currently, users have to choose between:
1. Running detection at high resolution (impacts CPU/GPU usage)
2. Accepting lower resolution snapshots
3. Using external tools to capture snapshots

### Proposed Solution
Add a configuration option to specify the stream source for snapshots:
```yaml
cameras:
  camera1:
    snapshots:
      enabled: true
      stream: record  # or 'detect' (default)

**Comment by hawkeye217** [comment]
Snapshots come from the decoded `detect` stream, and Frigate does not decode your `record` stream. Additionally, because two different ffmpeg processes are used to process each stream, there is no guarantee that the `detect` stream will be perfectly in sync with the `record` stream. For this and other reasons, it's not feasible to use the `record` stream for everything that snapshots are used for in Frigate.

However, there is already an API call available to pull static images from your recording streams that you can use for whatever you'd like (notifications, etc):

https://docs.frigate.video/integrations/api#get-apicamera_namerecordingsframe_timesnapshotpng
