### ISSUE TITLE
New web interface scaling

### ISSUE THREAD

**Issue by wjcloudy** [blakeblackshear/frigate#1557]
**Describe the bug**
The new web interface tends to always require vertical scroll - it would be great if the camera views/playback size could be adjusted - screenshots attached. Obviously at some point the camera list has to scroll, but the events viewer is particularly awkward. (This is a full screen browser on 1920x1080 screen)

**Version of frigate**
0.9.0-3340952

**Screenshots**
![screen1](https://user-images.githubusercontent.com/56305354/130030932-211f3e98-d449-45c5-8e35-944fd3a5a02a.JPG)
![scren2](https://user-images.githubusercontent.com/56305354/130030936-7bf672bd-b5e2-4ed2-b175-6671c67f736a.JPG)

**Comment by jcollie** [comment]
I just stared using Frigate (with 0.9.0-rc1) and I'm really liking it so far. The only nit that I have to pick so far is that the camera that I have (Amcrest AD410) has a resolution of 2560x1920. Since Frigate plays almost everything back 1:1 the video is much too large to fit on any monitor I have without scrolling. It would be great if there were a way to keep the recordings at full size but view the cameras in the web browser scaled down. Even better if that could be done dynamically.

**Comment by jcollie** [comment]
Digging around the docs I found the "live" section of the camera settings but this does not appear to actually be working, as you can see from the attached screenshot. I set the height in the live section to 240. I see a ffmpeg process in the container that is resizing the video to 300x240. The web interface is unfortunately scaling that up so that it overflows the screen. I'm not a HTML/CSS/JS wizard so I don't know where things are going wrong from there.

![Screenshot from 2021-08-28 22-20-00](https://user-images.githubusercontent.com/740022/131237249-3a640e58-ff28-49db-b847-4c4aaae4a686.png)

**Comment by dalcon007** [comment]
> I just stared using Frigate (with 0.9.0-rc1) and I'm really liking it so far. The only nit that I have to pick so far is that the camera that I have (Amcrest AD410) has a resolution of 2560x1920. Since Frigate plays almost everything back 1:1 the video is much too large to fit on any monitor I have without scrolling. It would be great if there were a way to keep the recordings at full size but view the cameras in the web browser scaled down. Even better if that could be done dynamically.

Hey @jcollie , I have the same camera and am having trouble getting the substream to work with Frigate. The main stream works fine. Can you share what your config looks like, or at least the rtsp link you are using? Mine is as follows, with a resolution of 720x576:
`rtsp://[credentials]@[ip]:554/cam/realmonitor?channel=1&subtype=0&authbasic=64`

Thank you!

**Comment by jcollie** [comment]
>I have the same camera and am having trouble getting the substream to work with Frigate. The main stream works fine. Can you share what your config looks like, or at least the rtsp link you are using? Mine is as follows, with a resolution of 720x576:
> `rtsp://[credentials]@[ip]:554/cam/realmonitor?channel=1&subtype=0&authbasic=64`

Substream: `rtsp://admin:xxxx@xxxx:554/cam/realmonitor?channel=1&subtype=1`
Main stream: `rtsp://admin:xxxx@xxxx:554/cam/realmonitor?channel=1&subtype=0`

**Comment by dalcon007** [comment]
> > I have the same camera and am having trouble getting the substream to work with Frigate. The main stream works fine. Can you share what your config looks like, or at least the rtsp link you are using? Mine is as follows, with a resolution of 720x576:
> > `rtsp://[credentials]@[ip]:554/cam/realmonitor?channel=1&subtype=0&authbasic=64`
> 
> Substream: `rtsp://admin:xxxx@xxxx:554/cam/realmonitor?channel=1&subtype=1`
> Main stream: `rtsp://admin:xxxx@xxxx:554/cam/realmonitor?channel=1&subtype=0`

Thanks! What resolution are you using in your config? I actually think that is the main issue for me...

**Comment by NickM-27** [comment]
The UI has been rewritten for the next version of frigate. As part of that standard, wide, and portrait cameras are accounted for. Closing as this is no longer relevant
