### ISSUE TITLE
[Feature Request] Live view and Birdseye page should attempt to reconnect on network failures and display large visible alert when browser is experiencing bad network connection or stream(s) stopped

### ISSUE THREAD

**Issue by chrislawso** [blakeblackshear/frigate#15692]
The feature request is to suggest some form of error handling and for the front-end wegui to attempt to reconnect to the birdseye page when the page stops working.
In addition, when the birdseye page stops displaying new video data and is stuck displaying static images the page should display a large alert to notify users. 

Other nice to have features would be the option display in small text over cameras or pages statistical info ie stream analytics that would help users determine the quality of the network connection. Examples could be displaying bitrates, number of dropped frames or any other metrics that could help identify connection quality.

The above requests will be useful to users that connect to frigate remotely or are using less reliable wifi wireless, mobile, etc networks. In my experience when offsite and connecting to a frigate remotely the network connection is sometimes less than ideal and I frequently have the birdseye page freeze with several camera views continuing to display static images but not actually streaming any new video content. Often when this occurs the issue is not immediately obvious because if there is no quickly discernible frozen object in time/space then at a quick glance the birdseye page 'appears' to be working and only upon closer inspection the frozen page and still frames becomes apparent. The only solution currently is to reload the birdseye page in the browser. If possible, the frontend javascript should perform some additional work to re-establish connections and restart the video streams and during the disruptions to streams the pages and video streams should display large alerts notifying user that the connection is broken/ not streaming.

**Comment by hawkeye217** [comment]
There is already timeouts and reconnect logic in place for streams that use go2rtc. We use an [external package](https://github.com/cycjimmy/jsmpeg-player) to play jsmpeg streams (which birdseye uses). The [reconnect logic](https://github.com/cycjimmy/jsmpeg-player/blob/b03021e9cd8dc6ed6cf3b4ead33f3791bc5ef9df/src/lib/websocket.js#L11) is rudimentary but functional, though it may not deal with fluctuating bandwidth issues very well. 

We don't plan to fork and improve the jsmpeg player further.

However, there have already been improvements in this area for Frigate 0.16. If you are using go2rtc, the stream used for Live view will be user-selectable so that a lower bandwidth substream can be used on mobile, for example. A clear indication is also given if there is a low bandwidth condition and the player switches to jsmpeg. Additionally, stream stats can be quickly viewed as an overlay on the camera feed to see bandwidth usage, dropped frames, and latency.
