### ISSUE TITLE
Add symlink like clip support for 0.9.0 release

### ISSUE THREAD

**Issue by pskuza** [blakeblackshear/frigate#1675]
First of all thanks for writing frigate, I'm using it in three different locations and am quite happy. Now of course I had to upgrade to the new 0.9.0 rc2 release which changed the clip behavior.

**Describe what you are trying to accomplish and why in non technical terms**
I know that I can set the recording retention to 0 and thus only keep the triggered events on disk, but I would like to have x days of 24/7 recordings saved on disk locally and additionally have the corresponding event clips (now included in the recordings and not separate like before) in another directory so I can sync them to an offsite location. 

I'd be using rclone or syncthing to point to a directory containing those event recordings to upload them. I can't upload the whole recordings directory since the data generated would be too much.

**Describe the solution you'd like**
A good solution in my eyes would be a config flag that creates symlinks of the recording files that contain an event in another directory.

**Describe alternatives you've considered**
If frigate is not going to have such an option I would consider writing my own script to listen to the mqtt topic event and create the symlink myself.

**Additional context**
.

**Comment by blakeblackshear** [comment]
I would suggest using the mqtt events topic and the /api/events/id/clip.mp4 endpoint to download a clip for backup. A few things to note:

- I would add a delay of 30 seconds before retrieving the clip to ensure the recording segments are ready.
- Don't download too many at once because the files are created at /tmp/cache and cleaned up occasionally. You could fill up the tmp directory.

You could also use the other API endpoints to fetch events for backup.
