### ISSUE TITLE
Recordings Timeview Enhancement

### ISSUE THREAD

**Issue by teslamine** [blakeblackshear/frigate#1695]
Could we please also get a way to see all cameras in the new recordings timeview? The new timeview is awesome.

**Comment by mr6880** [comment]
Do you mean a grid showing all cameras with some sort of synchronised playback?

**Comment by user897943** [comment]
> Do you mean a grid showing all cameras with some sort of synchronised playback?

I believe this is what they're referring to, yes. If you have multiple cameras spanning a road, one pointing left, one pointing right, and one pointing to the center, you could see what's happening on the entire road in sync when you play back the multiple cams. It could even be possible to "drag" the cams into a grid on a canvas to arrange them the way it's best for viewing. This would of course require the camera's NTP to be configured and synced for playback to be seamless....

**Comment by Deckoz2302** [comment]
Adding details I'd like to see, and 👍 this issue in hopes it gets support. I run nine 8mp cameras, five 5mp cameras, and two 2mp cameras  15 in total, which equates to 45 streams between the record(main), detect(sub2), and rtmp(sub1) streams processed by frigate on a j4125 Odyssey Blue, with coral dual edge m2 TPU. The tiny system runs beautifully. And really makes it hard to run a windows PC with blue iris for playback. 

**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to select all cameras with zone driveway, street, sidewalk etc(named zone in the cameras configuration). And play all cameras with that zone configured at the same time instead of going to events, filtering by street, and having to click each event(the same event from a different camera) and watching individually.

**Describe the solution you'd like**
A page similar to birdseye, except for all cameras with 'zone_name' matching, to playback at the same time.

**Describe alternatives you've considered**
On the recordings page, if 24/7 recording is in place, select the camera feeds you wish to display, and have a single time slider bar to scroll through the feeds of all cameras selected for the view.

**Additional context**
Frigate is great at object detection, and it's 24/7 recording is also very good. So much so that it negates running other software such as blue iris. But it is missing one key feature - playback of multiple feeds at the same time. Frigate already handles live viewing of multiple feeds. This is a feature that would really make frigate a very well rounded NVR and all in one solution for most users.

**Comment by NickM-27** [comment]
The ability to review recordings for multiple cameras at once has been implemented as part of the new UI, closing, https://github.com/blakeblackshear/frigate/pull/9985
