### ISSUE TITLE
Using frigate on camera/nvr recorded clips

### ISSUE THREAD

**Issue by psyciknz** [blakeblackshear/frigate#185]
Anyone looked at the possibility of using clips from a camera with motion detection enabled rather than processing the entire stream via rtsp and reporting on that?

Would be slower for images to come out as it would have to wait for the clip to be generated.  But would allow for less processing and only show me the stuff of interest rather than having to process everthing from each camera.

**Comment by blakeblackshear** [comment]
It probably makes more sense to use some of the built-in image processing integrations for Homeassistant if you don't want real-time analysis. Frigate isn't designed for that use case.

**Comment by dinki** [comment]
> It probably makes more sense to use some of the built-in image processing integrations for Homeassistant if you don't want real-time analysis. Frigate isn't designed for that use case.

Hi.  I stumbled upon this project with the intent of what the OP is suggesting.  I'd like to take my motionEye captures and filter out things like bugs/spiderweb/tree movement false positives.  I don't care about realtime captures but rather culling out false positives so that I can increase my retention as well as keep only 'good' clips.

Can you speak to how this might be done with the built-in image processing integrations for Homeassistant?  Admittedly, I'm just getting started at looking at this and would appreciate any guidance and/or pushes in the right direction.

All the best to you!

**Comment by blakeblackshear** [comment]
I would suggest giving Frigate a try. It may use less CPU than motioneye and it will automatically filter clips based on detected objects too. Seems like you would end up chaining a bunch of complicated pieces together to accomplish the same thing with less features and worse performance.

**Comment by dinki** [comment]
Thanks for the speedy response.  I'm running this on a PC based Linux server, Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz w/ 16GB RAM, with all my software running in Docker.  I'd prefer to use my existing hardware if possible as I'm not sure how easy it would be to integrate Google Coral with Docker plus the additional cost.  Do you think what I'm wanting to do is possible with the hardware I have?

**Comment by blakeblackshear** [comment]
That will handle it without even breaking a sweat. Take a look at the Coral devices here: https://coral.ai

The simplest option is the USB, but there are other form factors too.
