### ISSUE TITLE
Use tmpfs for temp recordings and only write to media storage during events

### ISSUE THREAD

**Issue by jasonpstokes** [blakeblackshear/frigate#1885]
As per comments [here](https://github.com/blakeblackshear/frigate/discussions/1502#discussioncomment-1280234), the recording changes in 0.9 are positive and have long-term storage benefits, but the continual recording requires any external storage/NAS devices to stay powered on/spinning. If tmpfs could be used to store temporary clips so Frigate only writes to media storage during detected events (if `retain_days: 0`), then any external devices/NAS could power down/sleep during periods of no object detection. i.e. when no one is home, or overnight.

(I have seen a small increase in my rack's power usage since moving to 0.9, with my 2-bay NAS running 24/7.)

**Comment by blakeblackshear** [comment]
There are some changes needed to make this work, but it's on the list for post 0.9.0.

**Comment by jaytea33** [comment]
Really excited for this feature - I've reverted to only taking Snapshots for now since that way it doesn't constantly write to the drive. But another reason this is essential imo is if you ever plan to use something like rsync to continuously sync your footage to the cloud. The way it is now, it would be in a constant state of upload rather than just when an event is detected due to the constant write modifications, and since the 5 minute temp files are in the same folder as the clips, a folder exclusion wouldn't be a viable option.

**Comment by cpuks** [comment]
How's retain_days going to work since in 0.10.0beta5 it's deprecated for retain modes?
Should I keep retain_days: 0 if I don't want 24/7 recording for now and have retain modes specified or I can ditch retain_days since I have retain modes set?

**Comment by blakeblackshear** [comment]
The `days` section just moved under `retain`. See example here: https://github.com/blakeblackshear/frigate/discussions/2447

Note that the new retain modes apply to the cache copy operation too. Using the new modes will reduce writes to disk even more.
