### ISSUE TITLE
Implement a Healthcheck

### ISSUE THREAD

**Issue by Draxter** [blakeblackshear/frigate#2299]
**Describe what you are trying to accomplish and why in non technical terms**
As a user, I want Frigate container to have a healthcheck, so that the container failure can be detected if sometthing goes wrong.

**Describe the solution you'd like**
It would be best practice to add a healthcheck Dockerfile so that every user gets it by default. It would be useful to monitor two things:
Whether the frontend is reachable with a web request, like so:
```
HEALTHCHECK  --interval=1m --timeout=3s \
  CMD wget --no-verbose --tries=3 --spider http://127.0.0.1:5000/ || exit 1
```

And whether ffmpeg is running, as it has a tendency of sometimes failing for invalid data while the frontend continues to work fine.
Something along those lines?
```
if ps aux | grep ffmpeg | grep -v grep > /dev/null
then
  exit 0
else
  exit 1
fi
```

**Describe alternatives you've considered**
A healthcheck can also be added in the docker-compose.yml file, but then users would not get it by default.

**Additional context**
This issue was explored in #53 But the solution there does not work, as 'curl' is not present on the container.

**Comment by blakeblackshear** [comment]
I would suggest monitoring `/api/version` or `/api/stats`. Frigate already monitors ffmpeg for failures and restarts when it is no longer running.

**Comment by Draxter** [comment]
@blakeblackshear Thanks for the api endpoints, very useful. could indeed query that with the command I posted above.

Are you sure that Frigate monitors ffmpeg for failures and restarts when it's no longer running? I hopped into the container and ran pkill on the ffmpeg processes and the container kept running despite the stream no longer working in the web UI.

Logs did show errors, but that's about it:
```
INFO    : front_camera: ffmpeg process is not running. exiting capture thread...
ERROR   : FFMPEG process crashed unexpectedly for front_camera.
ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
ERROR   : You may have invalid args defined for this camera.
INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:44964]
INFO    : front_camera: ffmpeg sent a broken frame. memoryview assignment: lvalue and rv
```

**Comment by Draxter** [comment]
Yeah... It does restart one of the ffmpeg processes, but that does not fix the stream. Then again, wheile testting I pkill'ed multiple ffmpeg processes, and only one comes back. Perhaps that is not a realistic scenario. WOuld still be good to be able to monitor stream health.

**Comment by dannysauer** [comment]
> WOuld still be good to be able to monitor stream health.

That's a camera healthcheck; not a frigate healthcheck. :)  The guideline to follow is "does restarting the container fix the problem?"  If yes, then include that in the thing the healthcheck calls.  If no, then the external dependency status can certainly be exposed through an API or whatever, but should not trigger a container restart. :)

**Comment by NickM-27** [comment]
This has been implemented in 0.13

**Comment by sochartgit** [comment]
Thanks for your fast reply. I have tried v0.13 and the latest dev image too and still can't find the script.
Portainer still reports the container as unhealthy. Could you please explain where I'm wrong ?
Thanks a lot.

**Comment by justJackjon** [comment]
@sochartgit - I haven't used portainer, but if you can customise your health check to just `curl`, `wget` or otherwise call an http endpoint, I found just calling `/api` suffices. It will bung you a 200 OK back and report "Frigate is running. Alive and healthy!" in a html response. Fits the bill of an endpoint to quickly verify the service's operational status.

`/api/version` or `/api/stats` has also been suggested above, but for the latter suggestion I personally found I had no need to do anything with the stats included in the `/stats` return payload and the response time is slower for that endpoint (I haven't read the source, but presumably there is some logic executed to calculate that statistics being sent back in the json payload). `/api/version` works too, but the response content of `/api` just felt a little more idiomatic for a health check so I just rolled with that.

**Comment by Tyler-2** [comment]
Is there a healthcheck endpoint that the nginx bits are configured to not log? I don't like seeing a log entry every time Kube does a health check.

**Comment by giri-v** [comment]
I'm trying to implement restarting the container on a failed health check with this:
```
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://frigate:5000/api/stats || kill 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 240s
```

But this fails immediately after:
```
...
2025-12-30 20:59:21.723536434  [2025-12-30 20:59:21] detector.coral                 INFO    : Starting detection process: 399
2025-12-30 20:59:21.725735116  [2025-12-30 20:59:21] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
```
regardless of the `start_period`

I think the container's healthcheck is automatically triggering the `kill 1`.

Any ideas?

**Comment by christoftaylor** [comment]
> I'm trying to implement restarting the container on a failed health check with this:

@giri-v, you are not alone. It took me way longer than it should have to figure out why my unhealthy containers were never magically correcting themselves. 

`healthcheck:` in a docker-compose.yaml does NOT restart the container. It just adds the "(healthy)" or "(unhealthy)" to the name depending on the test results. In order to auto restart on unhealthy, you need some external force. Most common is to run another docker container called "willfarrell/autoheal" or one of its alternatives. This autoheal container then handles the restarts for you.
