### ISSUE TITLE
Filter false positives by estimated size of a person

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#23]
Should be able to use this to collect data and compute an estimated person size. https://docs.scipy.org/doc/scipy-0.15.1/reference/tutorial/interpolate.html#multivariate-data-interpolation-griddata

**Comment by blakeblackshear** [comment]
Not stale

**Comment by blakeblackshear** [comment]
Duplicate of #2330

**Comment by ozett** [comment]
i would not consider this as a duplicate of https://github.com/blakeblackshear/frigate/issues/2330
because in https://github.com/blakeblackshear/frigate/issues/2330 a size-definition for **every object-type**.

it would help to prevent illogical detection sizes (compared to human definited values, means based on camera level oder perspective of the camera. objects could be bigger in front of the camera instead of the background, but size must also be within logical bounds compared to other object-types or camera-resolution.)
