### ISSUE TITLE
[Support]: Box-dimensions on MQTT negative?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2574]
### Describe the problem you are having

i want to crop the region/box from the snapshot 
i use node-red and image tools to crop from the mqtt-values of frigate. seems x,y,x2,y2
but from time to time a value is negative.
is this a bug?

### Version

DEBUG 0.10.0-DB1255A

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/5937811/147938913-c39192db-d970-4f67-a722-e59442cd81c9.png)

**Comment by ozett** [comment]
also the box-values over MQTT seems not correspond 
with the painted box on the snapshot. 
(made a special-marker "shift-c") in irfanview to check.)

is this my misunderstanding of the values - a timing-problem -  or
can i get the box-dims for the snapshot elsewhere?

![image](https://user-images.githubusercontent.com/5937811/147942849-f753f17b-2149-486c-aeb0-d40cb6999ad4.png)

**Comment by blakeblackshear** [comment]
Note that the `frame_time` and the `snapshot_time` are different here. The box coordinates are from the current frame, but the snapshot is from a previous frame. This is expected behavior as the snapshot does not update for every frame, just the ones that are determined to be better. The coordinates would only match when the `frame_time` and `snapshot_time` match.

**Comment by ozett** [comment]
thanks for diving into this..

that means, that the grabbed snapshot image has a already drawn box-marker, 
which coordinates are _not_ send via mqtt with the event-id. -- ok.

to get a cropped box of a detection with the mqtt-box-coordinates, 
i have to grab the clip (what i already do) and extract one image at given frametime (one image extraction seems doable)?

is there a ffmpeg-way to adress this specific frame (at that frametime) in the downloaded clip,
to extract that frame for that known mqtt-box-region coordinates?

or any other way to get a crop-image of  the (best) detection-box for that event?

thx.
by the way: do the negative coordinates for the detection box values need an $abs() ?

**Comment by blakeblackshear** [comment]
I _think_ the coordinates can actually be negative because the region can go outside the boundary of the frame, but that could be a bug. For example if its a portrait mounted camera the width of the region may need to go beyond the actual width of the frame to ensure it maintains a square aspect ratio.

You will always get an mqtt message when the snapshot time updates, so I would just crop the snapshot image when snapshot_time and frame_time match. I think what is ultimately needed here is the ability to grab a frame from the API by the frame time. There will always be a race condition for downstream re-analysis jobs using the events topic if using snapshot and/or latest.

**Comment by ozett** [comment]
my goal was to get the bounding-box region with the best box/view of the object detection 
for the video-sequence (means: event-id with end-message).
(to feed this into the object-identifier with the bird-model).

my approach is:
grab the video for that event-id when mqtt sends the end-event,
grab snapshot of this even-id and crop from the mqtt-coordinates.

problems seems to rely on the mqtts values of the "end"-event
for getting the best object-detection region/image.

solution could be to grab the right snapshots,
so grabbing all snaphots while mqtt-send "update" events....
brings some other problems...

i can think of some other ways to fiddle this out, 
but also to prevent a 2nd analysis to get box-coordinates:
do you plan to change something on the frigate side ? 😄

**Comment by ozett** [comment]
demo-image brings some color into threads 😄 

![image](https://user-images.githubusercontent.com/5937811/148185413-9772b9a1-d9f8-4936-a682-03f9bfd60711.png)

**Comment by blakeblackshear** [comment]
You may have to store the coordinates when snapshot_time and frame_time match so you know the coordinates for the snapshot image. Then on the end event, you can fetch the image and crop.

**Comment by ozett** [comment]
i will try this.. thx.

in the longer run that suggestion https://github.com/blakeblackshear/frigate/discussions/1697#discussioncomment-1293312
from @tve seems convincing... 

get all detections with mqtt and use more than only one image to try classification.
would be great to see something like this build into frigate... 🙈

**Comment by ozett** [comment]
it seems a similar problem, now with the region-dimension.
they are bigger than the image-dimensions itself.

is this possible? or a bug?
(if no bug, than i have to build a workaround in the flow)

![image](https://user-images.githubusercontent.com/5937811/172161567-793fbf53-d8fb-4f35-853a-1d452f16db09.png)
