### ISSUE TITLE
Record actual clips that cover entire events, separate the continuous recording to its own folder

### ISSUE THREAD

**Issue by Bod1985** [blakeblackshear/frigate#2591]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to record clips that have events to one directory and continuous recordings to a different directory. This would allow me to upload clips to cloud storage and limit continuous recordings to my NAS

**Describe the solution you'd like**
Continuous recording records as it does now to recordings folder by date. 

Clips folder is utilised for a form of ‘duplication’ of the recording but perhaps combined to a single file by ffmpeg? So a 1 minute 45 event would have a 1 minute 45 clip.

It would make sense to be configurable and some people won’t wish to have duplicate data for storage reasons.

**Comment by NickM-27** [comment]
Just curious, is there any reason you can't check the length of the file and only upload ones that are < reasonable clip length?

**Comment by blakeblackshear** [comment]
You can use the api and/or the mqtt topics to easily create mp4 clips for each event as desired. There are endpoints for this already. Here was a similar request: https://github.com/blakeblackshear/frigate/issues/1675

**Comment by Bod1985** [comment]
> Just curious, is there any reason you can't check the length of the file and only upload ones that are < reasonable clip length?

Continuous recordings also generate short clips iirc so this wouldn’t be a reliable approach

**Comment by Bod1985** [comment]
> You can use the api and/or the mqtt topics to easily create mp4 clips for each event as desired. There are endpoints for this already. Here was a similar request: #1675

I will look into doing this, thank you. 

I still think my feature request has value, in my opinion it’s more of a core feature than one that should need an API call and automation built around?

**Comment by seanb-uk** [comment]
I agree with Bod1985.

Prior to the latest release, clips were stored in the clips directory and it was simple to pick them up to sync offsite.

The problem with writing a script to pick them up as quickly as possible is handling the delay to ensure that segments are ready, and not downloading too many clips at once (as per the comments on #1675 while also ensuring that no clips are missed.

Getting that right would be a moderately complex script to reinstate functionality that was there in the older version of Frigate.

**Comment by NickM-27** [comment]
@seanb-uk If my understanding is correct, the issue is that the reason the old clips dir was moved away from for recordings is because it was inefficient and added complexity / redundancy. Now Frigate holds the segments and dynamically generates the clips from those segments. So to me it doesn't seem as simple as "just put back old functionality" as it would basically be reverting an improvement. 

It's not available today, but I have a pr #2643 which allows bookmarking certain events. So it may be a way to only move the important ones (marked as retain) offsite and not produce as much unnecessary traffic

**Comment by seanb-uk** [comment]
@NickM-27 I understand a lot was probably restructured, it's just a bit frustrating because I had a simple little script based on inotifywait that copied clips as soon as they were written to a directory that gets synced offsite, giving me a secure backup. It's a bit tricky to replicate that now, using the APIs.

I'm only interested in clips, rather than recording, so I've got retain days set to zero, but the old version was, in my opinion, a bit better for users who only want motion detection clips.
