### ISSUE TITLE
frigate/<zone_name>/<object_name> include snapshot image

### ISSUE THREAD

**Issue by clockworkant** [blakeblackshear/frigate#2662]
**Describe what you are trying to accomplish and why in non technical terms**
I want to send the snapshot image when there is a person in a zone.

**Describe the solution you'd like**
Add a "snapshot" field to the mqtt end point for zones/objects. The current payload looks similar to this:
```
{
   "topic":"frigate/in_front_path/person",
   "payload":"0",
   "qos":0,
   "retain":false,
   "_topic":"frigate/in_front_path/person",
   "_msgid":"76e7f282ee882c23"
}
```

**Describe alternatives you've considered**
I could subscribe to the mqtt topic for the camera snapshot such as `frigate/front/person/snapshot` and attempt to pair up this snapshot with the topic for the zone/object. It's probably possible as I *think* that the snapshot is fired before the zone event. It would be cleaner if the snapshot was attached to the zone event though.

**Additional context**

**Comment by blakeblackshear** [comment]
You are much better off subscribing to the `events` topic where you have the actual event_id. There can be multiple objects in the zone and no way to know which snapshot to send. Otherwise, I would recommend just grabbing latest.jpg to get the current frame.

You will never be able to reliably coordinate between the snapshot and zone topics.

**Comment by clockworkant** [comment]
I see, that makes sense. I'll subscribe to the events topic and use the http api to get the clip and snapshot.

Thanks for taking the time to explain things 🙂.
