### ISSUE TITLE
Record Multiple cameras on Single Event

### ISSUE THREAD

**Issue by AbDhops** [blakeblackshear/frigate#2759]
**Describe what you are trying to accomplish and why in non technical terms**
I have multiple cameras covering my back yard. I would like to have record the stream from different cameras if any of them detect a motion.

**Describe the solution you'd like**
Combine different cameras to record video on motion events from different cameras. E.g. create group of multiple events which could be trigger from motion. And then record group of cameras. 

**Describe alternatives you've considered**
There are no alternatives. 

**Additional context**
** None **

**Comment by Bod1985** [comment]
I believe manual triggers is a planned feature as per https://github.com/blakeblackshear/frigate/pull/1927 which could (hopefully) be used to automate the triggering of a different camera to the one detecting the object.

**Comment by DrSpaldo** [comment]
I am also interested in this and hope as @Bod1985 says it will be planned with [#1927](https://github.com/blakeblackshear/frigate/pull/1927)

**Comment by blakeblackshear** [comment]
It is still planned, but it won't make the cut for 0.10.0.

**Comment by VictoriousCupid** [comment]
untill this is available as an option (which I look forward too) I have the cameras set up as normal and set them up with the recording roles crossed

like:

      inputs:
        - path: camera 1
          roles:
            - record
        - path: camera 2
          roles:
            - detect
            
and

      inputs:
        - path: camera 2
          roles:
            - record
        - path: camera 1
          roles:
            - detect            
            
It is an ugly solution and it delivers double cameras in frigate. But whether there is an event on camera 1 or 2 I have recordings from both.

**Comment by danmandle** [comment]
Bump! When is this feature planned to be released? I have two cameras that have overlapping views, but one triggers earlier (and more reliably) but I want it recorded on my other camera too.

Maybe trigger recording of a camera that has a shared zone?

**Comment by gitboi-99** [comment]
I'm also still keen for this feature. Can this issue be re-opened or should a new one be created?

**Comment by VictoriousCupid** [comment]
You can use a curl command to manually make an event. Plug that in an automation and presto.

**Comment by danmandle** [comment]
> And draw the rest of the owl

@VictoriousCupid I get the gist if what you're saying, but can you give some examples? How much latency does this introduce? 

I'd still like to see where all cameras that share a zone will trigger an event for the whole zone.

**Comment by bracklanna** [comment]
Any further discussion or development on this feature request?

I have a location where I have a detail camera (camera A) with a ~45º FOV that works well for detection. I have another camera (B) pointed at the same area, but with a huge 180º FOV that doesn't work well for detection because objects appear very small in its huge FOV.

I want an Event detected on camera A to trigger recording on camera B so that it captures both camera A and camera B's footage during the event.

I've briefly come across google results suggesting using 3rd party HA integrations to achieve this but I don't run HA and would prefer to just achieve this directly inside Frigate alone.

**Comment by NickM-27** [comment]
Not really, you could use motion recording or just use object detection, I have a 180 degree camera as my primary camera on the front of our house and it works without any issue to detect objects

**Comment by DrSpaldo** [comment]
It would be nice if the issue could be considered for the rest of us, even if it isn't needed for you Nick...  Blake said in 2022 this feature was planned?

**Comment by NickM-27** [comment]
It can already be implemented with home assistant using the create event service. 

I pointed out that it works for me because the user most likely has something misconfigured on their panoramic camera as there's no reason object detection can't be run on those cameras.

**Comment by DrSpaldo** [comment]
@NickM-27 thanks for the reply. I can't speak for everyone, but I would hope that it is part of Frigate and doesn't need to rely on another service, Frigate is for our NVR, cameras, etc. Using HA to make a workaround isn't exactly what this request was for... It adds one extra spot for failure that shouldn't be needed

**Comment by NickM-27** [comment]
it's certainly possible it could come in the future, but I don't believe we see this requested and this request was closed as stale some time ago.

This has a lot of complexity, especially as different users will want a large degree of customizability in specific behavior, which would make it quite complicated to implement, test, and maintain. Whereas using an external script / automation platform provides all the flexibility the user needs to make it work exactly as they want.

**Comment by danmandle** [comment]
Am I missing the complexity here? I think it's pretty straight forward. When an event occurs in a shared zone, record both cameras.

**Comment by NickM-27** [comment]
> Am I missing the complexity here? I think it's pretty straight forward. When an event occurs in a shared zone, record both cameras.

Off the top of my head, I can see many different variations users would want for this:
- Only share specific zones, not all of them
- Share based on overall motion not object detections
- Only share at certain times
- Ability to enable / disable sharing dynamically

Also, there is a lot of complexity internally. There is no such thing as an "event", there are review items which are distinct periods of time, meaning only one period of activity can exist on a camera at a time. This means if both cameras have object detection enabled we would need some way to make sure the review items start times are consistent, and there are other collisions such as loitering zones.

also is it one way like the user described (Camera A -> Camera B) or does it go both ways (Camera A <-> Camera B).

While it might seem simple to you, and I'm sure you could answer all of those questions, what one users thinks is intuitive is often unintuitive or not the desired behavior for another user. Hence, we would either need a lot of configuration options, or require a lot more thinking through how this could work.

**Comment by posicat** [comment]
I'd honestly just add it as another overlay on the images.  "If something happens in this zone" also trigger these cameras" should allow plenty of flexibility, and allow people to say "only the driveway stairs" or "if the pool is triggered, record the fence gate too".  Maybe with the addition of "add X seconds of recording time past the trigger".

The example today was :  I think a dude in a neon jacket came to check my gas meter, it's on the side of my house, where my trigger zones are pretty narrow (Or I end up recording the neighbors all the time because their flower garden is there) but I would have loved to see where the dude went when he went up the stairs and towards my side yard.  Putting a bounding box around "stairs" and saying "also record side yard for 30 seconds" would have been enough to catch the action.
