### ISSUE TITLE
Don't send MQTT messages for deleted and extended events

### ISSUE THREAD

**Issue by tjedmunds** [blakeblackshear/frigate#3255]
I recently deployed an offsite cloud storage solution for events and this revealed a strange situation where events are deleted by Frigate. As soon as an MQTT ‘end’ event occurs I copy the snapshot and video clip to an offsite server. Yet every once in a while I see an event ‘disappear’ from Frigate but I have a copy offsite. 

What I now know is happening is that sometimes events get deleted and extended as a new event. In this situation 2 events were created for the same camera with the exact same start time but different end times. The event id is the same except for the 6 somewhat random characters in the file name. The first shorter event was short lived (though it existed long enough to copy it offsite) but is soon deleted from Frigate. The links to the clip/snapshot all say event not found.

The second event was 12 seconds longer and the beginning of this clip is identical to the now deleted clip of the first event. Presumably I copied the first event offsite during this 12 second window and then it was deleted.

This results in some ‘undesirable’ side effects like an unnecessary phone alert for the first event with a broken image link, and extra storage on my cloud setup. Ideally, I wouldn’t see an MQTT ‘end’ event for the first shorter event and this is the ‘feature’ request.

**Comment by blakeblackshear** [comment]
This is because frigate consolidates events that overlap like this after the fact. Events are created per-object and tracked/managed independently. There isn't a way for frigate to know ahead of time when the second event would end, so I can't really prevent the end message for the first object.

Consider a situation where two people are tracked. The first person enters the frame and sticks around for 15 minutes. The second person walks across the frame and leaves 7 minutes after the first person arrived. In this situation I wouldn't want to consolidate the events since you might not ever realize the second person briefly walked by. I can't know this ahead of time.

**Comment by tjedmunds** [comment]
Perhaps if there was a ‘delete’ MQTT message with a JSON property that indicated if the event was deleted by the ‘user’ or ‘system’ I could then delay the phone alert until some timeout value and also cleanup deleted events from the cloud server.

**Comment by tjedmunds** [comment]
On second thought, I can probably just cache the last event's camera and start time for something like 30 seconds to weed out these bogus messages/events.
