### ISSUE TITLE
Option to create clips on motion where objects are not detected

### ISSUE THREAD

**Issue by hawkeye217** [blakeblackshear/frigate#345]
There’s a couple of things I like about my current setup with Zoneminder and Frigate together:

1. I can change “run states” in Zoneminder so that I can have a different set of cameras (and modes for each of those cameras) enabled or disabled at various times of the day.
2. I can use Zoneminder’s motion detection features and alter the appropriate detection thresholds to record clips in addition to having Frigate externally trigger clip recording in Zoneminder. So I can record for both motion (unidentified objects) and detected objects.

On the HA forums, you said:

> You mean like motion clips to record even if no objects are detected? There is definitely a way to calculate a value for motion, so that should be possible too. Should be fairly simple to incorporate into the existing event framework.

It looks like you have plans to develop the first one, but the second one would be super helpful in being able to dump Zoneminder and use Frigate exclusively. With Zoneminder, I can create zones much like can do in Frigate with an image map, and then I can set particular parameters for detecting motion within that zone - like the amount of pixel variation, the min/max size of the variation, etc. (see https://wiki.zoneminder.com/Defining_Zones for more details). Frigate wouldn’t have to be that elaborate, but to have some control over it would be great as well. 

Thanks for considering!

**Comment by hwinkel** [comment]
In this case it makes a lot of sense to have the motion bounding box on the region segment or full frame recorded. Especially this material might be used for training model too ?

**Comment by hwinkel** [comment]
Further, coming from hikvison cams and NVR, it Would be nice to trigger such recording based on line crossing (with directions) and entering and leaving zones. Object recognition is nice, but as long the object model might be not ideal, having some options to detected and track motion of an "unknown" object of a certain size which crosses lines, enters and leaves region would give us the same features we have on the Hik NVR (which is a pain to configure and operate due to the browser incompatibilities)

**Comment by NickM-27** [comment]
Going to close this given that motion based recording is supported and in 0.13 motion events can be created using the custom events API
