### ISSUE TITLE
[Support]: missing link in Frigate documentation 'RTMP'

### ISSUE THREAD

**Issue by mchangsp** [blakeblackshear/frigate#3481]
### Describe the problem you are having

The documentation page https://docs.frigate.video/configuration/rtmp/ mentions
QUOTE
If your camera doesn't support a compatible format for RTMP, you can use the ffmpeg args to re-encode it on the fly at the expense of increased CPU utilization. Some more information about it can be found [here](https://docs.frigate.video/configuration/faqs#audio-in-recordings).
ENDQUOTE
The page https://docs.frigate.video/configuration/faqs does not exist
here can I find the ffmpeg arsg to re-encode on the fly?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
not applicable
```

### Relevant log output

```shell
not applicable
```

### FFprobe output from your camera

```shell
not applicable
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

Not applicable

**Comment by NickM-27** [comment]
That docs points me to https://docs.frigate.video/faqs#audio-in-recordings which resolves just fine 🤔

**Comment by Parlane** [comment]
> That docs points me to https://docs.frigate.video/faqs#audio-in-recordings which resolves just fine 🤔

If you navigate directly to https://docs.frigate.video/configuration/rtmp/ then you click "here" it does navigate to "https://docs.frigate.video/configuration/faqs#audio-in-recordings"

If you navigate by clicking RTMP on the left sidebar then click "here" it navigates to the correct page. But if you hit f5 and click here, the link is broken again. It seems like relative paths are the issue here.

**Comment by Parlane** [comment]
HTML on first navigation by the side bar:

![image](https://user-images.githubusercontent.com/86614/179630872-c98aa202-af8c-49cb-b75e-fd9c3c6f4d34.png)

HTML after hitting f5 on the rtmp page:

![image](https://user-images.githubusercontent.com/86614/179630914-03c96cd6-7ab0-4c17-ac32-de44e8b76ea8.png)

**Comment by Parlane** [comment]
The link to faq uses a ../faq for some reason instead of a /faq:

I was trying to see why it didn't have the same issue on other pages like docs/guides/getting_started.md
Frigate supports many configuration options for mqtt. See the [configuration reference](/configuration/index#full-configuration-reference) for more info.

I think you can just change the docs/configuration/rtmp.md to use:
Some more information about it can be found [here](/faqs#audio-in-recordings).

**Comment by Parlane** [comment]
> I see now, I can reproduce that, it adds `/` when refresh is done. Seems to me like a docusaurus bug but will need to see

The adding of / is a 301 redirect from netlify, seems to be a common thorn in the side for people....

https://support.gatsbyjs.com/hc/en-us/articles/360056349113-Remove-trailing-slash-in-Netlify-URLs

**Comment by NickM-27** [comment]
@Parlane You figured it out, feel free to make a PR to fix it
