### ISSUE TITLE
What inference model are you using? Can I use a custom model?

### ISSUE THREAD

**Issue by wuhongsheng** [blakeblackshear/frigate#3785]
What inference model are you using? Can I use a custom model?

**Comment by NickM-27** [comment]
The default model is linked here: https://github.com/blakeblackshear/frigate/blob/release-0.11.0/docker/Dockerfile#L124

Custom models are supported: https://docs.frigate.video/configuration/advanced#model

Going to close this as completed as these are already supported and it's not clear what the enhancement is (since none of the default included questions were answered).
