### ISSUE TITLE
Allow to enable/disable motion detection from Frigate UI and `frigate.yml`

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4326]
**Describe what you are trying to accomplish and why in non technical terms**
I can disable from Home Assistant:

![image](https://user-images.githubusercontent.com/29582865/200675331-04f5795c-3aa4-4aa6-b66b-fd2b1ce331c9.png)

But I can't disable it from the Frigate UI or the configuration file.

![image](https://user-images.githubusercontent.com/29582865/200675625-cc05646f-e987-4831-b96a-1f65c76eaa15.png)

![image](https://user-images.githubusercontent.com/29582865/200675743-129e3902-74cc-4ad1-a4c3-fde4182ca0cf.png)

**Describe the solution you'd like**

I believe that, for consistency I should be able to disable it from the configuration file or from the  Frigate UI as well.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by felipecrs** [comment]
Perhaps this is one of those issues that should be kept open?

**Comment by my-umd** [comment]
I actually feel it's better NOT allowing the toggle from the UI, because it's so easy to accidentally turn things off.  And may end up spending lot of time to figure out what's going on.  Putting the control in the configure file is sufficient and much simpler - there is only one place to control things.

**Comment by felipecrs** [comment]
I agree, but I think it should be made optional. :)

**Comment by NickM-27** [comment]
> I actually feel it's better NOT allowing the toggle from the UI, because it's so easy to accidentally turn things off. And may end up spending lot of time to figure out what's going on. Putting the control in the configure file is sufficient and much simpler - there is only one place to control things.

that doesn't really jive with the rest of the config options which are already controllable in multiple places. Your point would be covered by a different issue which is pinned to allow making those toggles admin only.

**Comment by jangrewe** [comment]
I second that it should at least be possible to configure the motion detection state from the config file, as restarting Frigate otherwise always triggers an alert for me. As it's possible to disable object detection in the config, and toggle both of them via MQTT, it would indeed be more consistent to allow this in the config.

Having the toggle in the UI is a nice-to-have for me, but not being able to do this via the config is a bit frustrating, as i always have to toggle it via MQTT when Frigate gets restarted. 😃

**Comment by aristosv** [comment]
So there is no way to do that? It seems I can turn everything off from the frigate configuration, except that.

<img width="776" height="597" alt="Image" src="https://github.com/user-attachments/assets/ec624ad8-ebd9-4c59-93c9-f89c6a2f79fb" />

**Comment by NickM-27** [comment]
You can turn off motion detection using MQTT

**Comment by felipecrs** [comment]
@NickM-27, is there a reason not to allow it to be configured through YAML or is this just a matter of _hasn't been done yet_?

**Comment by NickM-27** [comment]
it has been configurable in yaml for quite some time

**Comment by jangrewe** [comment]
@felipecrs It can be configured in the YAML! `detect:` and `motion:` -> https://docs.frigate.video/configuration/reference/

**Comment by felipecrs** [comment]
Lol, sorry.

So, @aristosv what do [you mean](https://github.com/blakeblackshear/frigate/issues/4326#issuecomment-3406315869)?

**Comment by aristosv** [comment]
I don't see a way to turn the "state" OFF, using the frigate configuration file. These two option **do not** turn the "state" OFF.

```
detect:
  enabled: false

motion:
  enabled: false
```

**Comment by jangrewe** [comment]
Works for me... 🤷‍♂️

**Comment by aristosv** [comment]
To clarify, "motion: OFF" and "state: OFF" are two different things. You were able to turn them both off from the frigate configuration file? Can you paste an example here?
