### ISSUE TITLE
[Support]: Frigate or Frigate Full access ? Not sure what to choose.

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#4348]
### Describe the problem you are having

This version of the add-on requests full device access in order to turn off protection mode for those devices which don't work with protection mode enabled.

What is the difference between Frigate NVR and Frigate NVR full access? I don't understand the above explanation (from the repo). When do i use one or the other ? Currently running HA in VMware.

### Version

na

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

dahua

**Comment by NickM-27** [comment]
The general process would be use the default one first, if it has trouble seeing your coral then you should use the full access with protection mode disabled.

**Comment by NickM-27** [comment]
The only difference is that full access has more access to your system so it can see devices like the coral and integrated GPU for video decoding

**Comment by atv2016** [comment]
Nice, I’ll try the default one first as per your suggestion.
________________________________

**Comment by crazyfrog-github** [comment]
Hi, I am going round in circles need someone help with issue that Coral TPU not being available to HAOS Supervised from Frigate in docker. However Coral TPU is being passed through to Frigate in docker locally but not remotely to HAOS:

Setup:
- HP Elitebook 800 G4 Mini i7 8700T processor with 16gb ram and 512GB M2 storage.
- Google Coral TPU Usb
- Proxmox 7.2 bare metal on HP Elitebook (Node 100) - IP 192.168.0.1
- Promox VM (101) - IP 192.168.0.2 + Home Assistant OS (Supervised) Proxmox Version qcow2 + Mosquitto mqtt broker + Frigate (Full Access) connected to IP 192.168.0.3:5000
- LCX container - IP 192.168.0.3 ("unprivileged container" unchecked, to make it privileged, with nesting) + Docker install with Portainer Stack install of Frigate (with Coral TPU passthrough working okay if accessed locally 192.168.0.3:5000)

When I access Frigate directly 192.168.0.3:5000 that is the Coral TPU USB passthrough from the Node to Frigate Docker, it works fine.

[2022-11-12 10:46:40] detector.coral                 INFO    : Starting detection process: 217
[2022-11-12 10:46:40] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-11-12 10:46:42] frigate.edgetpu                INFO    : TPU found


The issue arises when I set Home Assistant frigate.yml to use TPU instead of CPU it cannot find the Coral USB despite the LXC container being "privileged" Frigate container.

[2022-11-12 23:53:56] detector.coral                 INFO    : Starting detection process: 216
Process detector:coral:
[2022-11-12 23:53:56] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-11-12 23:53:56] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

Is it that the LXC Frigate Container has access to the TPU and will not share it with the HAOS supervised Frigate (Full Access) at the same time? I am completely lost.

I want to use Home Assistant UI with Frigate at is works and recordings and clips playback in H265 as Frigate docker direct 192.168.0.3:5000 only plays back h264 which I do not want.

**Comment by NickM-27** [comment]
> Is it that the LXC Frigate Container has access to the TPU and will not share it with the HAOS supervised Frigate (Full Access) at the same time? I am completely lost.

Yes, only one process is allowed access to the coral at any time

**Comment by NickM-27** [comment]
> I want to use Home Assistant UI with Frigate at is works and recordings and clips playback in H265 as Frigate docker direct 192.168.0.3:5000 only plays back h264 which I do not want.

This entirely depends on the browser used, h.265 playback is not affected by where frigate is installed in nay way

**Comment by crazyfrog-github** [comment]
> 

Hi,

Thanks, so what do I do with the following config files:

1. Proxmox Node: (100) /etc/pve/lxc/101.config file that contains the passthrough info (I assume leave it alone to make it available to the Frigate docker container)
2. LXC docker container (101): /home/frigate/config.yml - that contains MQTT IP and login and detector and camera info (Is this file needed at all as Frigate (Full Access) is installed on HAOS Supervised in the Proxmox VM and contains all the MQTT, detector and camera info or is there something that is needed in this config.yml in the Frigate docker container?
3. On HAOS supervised VM: frigate.yml file is this where I leave detector to use the TPU?

**Comment by crazyfrog-github** [comment]
> > Is it that the LXC Frigate Container has access to the TPU and will not share it with the HAOS supervised Frigate (Full Access) at the same time? I am completely lost.
> 
> Yes, only one process is allowed access to the coral at any time

Hi,

Thanks, so what do I do with the following config files:

Proxmox Node: (100) /etc/pve/lxc/101.config file that contains the passthrough info (I assume leave it alone to make it available to the Frigate docker container)
LXC docker container (101): /home/frigate/config.yml - that contains MQTT IP and login and detector and camera info (Is this file needed at all as Frigate (Full Access) is installed on HAOS Supervised in the Proxmox VM and in frigate.yml contains all the MQTT, detector and camera info or is there something that is needed in this /home/frigate/config.yml in the Frigate docker container to make things work?
On HAOS supervised VM: frigate.yml file is this where I leave detector to use the TPU as Detector has been removed from LXC docker container (101): /home/frigate/config.yml

**Comment by crazyfrog-github** [comment]
> > I want to use Home Assistant UI with Frigate at is works and recordings and clips playback in H265 as Frigate docker direct 192.168.0.3:5000 only plays back h264 which I do not want.
> 
> This entirely depends on the browser used, h.265 playback is not affected by where frigate is installed in any way

Hi,

When I use Frigate Proxy AddOn with Frigate Docker Container the Coral TPU does get passed to the VM HAOS Supervised fine but when I play a recorded clip in any browser on different devices I get "Playback cannot continue. No available working or supported playlists." and spinning circle. You acknowledged this issue in another post h265 being the issue:

https://github.com/blakeblackshear/frigate/issues/3054#issuecomment-1088168407

When I use Frigate AddOn and not Frigate Proxy AddOn the recorded clip in any browser on different device works. 

![image](https://user-images.githubusercontent.com/33864965/201480422-7ca75844-2803-4330-8f18-6301eea68e3a.png)

**Comment by NickM-27** [comment]
> When I use Frigate Proxy AddOn with Frigate Docker Container the Coral TPU does get passed to the VM HAOS Supervised fine

I think you're misunderstanding. The frigate proxy Add On does nothing other than proxy the web ui, it does not proxy the coral or run anything else at all.

If h.265 doesn't work with the proxy then the proxy may need an update as I imagine it uses nginx and maybe isn't catching that case.

**Comment by crazyfrog-github** [comment]
> I think you're misunderstanding. The frigate proxy Add On does nothing other than proxy the web ui, it does not proxy the coral or run anything else at all.

Interesting, when I set detector to TPU on HomeAssistant frigate.yml in HAOS VM and Frigate docker container config.yml to CPU it shows Coral and inference connected which is coming from HAOS VM in frigate.yml config file as below image, so this does not make sense based on what you just said. 

![image](https://user-images.githubusercontent.com/33864965/201481002-f1656d08-b67c-44b9-b243-57320c8c0052.png)

**Comment by NickM-27** [comment]
You're crossing a lot of threads here. 

The frigate proxy addon does not even read the frigate.yml file which you can see: https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate_proxy/config.yaml#L25

Meanwhile the actual frigate addon does read the config file https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate/config.yaml#L39

So you're either doing way too much at the same time which is confusing things, or you're not using the correct terms when describing what you're running.

**Comment by crazyfrog-github** [comment]
> So you're either doing way too much at the same time which is confusing things, or you're not using the correct terms when describing what you're running.

I really want to get this to work please confirm what you are saying is do NOT create a frigate.yml in HAOS Supervised in the at all and put all the config into LXC Frigate Docker container in /home/frigate/config.yml and just install the Frigate Proxy only no HACS integration and everything will just show up in the sidebar in HAOS supervised?

**Comment by NickM-27** [comment]
That's not what I'm saying. You mentioned frigate proxy addon but then based on what you're saying that's not actually what you're running.

If you want advice then I'd need to know your goals and why you're trying to move away from the docker in proxmox install.

**Comment by crazyfrog-github** [comment]
> That's not what I'm saying. You mentioned frigate proxy addon but then based on what you're saying that's not actually what you're running.
> 
> If you want advice then I'd need to know your goals and why you're trying to move away from the docker in proxmox install.

Okay, my goal is to use Frigate UI from the sidebar in HAOS Supervised UI and Frigate to use the Coral TPU that is passed through from the Proxmox Host to the LXC Docker Frigate Container.

**Comment by NickM-27** [comment]
> Okay, my goal is to use Frigate UI from the sidebar in HAOS Supervised UI and Frigate to use the Coral TPU that is passed through from the Proxmox Host to the LXC Docker Frigate Container.

Okay then yes you'd want to use the frigate proxy addon and not create a frigate.yml in supervised ha. You WILL still want to have the frigate integration installed

**Comment by crazyfrog-github** [comment]
> Okay then yes you'd want to use the frigate proxy addon and not create a frigate.yml in supervised ha. You WILL still want to have the frigate integration installed

Thanks I will try tomorrow, strip all from HAOS config files, config Frigate LXC container, install frigate proxy addon and frigate integration installed. See how things go.

**Comment by NickM-27** [comment]
If you have any issues with that I recommend creating a new issue, going to close this as it is unrelated

**Comment by crazyfrog-github** [comment]
> If you have any issues with that I recommend creating a new issue, going to close this as it is unrelated

Hi, even though it is 2am I have tried what you suggest and all on the Frigate Docker Side and it works. The only thing that does not work is the playback of event clips I have logged a ticket about that.

Thanks
