### ISSUE TITLE
Video stream (MSE) in Birdseye View maximized

### ISSUE THREAD

**Issue by banthungprong** [blakeblackshear/frigate#4934]
The MSE player in Birseye.jsc ist limited to "max-w-5xl". On a 4k Monitor this results in a player size with 1920 px.

Changing this value to "max-w-full" in line 34 for MSE Player will use 100% of usable size (I tested this in the Developer Tools in Chrome and it worked).

Line 43 (WebRtcPlayer) could use the same value.

**Comment by NickM-27** [comment]
There's no reason for the video player to be maximized, there is a full screen button for that on the player. This change was done on purpose.

**Comment by NickM-27** [comment]
This was done on purpose, if you check the source code you'll notice that the jsmpeg player was also set to have a max size until it is clicked to full screen. If you want full screen then you should use the full screen button. 

This change was done because if you are not in full screen then the player should be smaller. Before when the player was full size I could not even get to the full screen button without scrolling. Right now the birdseye screen is only the stream but in the future there will likely be other buttons, controls, etc. there which will take up that space as well.

![Screenshot 2023-01-06 at 7 31 40 AM](https://user-images.githubusercontent.com/14866235/211033102-7f1ff615-4864-4288-a442-7d97d1d79fbb.png)

**Comment by banthungprong** [comment]
Ok. Scrolling is ugly. I just tried other options. Always with a scroll bar. I understand now. Thanks for the explanation.

**Comment by NickM-27** [comment]
as an example, to the above, could add PTZ controls to all cameras in birdseye view 👍
