### ISSUE TITLE
[Feature Request]: Camera Groups

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5510]
**Describe what you are trying to accomplish and why in non technical terms**

I have a _lot_ of cameras (30+), covering multiple areas both indoor and out. The web interface gets really clunky finding the correct camera for any reason. I would like to be able to associate cameras to group, similar to zones, but broader. For example "Outdoors", "Main Floor", and "Basement" zones. Then on the Cameras page, there would be a dropdown to filter to certain groups. On Birdseye, I could get a view of active cameras only within the selected group. On Events page, it would be an additional dropdown, or possibly built into the Cameras dropdown which will pre-select all relevant cameras when clicked.

**Describe alternatives you've considered**

I've noticed at least on the Events page, the URL changes as I select a single camera, and then additional cameras. I've considered bookmarking the full URL with all the cameras I want, but that's not discoverable/scalable when sharing access to Frigate with others.

**Comment by craigmcgowan** [comment]
This would be of interest to me too. I have all my home cameras in Frigate but am starting to include the cameras from my work too. However, this would trigger hundreds of events a day so Ideally I'd love to add cameras into groups (home/work).

Any suggestions for workarounds as it stands?

Thank you

**Comment by ccutrer** [comment]
I'm curious... are your home and work at the same physical location? If not, is the network connection between the two locations fast enough to handle multiple camera streams, and at low latency? Seems like an unusual use case to use a single Frigate instance for two only tangentially related locations. But if the network connection is reliable and fast enough, it could definitely save you costs on hardware. And makes more sense for multiple locations of the same business, all with reliable and fast connections.

**Comment by craigmcgowan** [comment]
Hi Cory

No, they are different locations.

I have a warehouse which has around 30 cameras on site. I don't current intend for Frigate to do anything with these cameras (so no detects or events) but purely just restream then for me. If there is an option that the events page can "group" cameras together than I will add detection on the exterior cameras only 

I'll then just have a page on Home Assistant (which I spend half of my working day on anyway) to view my work cameras at a glance. Or in the middle of the night when the Remote Monitored Alarm company call to say their is an intruder alarm going off!

Im not sure yet how the connection and latency will be when I add in more cameras because at present I've only added one of the cameras on.

**Comment by YBonline** [comment]
> I'm curious... are your home and work at the same physical location? If not, is the network connection between the two locations fast enough to handle multiple camera streams, and at low latency? Seems like an unusual use case to use a single Frigate instance for two only tangentially related locations. But if the network connection is reliable and fast enough, it could definitely save you costs on hardware. And makes more sense for multiple locations of the same business, all with reliable and fast connections.

I have cameras from 7 locations in my Frigate install without issue, including some locations off site with over 14 cameras with no issue. My area has all been upgraded to fiber after a hurricane blew away all the old lines, but it is all residential fiber (GPON), and it doesn't skip a heartbeat streaming 30 cameras from off site.
