### ISSUE TITLE
Debug View Improvement and Birdeyes objects mode sensitivity

### ISSUE THREAD

**Issue by LckySndays** [blakeblackshear/frigate#5600]
When the camera birdeyes mode set to objects to track person , I occasionally get my birdeyes view triggered by something (possibly false positive), the camera event view show me nothing.

After I keep staring at camera debug view for minutes, I found out that sometimes object being detected flashing so quickly and then disappeared and it is enough to trigger the birdeyes view but not registering the event to the camera event. Is there any way to see what thing cause it to trigger the birdeyes view? or Is there is a way to set the birdeyes view to only trigger the event that is registered to camera event?

The debug view resolution and fps is capped and kinda low, most of the time I know that there are object being detected but I don't know what it is because the bounding box so small, blurry and the text is unreadable ( might be because high resolution camera image ) especially when it is flashing so quickly for just a second. It is so hard to adjust the configuration without knowing the cause of issue.

If there is a logs view inside the camera debug view with lot of useful information dumped/printed there such as what object being detected with what confidence at which coordinate and for how long it stay there with timestamp, it will greatly improve the debugging experience.

**Comment by NickM-27** [comment]
> When the camera birdeyes mode set to objects to track person , I occasionally get my birdeyes view triggered by something (possibly false positive), the camera event view show me nothing.
>
> After I keep staring at camera debug view for minutes, I found out that sometimes object being detected flashing so quickly and then disappeared and it is enough to trigger the birdeyes view but not registering the event to the camera event. Is there any way to see what thing cause it to trigger the birdeyes view? or Is there is a way to set the birdeyes view to only trigger the event that is registered to camera event?

Birdseye object mode will show as soon as an object is detected even when it is not yet considered a true positive. This is to ensure quicker response so there is no delay in showing the camera view for a possible object. The events view requires the object to be considered a true positive before the event will be saved. This behavior is currently not cusotmizable.

> The debug view resolution and fps is capped and kinda low, most of the time I know that there are object being detected but I don't know what it is because the bounding box so small, blurry and the text is unreadable ( might be because high resolution camera image ) especially when it is flashing so quickly for just a second. It is so hard to adjust the configuration without knowing the cause of issue.
>
> If there is a logs view inside the camera debug view with lot of useful information dumped/printed there such as what object being detected with what confidence at which coordinate and for how long it stay there with timestamp, it will greatly improve the debugging experience.

The debug resolution comes directly from your configs debug resolution. The fps is capped because it is a lot of work generating the debug view and making the fps higher would put a lot of load on the system which could slow down the actual detections (AFAIK). In a future version we are looking at a frame level replay of events after the fact by saving the event related metadata.
