### ISSUE TITLE
Feature Request - Output movie clips of detected objects for notifications

### ISSUE THREAD

**Issue by steveneighbour** [blakeblackshear/frigate#57]
Noticed this is a planned feature in the readme, so figured i'd open an issue for it.

Having video clips compiled when objects are detected would be a great feature.  [Motion](https://motion-project.github.io/) handles this really well, using a [pre](https://htmlpreview.github.io/?https://raw.githubusercontent.com/Motion-Project/motion/master/motion_config.html#pre_capture) and post number of frames captured that are then stitched into a movie file. 

I believe you already store 2 seconds (?) of frames for object analysis, so it would be a matter of using those 2 seconds + all frames captured while the moving object is present + a configurable number of seconds/frames after the object is no longer present/moving.

This video could be dumped to disk and/or sent to HA.

**Comment by steveneighbour** [comment]
renamed issue as detection is no longer people specific.

I've had a go at getting video being created after objects are detected but don't have the skills to get it to work reliably.

**Comment by steveneighbour** [comment]
This is working for me now, with Frigate doing object detection + sending an eventstart/eventend API call to my [motion ](https://github.com/Motion-Project/motion/)container via edits to the [mqtt.py](https://github.com/steveneighbour/frigate/blob/master/frigate/mqtt.py) file.  Motion generates the video recording.

```
Object Detected | Type:car | Confidence:97% | Area: 3783 | Camera:front
124658 - Start Recording Request sent to: front
124708 - End Recording Request successfully sent to: front
```

The end result of this is a video recording of each object detection, with a 3 second pre-record time + using the high res camera stream for the recording.

Not suggesting this is the way to do it, as it requires a 2nd application to be running.. I also am certain the way i've done it is a hack of horrific proportions!

**Comment by valantur** [comment]
I'm just here to say this would be amazing!

**Comment by scstraus** [comment]
I have it sending a message to my synology to trigger recording there. And then I can filter recordings only by ones with humans detected or add in the motion detected ones for more context. My config is up here if anyone wants to replicate that.

https://github.com/scstraus/home-assistant-config#tell-my-synology-security-station-to-start-recording-if-a-human-is-detected

**Comment by Buzztiger** [comment]
I have a similar setup using Blue Iris as a recording backend. Blue Iris can trigger of mqtt messages.

**Comment by blakeblackshear** [comment]
Just finished an initial version of this feature. See[ updated example config](https://github.com/blakeblackshear/frigate/blob/save_clips/config/config.example.yml#L113-L128) for details.

You can pull the image at `blakeblackshear/frigate:save_clips-47cd69b`

**Comment by bm55** [comment]
I have been testing 0.6.0-rc1 for few days and the clips were working but now I am getting following error and the clips folder is empty. Only change I have done is I am now using RTMP instead of RTSP stream. 

`2020-09-06T15:09:05.368128189Z Camera_process started for back: 59
2020-09-06T15:09:05.370036084Z Starting process for back: 59
2020-09-06T15:09:05.371467202Z Camera_process started for garage: 60
2020-09-06T15:09:05.373026406Z Starting process for garage: 60
2020-09-06T15:09:05.386434771Z  * Serving Flask app "detect_objects" (lazy loading)
2020-09-06T15:09:05.386627711Z  * Environment: production
2020-09-06T15:09:05.386856087Z    WARNING: This is a development server. Do not use it in a production deployment.
2020-09-06T15:09:05.387020939Z    Use a production WSGI server instead.
2020-09-06T15:09:05.387228613Z  * Debug mode: off
2020-09-06T15:22:39.070697358Z Exception in thread Thread-5:
2020-09-06T15:22:39.070744579Z Traceback (most recent call last):
2020-09-06T15:22:39.070754739Z   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
2020-09-06T15:22:39.070763713Z     self.run()
2020-09-06T15:22:39.070771168Z   File "/opt/frigate/frigate/events.py", line 155, in run
2020-09-06T15:22:39.070778847Z     self.create_clip(camera, event_data, self.config[camera].get('save_clips', {}).get('pre_capture', 30))
2020-09-06T15:22:39.070786653Z   File "/opt/frigate/frigate/events.py", line 86, in create_clip
2020-09-06T15:22:39.070794082Z     while sorted_clips[-1]['start_time'] + sorted_clips[-1]['duration'] < event_data['end_time']:
2020-09-06T15:22:39.070802228Z IndexError: list index out of range
2020-09-06T15:22:39.070809691Z 
`

**Comment by blakeblackshear** [comment]
Check the format of your RTMP stream. In order to avoid re-encoding, frigate needs the video feed to be compatible with the mp4 container to work.

**Comment by bm55** [comment]
It is mp4
<img width="524" alt="Screen Shot 2020-09-06 at 9 59 19 PM" src="https://user-images.githubusercontent.com/7528001/92330280-5ed08400-f08d-11ea-8734-d35ceb723e68.png">

ffprobe recorded segment shows:
[h264 @ 0x56439a9ac9c0] Reinit context to 896x672, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'back-20200906091712.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:10.35, start: 0.000000, bitrate: 1214 kb/s
    Stream #0:0(und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 896x672, 1211 kb/s, 24.15 fps, 30 tbr, 10240 tbn, 20480 tbc (default)
