### ISSUE TITLE
Get "go2rtc dashboard" button working for hass

### ISSUE THREAD

**Issue by Mr-HaleYa** [blakeblackshear/frigate#5929]
When using Frigate as an addon in hassOS you can show it in the sidebar. When using the sidebar UI your URL will be something like `http://HASSIP:8123/hassio/ingress/ccab4aaf_frigate-beta`. If you go to the system page and click the "go2rtc dashboard" button it will take you to `http://HASSIP:8123/live/webrtc/` which will show `404: Not Found`. 
https://github.com/blakeblackshear/frigate/blob/34bdf2fc105bd0a249bc9f1dfa7e0ffe1be4abaf/web/src/routes/System.jsx#L97

This button does work when using frigate through the API port 5000 but that port is disabled by default and says `(Not required for Hass.io Ingress)` so unless enabled there's no way to use the button and when using the sidebar to nav to the UI you won't get to `http://HASSIP:5000/hassio/ingress/ccab4aaf_frigate-beta`.

This should probably be fixed so that when using the UI from the sidebar and when using from the API port the button works.

Also wondering why the button goes to that URL and not `http://HASSIP:1984/` 
I'm assuming that the port can not be changed when naving with an href, I've done it before with JS on click but don't know if that would work here.

**Comment by NickM-27** [comment]
It can't be fixed, at least not with the current implementation. The proxy doesn't support paths like that. 

This is also covered by the existing issue https://github.com/blakeblackshear/frigate-hass-addons/issues/87 on the other repo

Also, 1984 doesn't work since the port is not enabled by default for security reasons.

**Comment by NickM-27** [comment]
It would work just fine in HASS if you open port 5000 and access it with the ip address

**Comment by javigmsuperka** [comment]
Hello,

When i try to acces from frigate proxy addon My go2rtc dashboard link shows http://192.168.2.106:8123/live/webrtc/ (HA IP) instead of docker ip http://192.168.2.100:5000/live/webrtc/

If I directly access the frigate with the docker IP, then everything works fine.

From frigate proxy addon:

![image](https://github.com/blakeblackshear/frigate/assets/85594685/47aba367-d494-474c-8832-876a9fc8dcb1)


From Frigate Docker:

![image](https://github.com/blakeblackshear/frigate/assets/85594685/ed748204-efac-48bd-8dad-79c756c71706)
