### ISSUE TITLE
Database locked error

### ISSUE THREAD

**Issue by joshs85** [blakeblackshear/frigate#593]
**Describe the bug**
Getting an error saying the db is locked.  I think its because my clips directory is on a cifs share mapped by docker.  <path_to_directory_for_clips>:/media/frigate/clips

Can you add a config pram to specify a different location for the db file?  I can't seem to do it with docker because the folder is already mapped to the network drive.  When I do it from docker for that specific file, it still writes to the network location.

**Version of frigate**
What version are you using?

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Logs**
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating tmpfs of size 1024m
Starting migrations
peewee_migrate                 INFO    : Starting migrations
database is locked
```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by joshs85** [comment]
I actually found that this can be configured from looking at the config.py.  I tried it out and it fixed the issue.

**Comment by biggen1684** [comment]
I'm having the same problem. I was just getting ready to open up a issue here.

**Comment by joshs85** [comment]
This is what I added to fix mine.

database:
  path: /config/frigate.db

**Comment by biggen1684** [comment]
> This is what I added to fix mine.
> Make sure to indent path.
> `database:`
> ` path: /config/frigate.db`

Where is that being added to?

**Comment by joshs85** [comment]
The frigate config.yml file.  Right at the root so it doesn't go under anything.

**Comment by biggen1684** [comment]
Ok.  I just upgraded to his new RC5 that dropped and I'll see how that goes.  I've been running Frigate for months and not had that issue so I'm not sure where it came from.  Perhaps it was a fluke.

**Comment by blakeblackshear** [comment]
Reopen if this issue comes back up

**Comment by rickgitdone** [comment]
I have read through all the docs on how to adjust the location of the database after I also was stuck with database locked error after my initial install... None of the docs nor YouTube videos give any hints why the database error locked pops up... only these threads demonstrate the proper issue.

It would truly help everyone out there who wants to use the docker containers and have the external media separated from the database location because its "required" when mapping /media to a mounted file system. I assume this is a SQLite requirement that isn't documented in the Frigate Docs either... The default configuration should just show local db mapping which I tried several ways with total failure until I gave up removed "ro" from the config.yml mapping and placed the database in the same directory which also works .. was that wrong?

Simply letting everyone know the SQLite database "must" be mapped locally similar to the config.yml mapping but writeable and providing good examples would save hours of questioning what went wrong...
