### ISSUE TITLE
Still need generic cam?  Onvif?  Can go2rtc create entities?  Need go2rtc integration?  Webrtc integration?

### ISSUE THREAD

**Issue by mannyp26** [blakeblackshear/frigate#6089]
### Describe the problem you are having

One of my cameras shows a black screen with a message saying "No frames have been recieved, check error logs."  Since the most recent update its always the same camera but for a time it was usually two of them and it wasn't always the same two.  Also go2rtc dashboard always gives error 404 with black webpage.  

Also using the regular rtsp stream url in frigate.yml config along with the same regular rtsp stream url in the go2rtc portion of the config.  This results in the camera showing in the Frigate UI but then 2 of the other 4 cameras show the black screen

### Version

0.12.0-bc16ad1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate-fa-beta/api/config/schema

mqtt:
  host: localhost
  user: mqtt-user
  password: pass

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

snapshots:
  enabled: True
  timestamp: True      
  retain:
    default: 10

    

go2rtc:
  streams:
    driveway1:
      - rtsp://user:pass@192.168.x.x:8554/media/video1
    driveway2:
      - rtsp://user:pass@192.168.x.xx:8554/media/video2
    garage1:
      - rtsp://user:pass@192.168.x.xx:8554/CH001.sdp
    garage2:
      - rtsp://user:pass@192.168.x.xx:8554/CH002.sdp
    front_door1:
      - rtsp://user:pass@192.168.x.xx:8554/CH002.sdp
    front_door2:
      - rtsp://user:pass@192.168.x.xx:8554/CH002.sdp
    backyard2:
      - rtsp://user:pass@192.168.x.xx:8554/stream1

  
  
    # nest_cam: 
      # - rtsps://long-ass link
    # hunter_room_cam:
      # - rtsp://user:pass@192.168.x.xx:8554/live

cameras:
  front_door2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/front_door2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
    objects: 
      track:
      - person
      - car
      - dog
  driveway2:
    ffmpeg:
      inputs:
        - path: rtsp:localhost:8554/driveway2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
  garage2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/garage2
          input_args: preset-rtsp-restream
          roles:
            - detect 
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 5   
    objects:
      track:
        - person
        - car
        - dog
  backyard2:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/backyard2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: True
      width: 720
      height: 480
      fps: 5
    motion:
      mask:
        - 636,227,673,50,572,34,559,139
    objects:
      track:
        - person
        - dog
  # nest_cam: 
    # ffmpeg:
      # inputs:
        # - path: rtsp://user:pass@localhost:8554/nest_cam
          # roles:
            # - detect
```

### Relevant log output

```shell
2023-04-15 07:14:49.581445242  [2023-04-15 00:14:49] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-04-15 07:14:52.380663021  [2023-04-15 00:14:52] frigate.comms.mqtt             ERROR   : Unable to publish to front_door2/all: client is not connected
2023-04-15 07:14:53.617860384  [2023-04-15 00:14:53] frigate.video                  ERROR   : backyard2: Unable to read frames from ffmpeg process.
2023-04-15 07:14:53.618781364  [2023-04-15 00:14:53] frigate.video                  ERROR   : backyard2: ffmpeg process is not running. exiting capture thread...
2023-04-15 07:14:54.847446814  [2023-04-15 00:14:54] frigate.comms.mqtt             ERROR   : Unable to publish to driveway2/all: client is not connected
2023-04-15 07:15:06.985130985  [2023-04-15 00:15:06] watchdog.garage2               INFO    : No frames received from garage2 in 20 seconds. Exiting ffmpeg...
2023-04-15 07:15:06.986664618  [2023-04-15 00:15:06] watchdog.garage2               INFO    : Waiting for ffmpeg to exit gracefully...
2023-04-15 07:15:07.018804873  [2023-04-15 00:15:06] watchdog.backyard2             ERROR   : Ffmpeg process crashed unexpectedly for backyard2.
2023-04-15 07:15:07.020143770  [2023-04-15 00:15:06] watchdog.backyard2             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-15 07:15:07.021573036  [2023-04-15 00:15:06] ffmpeg.backyard2.detect        ERROR   : [rtsp @ 0x55a98e30c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-04-15 07:15:07.022752140  [2023-04-15 00:15:06] ffmpeg.backyard2.detect        ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
2023-04-15 07:15:07.024113611  [2023-04-15 00:15:06] ffmpeg.backyard2.detect        ERROR   : Output file #0 does not contain any stream
2023-04-15 07:15:07.481371596  [2023-04-15 00:15:07] frigate.video                  ERROR   : garage2: Unable to read frames from ffmpeg process.
2023-04-15 07:15:07.481387448  [2023-04-15 00:15:07] frigate.video                  ERROR   : garage2: ffmpeg process is not running. exiting capture thread...
2023-04-15 07:15:12.716168514  [2023-04-15 00:15:12] frigate.video                  ERROR   : backyard2: Unable to read frames from ffmpeg process.
2023-04-15 07:15:12.728335606  [2023-04-15 00:15:12] frigate.video                  ERROR   : backyard2: ffmpeg process is not running. exiting capture thread...
2023-04-15 07:15:17.049444448  [2023-04-15 00:15:17] watchdog.backyard2             ERROR   : Ffmpeg process crashed unexpectedly for backyard2.
2023-04-15 07:15:17.051091506  [2023-04-15 00:15:17] watchdog.backyard2             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-15 07:15:17.051420610  [2023-04-15 00:15:17] ffmpeg.backyard2.detect        ERROR   : [rtsp @ 0x55a264f0c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-04-15 07:15:17.053166814  [2023-04-15 00:15:17] ffmpeg.backyard2.detect        ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
2023-04-15 07:15:17.054454990  [2023-04-15 00:15:17] ffmpeg.backyard2.detect        ERROR   : Output file #0 does not contain any stream
2023-04-15 07:15:17.487130384  [2023-04-15 00:15:17] watchdog.garage2               ERROR   : Ffmpeg process crashed unexpectedly for garage2.
2023-04-15 07:15:17.489582240  [2023-04-15 00:15:17] watchdog.garage2               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-15 07:15:17.491200705  [2023-04-15 00:15:17] ffmpeg.garage2.detect          ERROR   : [h264_v4l2m2m @ 0x559ae929e0] capture VIDIOC_REQBUFS failed: Cannot allocate memory
2023-04-15 07:15:17.491216779  [2023-04-15 00:15:17] ffmpeg.garage2.detect          ERROR   : [h264_v4l2m2m @ 0x559ae929e0] can't request capture buffers
2023-04-15 07:15:17.492495270  [2023-04-15 00:15:17] ffmpeg.garage2.detect          ERROR   : [h264_v4l2m2m @ 0x559ae929e0] capture set status 1074026002 (ON) failed: err=22
```

### Frigate stats

```json
coral
P-ID	Inference Speed	CPU %	Memory %
302	16.17 ms	5.3%	2.6%

{"return_code":1,"stderr":"error:XDG_RUNTIME_DIRnotsetintheenvironment.nerror:can'tconnecttoXserver!nerror:failedtoinitializedisplay","stdout":""}

Front Door2
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	321	5	4.3%	0.8%
Capture	313	5	2.7%	2.2%
Detect	307	0 (0 skipped)	1.3%	2.4%
Driveway2
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	331	5.1	25.2%	1.3%
Capture	314	5.1	12.3%	2.4%
Detect	308	0 (0 skipped)	2.0%	3.4%
Garage2
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	399	5.1	4.0%	0.9%
Capture	315	5.1	2.0%	2.3%
Detect	309	3.7 (0 skipped)	7.3%	2.5%
Backyard2
FFPROBE
Process	P-ID	FPS	CPU %	Memory %
ffmpeg	5956	-	0.3%	1.2%
Capture	322	-	0.0%	2.3%
Detect	311	0 (0 skipped)	0.0%	2.2%

FFPORBE IS SAME FOR ALL
[{"return_code":1,"stderr":"","stdout":""}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Nabu Casa Subscription
I have a Geovision SNVR but I can't utilize all of its features in HA so I first used the generic camera and onvif integrations to import my feeds into HA.  Then I incorporated other cameras and the RTSP simple server add on and RTSPtoWebrtc and all that.  So there are a lot of parts here which was only brought to another level when I decided to use Frigate for Live feeds, snapshots, notifications and automations while allowing the SNVR to do the recording.  Well on my journey I've never had it running smoothly but I assume it has to do with my setup and it seems like I can simplify somewhere here since Frigate is like a Swiss Army Knife and does so much.  Im currently running a Pi4- Hassos- Frigate 0.12 CR 2- Frigate v5.0 integration- Coral TPU usb setup.  I've never removed my cameras from those other integrations but now I wonder if I should now that Frigate is bundled with go2rtc.  

If I were to start from scratch with my cameras, I also have a Eufy 2k Doorbell cam, 2 wyze cams, 1 Nest Cam, and an Iota Cam, would you suggest I use Frigate to restream everything into HA?  Then use the Frigate Integration?  Is there a way for it to create entities in Home Assistant?  All of my cameras with the exception of my Nest Cam have local storage so I don't pay for video storage.  I also really try to get everything working with Homekit as much as possible because my family is able to use it easily with Siri.  Or do I just not get it yet?  I started all of this 3 years ago after getting an Ecobee thermostat and realizing what home automation could do, I wanted it all in one place locally as much as possible.  But I had no prior experience with any of this.  So me sounding like a dumbass wouldn't surprise me and I'm fine if you let me know that.  MQTT still gives me issues and that should be easy.

Thanks for everything you guys have done

**Comment by blakeblackshear** [comment]
Sounds like you may be running out of gpu memory on the Pi. Previous versions would have just shown a frozen frame rather than an error message.

You can try applying hwaccel args at the camera level and running some of them on the CPU if necessary.

**Comment by caublet** [comment]
Not sure it's the video.. I' trying to upgrade to 0.12.0-DA3E197. I'vve launched a 2nd Frigate Docker container as v0.12 on the same Portainer host on another port and I've switched my config to use go2rtc. 

I get 2 of my 4 cameras working. For the 2 other other ones,  I get the same error message on non-standard resolution cameras : 
![image](https://user-images.githubusercontent.com/581162/233261984-76176b7d-4e6c-4293-bf4e-5a319f0af601.png)

I know I'm doing it right because I have 2 cams working.

Is there any options to fix this? Was working on v0.11

0.11 Config : 
`##################### CAMERAS ###################
  Ssolfenetre:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/Streaming/Channels/1
          roles:
            - rtmp
            - record
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/Streaming/Channels/2
          roles:
            - detect
    detect:
      fps: 6
      width: 480
      height: 360
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.35
          threshold: 0.5
        cat:
          min_score: 0.35
          threshold: 0.5
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - mia
          - fenetre
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
          - mia
          - fenetre
    zones:
      fenetre:
        coordinates: 346,14,328,183,446,211,464,52
        objects:
          - person
      mia:
        coordinates: 258,45,263,2,174,2,64,19,63,51
        objects:
          - cat
    motion:
      mask:
        - 20,313,255,313,255,336,20,336
################  MQTT #######################

mqtt:
  host: 192.168.1.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: BLANKED
  password: BLANKED
  stats_interval: 60
birdseye:
  enabled: True
  mode: continuous
  quality: 8

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
logger:
  default: info
  logs:
    frigate.event: info`

0.12 config
`go2rtc:
  streams:
    Ssolfenetre:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/Streaming/Channels/1
#      - "ffmpeg:Ssolfenetre#audio=aac"
    SsolfenetreSub:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/Streaming/Channels/2
#####      
  webrtc:
    candidates:
      - 192.168.1.15:8555
      - stun:8555
##################### CAMERAS ###################
cameras:
  Ssolfenetre:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/SsolFenetre
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/SsolfenetreSub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 6
      width: 480
      height: 360
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.35
          threshold: 0.5
        cat:
          min_score: 0.35
          threshold: 0.5
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 60
          mode: active_objects
        required_zones:
          - mia
          - fenetre
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 60
      required_zones:
          - mia
          - fenetre
    zones:
      fenetre:
        coordinates: 346,14,328,183,446,211,464,52
        objects:
          - person
      mia:
        coordinates: 258,45,263,2,174,2,64,19,63,51
        objects:
          - cat
    motion:
      mask:
        - 20,313,255,313,255,336,20,336
################  MQTT #######################

mqtt:
  host: 192.168.1.12
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: BLANKED
  password: BLANKED
  stats_interval: 60
birdseye:
  enabled: True
  mode: continuous
  quality: 8

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3

ffmpeg:
  hwaccel_args: preset-nvidia-h264
logger:
  default: info
  logs:
    frigate.event: info
`

Error message on 0.12 
`frigate4  | 2023-04-20 01:06:39.776534440  [2023-04-20 01:06:39] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate4  | 2023-04-20 01:06:39.805384322  [2023-04-20 01:06:39] peewee_migrate                 INFO    : Starting migrations
frigate4  | 2023-04-20 01:06:39.810990006  [2023-04-20 01:06:39] peewee_migrate                 INFO    : There is nothing to migrate
frigate4  | 2023-04-20 01:06:39.834366028  [2023-04-20 01:06:39] detector.cpu2                  INFO    : Starting detection process: 290
frigate4  | 2023-04-20 01:06:39.848015950  [2023-04-20 01:06:39] frigate.app                    INFO    : Output process started: 293
frigate4  | 2023-04-20 01:06:39.849095493  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.850678431  [2023-04-20 01:06:39] detector.cpu1                  INFO    : Starting detection process: 289
frigate4  | 2023-04-20 01:06:39.850683070  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.850686990  [2023-04-20 01:06:39] detector.cpu3                  INFO    : Starting detection process: 292
frigate4  | 2023-04-20 01:06:39.858521266  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.863559212  [2023-04-20 01:06:39] frigate.app                    INFO    : Camera processor started for Ssolfenetre: 297
frigate4  | 2023-04-20 01:06:39.863564222  [2023-04-20 01:06:39] frigate.app                    INFO    : Capture process started for Ssolfenetre: 298
frigate4  | 2023-04-20 01:06:41.619041210  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET /api/config HTTP/1.1" 200 6044 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.669249607  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET //api/Ssolfenetre/latest.jpg?h=460 HTTP/1.1" 200 13556 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.703735782  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET / HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.744340158  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET /api/config HTTP/1.1" 200 6044 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.802992365  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET //api/Ssolfenetre/latest.jpg?h=460 HTTP/1.1" 200 13556 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:44.958134956  01:06:44.957 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.22.0.2:49052->192.168.1.25:554: i/o timeout" url=rtsp://frigate:Contact12@192.168.1.25:554/Streaming/Channels/2
frigate4  | 2023-04-20 01:06:45.067325812  [2023-04-20 01:06:45] frigate.video                  ERROR   : Ssolfenetre: Unable to read frames from ffmpeg process.
frigate4  | 2023-04-20 01:06:45.067760014  [2023-04-20 01:06:45] frigate.video                  ERROR   : Ssolfenetre: ffmpeg process is not running. exiting capture thread...
frigate4  | 2023-04-20 01:06:48.645499653  [INFO] Starting go2rtc healthcheck service...
frigate4  | 2023-04-20 01:06:59.907722515  [2023-04-20 01:06:59] watchdog.Ssolfenetre           ERROR   : Ffmpeg process crashed unexpectedly for Ssolfenetre.
frigate4  | 2023-04-20 01:06:59.907736164  [2023-04-20 01:06:59] watchdog.Ssolfenetre           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate4  | 2023-04-20 01:06:59.908136569  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : [rtsp @ 0x56445f9d3d40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate4  | 2023-04-20 01:06:59.908140261  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate4  | 2023-04-20 01:06:59.908141961  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : Output file #0 does not contain any stream
frigate4  | 2023-04-20 01:06:59.919674974  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.record      ERROR   : [rtsp @ 0x56038c4c3e00] method DESCRIBE failed: 404 Not Found
frigate4  | 2023-04-20 01:06:59.919680653  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.record      ERROR   : rtsp://127.0.0.1:8554/SsolFenetre: Server returned 404 Not Found
frigate4  | 2023-04-20 01:06:59.919682426  [2023-04-20 01:06:59] watchdog.Ssolfenetre           INFO    : Terminating the existing ffmpeg process...
frigate4  | 2023-04-20 01:06:59.919683925  [2023-04-20 01:06:59] watchdog.Ssolfenetre           INFO    : Waiting for ffmpeg to exit gracefully...
frigate4  | 2023-04-20 01:07:05.010226626  01:07:05.010 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.22.0.2:43672->192.168.1.25:554: i/o timeout" url=rtsp://frigate:Contact12@192.168.1.25:554/Streaming/Channels/2
frigate4  | 2023-04-20 01:07:05.120042715  [2023-04-20 01:07:05] frigate.video                  ERROR   : Ssolfenetre: Unable to read frames from ffmpeg process.
frigate4  | 2023-04-20 01:07:05.120206966  [2023-04-20 01:07:05] frigate.video                  ERROR   : Ssolfenetre: ffmpeg process is not running. exiting capture thread...
frigate4  | 2023-04-20 01:07:09.921805669  [2023-04-20 01:07:09] watchdog.Ssolfenetre           ERROR   : Ffmpeg process crashed unexpectedly for Ssolfenetre.
frigate4  | 2023-04-20 01:07:09.921924186  [2023-04-20 01:07:09] watchdog.Ssolfenetre           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate4  | 2023-04-20 01:07:09.925035424  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : [rtsp @ 0x56248ee5ad40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate4  | 2023-04-20 01:07:09.925352086  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate4  | 2023-04-20 01:07:09.925355361  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : Output file #0 does not contain any stream
frigate4  | 2023-04-20 01:07:09.930234911  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.record      ERROR   : [rtsp @ 0x561a6f988e00] method DESCRIBE failed: 404 Not Found
frigate4  | 2023-04-20 01:07:09.930239949  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.record      ERROR   : rtsp://127.0.0.1:8554/SsolFenetre: Server returned 404 Not Found
frigate4  | 2023-04-20 01:07:09.930241572  [2023-04-20 01:07:09] watchdog.Ssolfenetre           INFO    : Terminating the existing ffmpeg process...
frigate4  | 2023-04-20 01:07:09.930242983  [2023-04-20 01:07:09] watchdog.Ssolfenetre           INFO    : Waiting for ffmpeg to exit gracefully...frigate4  | 2023-04-20 01:06:39.776534440  [2023-04-20 01:06:39] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate4  | 2023-04-20 01:06:39.805384322  [2023-04-20 01:06:39] peewee_migrate                 INFO    : Starting migrations
frigate4  | 2023-04-20 01:06:39.810990006  [2023-04-20 01:06:39] peewee_migrate                 INFO    : There is nothing to migrate
frigate4  | 2023-04-20 01:06:39.834366028  [2023-04-20 01:06:39] detector.cpu2                  INFO    : Starting detection process: 290
frigate4  | 2023-04-20 01:06:39.848015950  [2023-04-20 01:06:39] frigate.app                    INFO    : Output process started: 293
frigate4  | 2023-04-20 01:06:39.849095493  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.850678431  [2023-04-20 01:06:39] detector.cpu1                  INFO    : Starting detection process: 289
frigate4  | 2023-04-20 01:06:39.850683070  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.850686990  [2023-04-20 01:06:39] detector.cpu3                  INFO    : Starting detection process: 292
frigate4  | 2023-04-20 01:06:39.858521266  [2023-04-20 01:06:39] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate4  | 2023-04-20 01:06:39.863559212  [2023-04-20 01:06:39] frigate.app                    INFO    : Camera processor started for Ssolfenetre: 297
frigate4  | 2023-04-20 01:06:39.863564222  [2023-04-20 01:06:39] frigate.app                    INFO    : Capture process started for Ssolfenetre: 298
frigate4  | 2023-04-20 01:06:41.619041210  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET /api/config HTTP/1.1" 200 6044 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.669249607  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET //api/Ssolfenetre/latest.jpg?h=460 HTTP/1.1" 200 13556 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.703735782  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET / HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.744340158  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET /api/config HTTP/1.1" 200 6044 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:41.802992365  192.168.1.106 - - [20/Apr/2023:01:06:41 -0400] "GET //api/Ssolfenetre/latest.jpg?h=460 HTTP/1.1" 200 13556 "http://192.168.1.15:5001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
frigate4  | 2023-04-20 01:06:44.958134956  01:06:44.957 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.22.0.2:49052->192.168.1.25:554: i/o timeout" url=rtsp://frigate:Contact12@192.168.1.25:554/Streaming/Channels/2
frigate4  | 2023-04-20 01:06:45.067325812  [2023-04-20 01:06:45] frigate.video                  ERROR   : Ssolfenetre: Unable to read frames from ffmpeg process.
frigate4  | 2023-04-20 01:06:45.067760014  [2023-04-20 01:06:45] frigate.video                  ERROR   : Ssolfenetre: ffmpeg process is not running. exiting capture thread...
frigate4  | 2023-04-20 01:06:48.645499653  [INFO] Starting go2rtc healthcheck service...
frigate4  | 2023-04-20 01:06:59.907722515  [2023-04-20 01:06:59] watchdog.Ssolfenetre           ERROR   : Ffmpeg process crashed unexpectedly for Ssolfenetre.
frigate4  | 2023-04-20 01:06:59.907736164  [2023-04-20 01:06:59] watchdog.Ssolfenetre           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate4  | 2023-04-20 01:06:59.908136569  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : [rtsp @ 0x56445f9d3d40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate4  | 2023-04-20 01:06:59.908140261  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate4  | 2023-04-20 01:06:59.908141961  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.detect      ERROR   : Output file #0 does not contain any stream
frigate4  | 2023-04-20 01:06:59.919674974  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.record      ERROR   : [rtsp @ 0x56038c4c3e00] method DESCRIBE failed: 404 Not Found
frigate4  | 2023-04-20 01:06:59.919680653  [2023-04-20 01:06:59] ffmpeg.Ssolfenetre.record      ERROR   : rtsp://127.0.0.1:8554/SsolFenetre: Server returned 404 Not Found
frigate4  | 2023-04-20 01:06:59.919682426  [2023-04-20 01:06:59] watchdog.Ssolfenetre           INFO    : Terminating the existing ffmpeg process...
frigate4  | 2023-04-20 01:06:59.919683925  [2023-04-20 01:06:59] watchdog.Ssolfenetre           INFO    : Waiting for ffmpeg to exit gracefully...
frigate4  | 2023-04-20 01:07:05.010226626  01:07:05.010 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.22.0.2:43672->192.168.1.25:554: i/o timeout" url=rtsp://frigate:Contact12@192.168.1.25:554/Streaming/Channels/2
frigate4  | 2023-04-20 01:07:05.120042715  [2023-04-20 01:07:05] frigate.video                  ERROR   : Ssolfenetre: Unable to read frames from ffmpeg process.
frigate4  | 2023-04-20 01:07:05.120206966  [2023-04-20 01:07:05] frigate.video                  ERROR   : Ssolfenetre: ffmpeg process is not running. exiting capture thread...
frigate4  | 2023-04-20 01:07:09.921805669  [2023-04-20 01:07:09] watchdog.Ssolfenetre           ERROR   : Ffmpeg process crashed unexpectedly for Ssolfenetre.
frigate4  | 2023-04-20 01:07:09.921924186  [2023-04-20 01:07:09] watchdog.Ssolfenetre           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate4  | 2023-04-20 01:07:09.925035424  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : [rtsp @ 0x56248ee5ad40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
frigate4  | 2023-04-20 01:07:09.925352086  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
frigate4  | 2023-04-20 01:07:09.925355361  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.detect      ERROR   : Output file #0 does not contain any stream
frigate4  | 2023-04-20 01:07:09.930234911  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.record      ERROR   : [rtsp @ 0x561a6f988e00] method DESCRIBE failed: 404 Not Found
frigate4  | 2023-04-20 01:07:09.930239949  [2023-04-20 01:07:09] ffmpeg.Ssolfenetre.record      ERROR   : rtsp://127.0.0.1:8554/SsolFenetre: Server returned 404 Not Found
frigate4  | 2023-04-20 01:07:09.930241572  [2023-04-20 01:07:09] watchdog.Ssolfenetre           INFO    : Terminating the existing ffmpeg process...
frigate4  | 2023-04-20 01:07:09.930242983  [2023-04-20 01:07:09] watchdog.Ssolfenetre           INFO    : Waiting for ffmpeg to exit gracefully...`

**Comment by NickM-27** [comment]
@caublet check your go2rtc logs and make your own issue, what you're seeing is unrelated to what OP is seeing.

**Comment by mannyp26** [comment]
The cameras seem to be working now.  Not sure what changed.  But I following up on what my post was asking... does the go2rtc bundle add a camera entity for Home Assistant?  I made some additions to my config so that I am sending the main streams to go2rtc as well but the frigate integration doesn't see those streams.  I can only get the low resolution streams.  This is why I was asking if I still need to use integration Generic Camera?  Or can the frigate config file send all of my camera streams through go2rtc regardless of detection?

**Comment by NickM-27** [comment]
Frigate will only (by default) send the stream to a camera entity for the stream in go2rtc that matches the name in the cameras section. 

That being said, you don't need an entity to watch the stream. The frigate card and WebRTC card support both streams from frigate automatically.
