### ISSUE TITLE
[HW Accel Support]: QSV doesn't work on Intel 12th Generation - Fix included :) 

### ISSUE THREAD

**Issue by rjpearce** [blakeblackshear/frigate#6200]
### Describe the problem you are having

First things first, thank you for this awesome project! 🥇 

I've noticed that Hardware acceleration via QuickSync is not currently working on 12th generation Intel Alder Lake  [N100](https://ark.intel.com/content/www/us/en/ark/products/231803/intel-processor-n100-6m-cache-up-to-3-40-ghz.html) (QSV capable)

ffmpeg will error with:

```bash
Error setting child device handle: -17
Segmentation fault (core dumped).
```

I've managed to debug the issue by making changes inside the container. The problem is caused by a lack of support in the version of ffmpeg (`ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1`) and the Intel libraries bundled in Frigate. Updating ffmpeg to the last nightly (`ffmpeg-n5.1.3-6-g1e413487bf-linux64-gpl-5.1`) and updating some of the Intel packages using the [instructions](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-legacy.html#step-1-add-package-repository) from the Intel website for 12th gen. 

It is also worth noting that the host will also need to run kernel `>=5.19.0-28`. 
I also skipped the install of `intel-level-zero-gpu` in the container as it failed, I presume it is some kind of firmware that the host needs but isn't applicable inside the docker container. 

Below are the changes required to the Dockerfile in order to make this work, this might not be the smallest set of changes required but it certainly resolves the problem:

```bash
FROM ghcr.io/blakeblackshear/frigate:stable
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install wget xz-utils gpg -y

RUN wget -qO btbn-ffmpeg.tar.xz  \ 
      https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-04-21-12-47/ffmpeg-n5.1.3-6-g1e413487bf-linux64-gpl-5.1.tar.xz && \
    tar -xf btbn-ffmpeg.tar.xz -C /usr/lib/btbn-ffmpeg --strip-components 1

RUN wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg && \
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu jammy legacy' | tee  /etc/apt/sources.list.d/intel.gpu.jammy.list

RUN apt-get update
RUN apt-get install -y \
  intel-opencl-icd \
  level-zero \
  intel-media-va-driver-non-free \
  libmfx1 \
  libmfxgen1 \
  libvpl2
```

I'm happy to submit a merge request for this but I wanted to consult on:
1. Are happy with my findings?
2. Where do you want the changes to go [install_deps.sh](https://github.com/blakeblackshear/frigate/blob/dev/docker/install_deps.sh)?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.99
logger:
  default: debug
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264
cameras:
  driveway: 
    ffmpeg:
      inputs:
        - path: rtsp://redacted:redacted@192.168.10.94:554/Streaming/channels/2
          roles:
            - detect
    detect:
      width: 640 
      height: 480
```

### docker-compose file or Docker CLI command

```yaml
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=64m \
  --cap-add=CAP_PERFMON \
  --privileged \
  -v /home/redacted/frigate/media:/media/frigate \
  -v /home/redacted/frigate/config:/config \
  -v /etc/localtime:/etc/localtime:ro \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable
```

### Relevant log output

```shell
2023-04-22 16:14:36.795911877  [2023-04-22 16:14:36] watchdog.driveway              ERROR   : Ffmpeg process crashed unexpectedly for driveway.
2023-04-22 16:14:36.804228918  [2023-04-22 16:14:36] watchdog.driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-22 16:14:36.804614315  [2023-04-22 16:14:36] ffmpeg.driveway.detect         ERROR   : [AVHWDeviceContext @ 0x55e574bb1200] Error setting child device handle: -17
```

### FFprobe output from your camera

```shell
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://redacted:redacted@192.168.10.94:554/Streaming/channels/2':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.160000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 6 fps, 12.50 tbr, 90k tbn
```

### Operating system

Other Linux

### Install method

Docker CLI

### Network connection

Wireless

### Camera make and model

Hikvision DS-2CD2563G0-IS

### Any other information that may be helpful

Ubuntu 22.10 (Kinetic)
Kernel: 5.19.0-40-generic
The frigate config and information provided has been simplified and redacted to make it easier to discuss.

**Comment by NickM-27** [comment]
Thank for including this info along with a fix.

Updating ffmpeg and the intel driver is not a trivial thing since in 0.11 it took many beta and RC cycles to find versions that worked for all setups. There is also the fact that qsv does not offer any advantages over vaapi (when it comes to frigate's usage) and actually there are some advantages to just using vaapi instead. So for now I think the recommendation would be to use `preset-vaapi` since they offer similar if not identical performance on 12th gen with the added bonus that vaapi supports automatic profile selection.

**Comment by NickM-27** [comment]
also, we can't use nightly updates because btbn removes those after some time which would make the build break, we have to use the long term support versions which come out at the end of the month.

**Comment by rjpearce** [comment]
Thanks for the quick reply and additional info, if that's the case I close this and I will switch back to `preset-vaapi`

It might be useful to update the docs with the recommendation `preset-vaapi` vs `qsv` from a performance perspective, I had assumed Quicksync would be better purely as it was newer and only available ">=10th Generation only". 

Thanks again

**Comment by NickM-27** [comment]
It supports more features but frigate doesn't use those features since they're not applicable. We've done some recent updates to the docs that haven't been merged yet which should reflect this.

**Comment by Coder84619** [comment]
> Thanks for the quick reply and additional info, if that's the case I close this and I will switch back to `preset-vaapi`
> 
> It might be useful to update the docs with the recommendation `preset-vaapi` vs `qsv` from a performance perspective, I had assumed Quicksync would be better purely as it was newer and only available ">=10th Generation only".
> 
> Thanks again

Do you see a CPU reduction with VAAPI? I got VAAPI working on 12th gen Intel, but it doesn't do anything to CPU utilization for ffmpeg or the VM as a whole.

**Comment by joakimberg** [comment]
Also running 12th gen. From my experience/use case, switching to a recent ffmpeg and running QSV is as of now better than running the stock ffmpeg with VAAPI preset.

My main issue with the VAAPI scaling preset is that it does not seem to actually upload to hardware before changing framerate (I detect in 4K 8fps from main stream). So changing the vaapi scaling preset by prepending 'hwupload' to the filter chain as such:

from: `-r {0} -vf fps={0},scale_vaapi=...`
to: `-vf hwupload,fps={0},scale_vaapi=...`

everything gets put in hardware and cpu drops from >30% to ~13% per detect-related ffmpeg process (the one that outputs rawvideo in yuv420p to pipe: ). Also intel_gpu_top started to show usage on '3D/Render', before that it showed zero usage. Since the input resolution was identical to the output resolution in my case, only Video + VideoEnhance showed usage before and after. Not sure if this is 12th gen specific when using vaapi, and I do not know if this solution will break on other cpus supporting vaapi. This issue is not present when using the `intel-qsv-h264` scaling preset since it is clearly using hardware acceleration to change framerate (`-r {0} -vf vpp_qsv=framerate={0}:w={1}:....`).

Hope it helps someone running on 12th gen with the 'high ffmpeg usage' warning.

**Comment by jerome71** [comment]
Thanks Thanks @joakimberg 
Using the vaapi preset, I see GPU usage in intel_gpu_top (in the system's terminal) at 0% (but I sometimes see GPU usage in the Frigate UI).
If I switch to preset-intel-qsv-h264, I see 9% VideoEnhance usage in intel_gpu_top.

Since I understand vaapi has its advantages, I'd like to prepend "hwupload" to the filter chain in the vaapi scaling preset.
How can I do that?
Thanks in advance :-)
