### ISSUE TITLE
Improve missing codec error reporting

### ISSUE THREAD

**Issue by SchoolGuy** [blakeblackshear/frigate#6207]
**Describe what you are trying to accomplish and why in non technical terms**

As a user, I want to be able to report errors to my application admin correctly.

**Describe the solution you'd like**

Show a human-readable error message in case a video cannot be played due to unavailable codecs. A user could also be advised to try a different browser (for example Edge, Chrome, Safari, ...).

**Describe alternatives you've considered**

The current "media cannot be played" message is not very descriptive, leaving it as is would be user-unfriendly in my eyes.

**Additional context**

I discovered that this is a problem during the debugging of #6206. The funny thing is that the video can be played on the host directly via VLC because apparently, it has the correct codecs.

Screenshot of the error:

![grafik](https://user-images.githubusercontent.com/15035141/233836389-115be580-d9e0-4065-b4d7-64223b90be1e.png)

**Comment by NickM-27** [comment]
This isn't going to be a codex issue, most likely the browser itself just doesn't like it. If you create a support issue we'd be happy to debug. 

Also, there's nothing we can do to make these error messages more specific as they come directly from the browser and this single error message can be caused by literally 10+ different issues. If we tried to infer the error message we'd likely just end up steering users the wrong way. 

If you don't want to create a support issue, using chrome://media-internals is the best way to get detailed information about the failure to playback

**Comment by SchoolGuy** [comment]
@NickM-27 I will gladly open a support issue. However in the end I still believe that something should be improved on this end. My parents (and even I) weren't able to spot that this issue is not related to missing video files in the UI. I tested this across two OS versions (openSUSE Tumbleweed with Pacman Codecs & Windows 11) on both Chrome and Firefox and the results were consistent. Considering the easy integration that this app provides on HomeAssistant OS (and related hardware appliances) I would expect that users who cannot spell the word Docker or Linux will use this app and as such I would hope that the app gives error messages that are directed at this audience.

**Comment by SchoolGuy** [comment]
As request support issue was opened: https://github.com/blakeblackshear/frigate/issues/6210

**Comment by SchoolGuy** [comment]
Still relevant IMHO

**Comment by SchoolGuy** [comment]
Still relevant IMHO

**Comment by SchoolGuy** [comment]
Since it seems no other users are interested in this feature, I will close the issue.
