### ISSUE TITLE
[Config Support]: snapshot retention not working

### ISSUE THREAD

**Issue by Morphy99** [blakeblackshear/frigate#6274]
### Describe the problem you are having

I'm sure there is an obvious answer to this but I'm all out of search terms to enlighten me...

I have snapshot retention set to 20 yet my media/frigate/clips folder is full of old snapshots from 2022

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: False
  retain:
    default: 20
```

### Relevant log output

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
Most likely you've deleted your db at some point, frigate only clears segments that are in the db

**Comment by Morphy99** [comment]
Nope, never deleted the db. 
Going back from 06/04 I have a few (!) less snapshots per day (8-20) but they're still there, every day (pretty much, not verified it exactly) going back to 08/2022. Which I'm guessing where my db got wiped.
From 07/04 (inside the 20 day retention) I have thousands per day as expected.

**Comment by NickM-27** [comment]
do you see these snapshots / events in the web UI? are they starred? if they aren't there then they aren't in the DB

**Comment by blakeblackshear** [comment]
If you do see the events for these snapshots in the UI, can you post the snapshots section of your JSON config at `/api/config`?

**Comment by carldanley** [comment]
I also have this same issue by the way.

Relevant configs:

```
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 10
```

Yet, on my Synology DS918+, I see this in the clips folder:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/5e367881-90fc-4611-a51e-00c15402bbb3)

However, the recordings folder only has the 14 days I told it to retain:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/c505c465-2671-4f9e-9bb2-9927eb6cf680)

It's like the clips aren't being cleaned up. I've been tempted to write a couple of quick scripts to clean up files older than `x` but I feel like either my config is wrong or i'm missing something obvious? Or maybe clip storage retention isn't working correctly?

**Comment by NickM-27** [comment]
this usually happens because the db was deleting or something else is wrong with the config, all storage retention is working as expected for me.

**Comment by carldanley** [comment]
Config here: https://github.com/carldanley/home-ops/blob/main/kubernetes/apps/nvr/frigate/app/config/config.yaml

If there was an error/issue with the db deleting, I had nothing to do with it. If what you're saying is that some issue caused the db deletion to be interrupted, I feel like Frigate should still clean up the old files if older than the retention period - it's not like I store other things in this directory - Frigate owns it.

**Comment by NickM-27** [comment]
what about docker (or similar) config?

> I feel like Frigate should still clean up the old files if older than the retention period - it's not like I store other things in this directory - Frigate owns it.

I disagree, you may not but other users do different things and I think it is dangerous proposition to have frigate just start deleting any file that it doesn't know about in a folder

**Comment by carldanley** [comment]
I agree about it being dangerous - maybe there should be a configuration option called `manage_directory: true` or something that has a default value of `false`. Then, users (like me), don't have to:

a) waste time and effort writing scripts to cleanup a directory ultimately owned by frigate (in our case)
b) not Gigabytes of data on a faulty db deletion process

> what about docker (or similar) config?

Are you asking for the configuration on how it's deployed? It's a kubernetes statefulset and the specification can be found here:
https://github.com/carldanley/home-ops/blob/main/kubernetes/apps/nvr/frigate/app/helmrelease.yaml

**Comment by carldanley** [comment]
Also, I don't think it's a great for users to use the same directory for multiple frigate instances - seems weird because of the very small chance for file overwrites but 🤷🏻

**Comment by carldanley** [comment]
Just checked my `clips` directory, it is a substantial amount of storage for clips:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/73518cef-60be-43d9-8c98-aeaa16246964)

If I could opt-in to a configuration option that managed this folder correctly, that'd save me a very large portion of data which is doing nothing for me at the moment.

**Comment by NickM-27** [comment]
> Also, I don't think it's a great for users to use the same directory for multiple frigate instances - seems weird because of the very small chance for file overwrites but 🤷🏻

I don't disagree but regardless there are other cases as well where the wrong folder is mounted to /media/frigate/clips or something. 

frigate doesn't delete the db, so this is some kind of issue somewhere. Part of the issue may be that frigate deletes the db entry then tries to delete the image and if the image can't be delete it won't try again.

I think the effort would be better spent trying to figure out what the issue is, as opposed to creating a file manager that just deletes all files after they are not appropriately cleaned up

**Comment by carldanley** [comment]
> I don't disagree but regardless there are other cases as well where the wrong folder is mounted to /media/frigate/clips or something.

Fair point.

> frigate doesn't delete the db, so this is some kind of issue somewhere. Part of the issue may be that frigate deletes the db entry then tries to delete the image and if the image can't be delete it won't try again.

Ah, I see. I was thinking there was a loop (or some sort of cron-based job that did it - not privy on the internals of how the rention deletion is handled).

> I think the effort would be better spent trying to figure out what the issue is, as opposed to creating a file manager that just deletes all older files after they are not appropriately cleaned up

This is where I'm stuck, I haven't been able to figure it out - the config file I'm using is pretty straight forward. Maybe I'm missing something obvious? Not sure.

In any event, I think I'm going to write a small Go program to clean up the directory later tonight and maybe run it as a sidecar to the frigate container (unless I can figure out where the issue is on my end).

**Comment by NickM-27** [comment]
Yeah the difficulty is that I've only seen a few reports. One was related to bad permissions on a network mount, and another was due to the user deleting the db file on accident. 

So without a pattern or something it's not totally clear. Maybe after your script clears out everything current it will be easier to see what's going on

**Comment by carldanley** [comment]
So... I wrote a CLI tool that parses the frigate configuration and identifies the maximum retention period for clips and then scans the directory for clips older than the maximum retention period.

The tool is located here: https://github.com/carldanley/frigate-clip-cleaner. I still need to write docs, tests and do some general cleanup but after the first `--dry-run` pass, here are the results of what Frigate left behind:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/d888f131-d204-4e2f-a44f-bc752003d2c2)

Basically, it seems like every single clip was never cleaned up. I'm going to check file permissions later and verify but it can definitely read/write to the directory (else, how would the files get there).

This is consistent with the number of files in the directory and the space consumed:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/7b5ac8db-86e4-4250-b703-a70acbab7d23)

Going from 101.2 GB space used to 13 GB space used is a HUGE improvement regardless of whatever the reason is that they were not cleaned up.

If you're curious about how it's deployed, see here: https://github.com/carldanley/home-ops/blob/main/kubernetes/apps/nvr/frigate/app/clip-cleanup/helmrelease.yaml#L28-L41

**Comment by carldanley** [comment]
I had to step away from this for a bit for some work-related things but catching up:

I've deployed this tool as a `CronJob` in my Kubernetes cluster and gave it the same network-shared mount that the other container uses. It was able to successfully delete all of the files without a single problem. I have strong reasoning to believe it isn't related to file permissions (as I can read & write without issues). I also exec'd into the frigate container and ran `rm <filename>` and it completes perfectly fine.

I think this clip cleanup routine in Frigate needs to be double checked and there needs to be additional debugging involved to raise awareness for when a clip fails to delete.

After letting my tool finish, these were the results:

![image](https://github.com/blakeblackshear/frigate/assets/1470571/357a462e-e434-4910-ab3f-6a2c232c44d9)

That's a lot of data just sitting around. I wonder how many other people have the same issue.
