### ISSUE TITLE
[Support]: Truecharts Frigate. Could not write config file, be sure that Frigate has write permission on the config file.

### ISSUE THREAD

**Issue by Svyatk0** [blakeblackshear/frigate#6739]
### Describe the problem you are having

Hey. I am aware this was raised already and resolved in cases where one has access to setting permissions on the config.yml file. 

In my case, however, i am using [truecharts Frigate ](https://github.com/truecharts/charts/tree/master/charts/incubator/frigate) installation on Truenas Scale, where the path and therefore access to config.yml isnt exposed/mounted on the host. 

I raised it with Truecharts, but not much help there https://github.com/truecharts/charts/issues/9461

Any suggestions how to aid this problem when the config.yml is actually stored in the pod itself? 

Much appreciated, 

Svyatko

### Version

8.0.4

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Could not write config file, be sure that Frigate has write permission on the config file.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by doctorttt** [comment]
I can see that you're likely on TrueNAS Scale. I suggest you not to use the Truechart version of Frigate because the Truechart team makes some modifications on the image to work with TrueNAS Scale's app platform. And as you already know, you will not be able to get any meaningful support from the Truechart team.

I came from TrueNAS Scale before settling on using Unraid. While I was on TrueNAS Scale, I was able to get Frigate to work successfully using the project's original docker image.  First, I suggest you to use the Frigate's official docker image so you don't have to worry about other things that Truechart puts on of it. 

At a very high level: 
- You need to supply a config.yml file to the docker container - this holds true on the TrueNAS Scale platform. I suggest you have a look at Frigate's website to setup a very basis config.yml first.

- Once you have the basis config.yml ready, you will need to tell TrueNAS where to find the config.yml file. This is where you use hostpath to map your config.yml and so the Frigate docker container knows where to find it.  

Based on what you reported, I just think you're running into mapping issues and/or permission issues. 

Later on once you get Frigate to run on TrueNAS Scale, you will need to use hostpath mapping for other things like cache and shm. Overall, I recommend you take a stab on installing Frigate on TrueNAS Scale using the official docker image. I know it will work on TrueNAS Scale because I got it work as I said.

**Comment by Ornias1993** [comment]
A bit of a necro, but as this shows up quite high in google i'm still going to respond:

- No, we never ever modified the frigate image in any way, shape or form, we don't even build the image at all.
- The only reason this user didn't get support, was the fact it was not a finished Chart (this is what "incubator" means)
- The reason behind the GUI being limited, is due to iX systems not having text fields for custom config exposed. That's an iX limitation and not something we can fix
