### ISSUE TITLE
Live view seems to be making too many requests

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#677]
In 0.8.1, My browser made 475 requests in 1 minute, which comes out to ~8 fps for the live view. It seems as if each file is being requested twice in the network logs:
![image](https://user-images.githubusercontent.com/569905/106384809-65d89580-6392-11eb-8703-07139da0bea4.png)

This is also related to #600. Currently, I am transferring >200mb per minute while watching a live feed.

**Comment by paularmstrong** [comment]
Looks like a cache issue. Because everything from the `/api/` is set to `Cache-Control: "no-store"`, moving the [`img.src`](https://github.com/blakeblackshear/frigate/blob/d376f6b1d230858fe61006248a9b6530d9b390ff/web/src/components/CameraImage.jsx#L53) from the preload while the current version is displaying onto the action [`<img>`](https://github.com/blakeblackshear/frigate/blob/d376f6b1d230858fe61006248a9b6530d9b390ff/web/src/components/CameraImage.jsx#L43), the browser will reload it.

We need to set some sort of cache-control and expires headers properly on resources from the api, otherwise they will always be reloaded. I'll put up some options to talk through

**Comment by paularmstrong** [comment]
There is actually another alternative that I hadn't considered: we could be preloading the same way, but drawing to a `<canvas />` element, sidestepping the preact render loop altogether. This may be a bit more efficient for all camera images, not just the live view

**Comment by paularmstrong** [comment]
I've implemented a cache header in nginx on requests to `/api/` that include `?cache=` and I'm wondering if there's a bug in Chrome. Here's the same code running for Chrome (top) and Firefox (bottom)

<img width="642" alt="Screen Shot 2021-01-31 at 3 50 11 PM" src="https://user-images.githubusercontent.com/33297/106401982-2fc00380-63dc-11eb-99dd-7c0dfa27235f.png">

**Comment by paularmstrong** [comment]
And Safari gets it right as well
<img width="1392" alt="Screen Shot 2021-01-31 at 3 59 05 PM" src="https://user-images.githubusercontent.com/33297/106402198-46b32580-63dd-11eb-9c43-09faa33177f0.png">
