### ISSUE TITLE
[Support]: What kind of cameras are supported?

### ISSUE THREAD

**Issue by davidyang** [blakeblackshear/frigate#7091]
### Describe the problem you are having

I have an INVID system with INVID cameras and an INVID NVR.  It's terrible and basically unusable except to watch Live or Playback time.

It appears that the cameras support H264 and RTSP but I know very little about NVR systems.  Would I just buy a standard PC, put Debian on it with a Coral TPU and put it on the same network as the cameras and expect that it would discover the cameras that are streaming?  I saw the list of recommended cameras but I'm hesitant to buy new cameras before trying Frigate out.

My current NVR is an INVID VN1A-16x16 with 8 VIS-P8TXIR28NH cameras running on POE.  

Also, can I test this out on Mac just to see if it discovers the cameras?

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

INVID VIS-P8TXIR28NH

**Comment by NickM-27** [comment]
It needs to be supported by ffmpeg, if it supports rtsp over network then it should work. Frigate does not auto-discover cameras.

**Comment by davidyang** [comment]
Is there any way for me to test it?  I only have an Apple Silicon Mac right now where I am.

**Comment by NickM-27** [comment]
Sure, just run ffmpeg on the Mac and see if you can save a stream to MP4 and play it back.

**Comment by davidyang** [comment]
Awesome - I couldn't get it to work with ffmpeg but got it to work with VLC and ffplay.  What kind of machine would be recommended for 8 1080p streams?  It's streaming through RTSP from the INVID server (not sure if there are limits there) rather than directly from the cameras (since the cameras are on a separate network right now).

**Comment by spacebares** [comment]
If you got it to work with vlc then chances are you just messed up some ffmpeg argument somewhere. All frigate needs is an RTSP stream and if vlc can view it, high chance frigate can too.

Since you have an OEM nvr for your cameras i advise fixing the 24/7 recording function for it. Your first couple of days or weeks _(heh)_ of using frigate can be frustrating as you solve compatibility issues and configuration mistakes where you can lose footage without realizing it. Having a fallback like that is such a great peace of mind, especially for me, i run the dev branch of frigate which sometimes can be unstable.

Most of the time a frigate setup is straight forward but i learned when using cameras that don't really fall into the norm like reolink's http streams or INVID Server RTSP streams_(???)_ things usually take a bit of extra work to get working right.

For frigate you will need a high resolution stream and a low resolution stream for each camera. The VIS-P8TXIR28NH's you have support this behavior. You would configure the substream as frigate's Detect mode and the high resolution 8MP for frigate's Record mode, All explained in the docs. 
You mention you want to use a coral, which wouldn't even break a sweat for 8 cameras. Just make sure its plugged into a USB3.0 slot!!! Also [Frigate supports a couple of other accelerators besides coral if you don't have one. ](https://docs.frigate.video/configuration/detectors/)

Its advised to use an actual computer for frigate, as CPU is required to process the image when theres motion, send it to the coral _(or other detector)_ and then decide to generate an event, etc etc. 

For my setup i have 6, 5MP cameras using 896x512 detect streams. and Two 1080P cameras using 1080P detect streams. During a rainy day when all cameras have motion **my skylake i5-6300 gets to 40-50% cpu usage**. I have an rx570 in there for [HWACCEL](https://docs.frigate.video/configuration/hardware_acceleration) but im thinking of removing it to reduce heat in the little closet its in. I could never get the skylake to work with hwaccel... I have noticed that the cpu usage is not accumulative. so if 8 cameras are 50% cpu usage, 16 cameras does not mean 100% cpu usage. 
Currently at 2.36/8GB for ram usage. The Frigate Database is on an SSD and i use a 1TB hdd for the event recordings.

**Comment by davidyang** [comment]
Thanks for the awesome info - that's super helpful for gauging what kind of HW I need to have!
