### ISSUE TITLE
Allow main and substreams for recording vs object detection

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#734]
Most quality cameras have 2 streams, the main one and the substream which is a low quality version. The substream makes sense for object detection but now that frigate has recording ability, I'd like to be able to record the mainstream but still use the substream for the object detection.

**Comment by blakeblackshear** [comment]
That's what most people are already doing. Add multiple inputs and set the roles the way you want: https://blakeblackshear.github.io/frigate/configuration/cameras#example

**Comment by ljmerza** [comment]
sorry, if you can add two streams why do can you only set the height/width values for one? which one would i use?

**Comment by blakeblackshear** [comment]
Only the input with the detect stream is decoded and processed, so that's the only one where width and height need to be specified. The other roles just pass through the feed without any processing, so it doesn't matter what the resolution is.

From the docs:
![image](https://user-images.githubusercontent.com/569905/107168099-4936f180-6980-11eb-9447-8efd6dd05928.png)
