### ISSUE TITLE
Unable to connect to Frigate" error when adding integration - using HACS not Docker

### ISSUE THREAD

**Issue by HSB-collab** [blakeblackshear/frigate#784]
This issue has come up before for those using the Docker container but it was closed. I am not using Docker.
'I am using Home Assistant 2021.2.1 on a 4GByte Raspberry Pi. I would like to integrate some IP cameras with person detection so I am trying to install Frigate. I have added the Frigate Repository version 1.0.3 to HACS and installed the Mosquitto MQTT broker.
However, when I try to add the Frigate Integration under /configuration/integrations I get “Unable to Connect to Frigate”. I have tried using the host http://localhost:5000 and http://frigate:5000 but in both cases I get the same message.

The log file gives me the following messages:

```
*Logger: custom_components.frigate*
*Source: custom_components/frigate/api.py:90*
*Integration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [issues](https://github.com/blakeblackshear/frigate-hass-integration/issues))*
*First occurred: 11:33:04 AM (4 occurrences)*
*Last logged: 11:37:42 AM*
** Error fetching information from http://frigate:5000/api/stats - Cannot connect to host frigate:5000 ssl:default [Try again]*
** Error fetching information from http://localhost:5000/api/stats - Cannot connect to host localhost:5000 ssl:default [Connect call failed ('127.0.0.1', 5000)]*
** Error fetching information from http://10.0.0.214:5000/api/stats - Cannot connect to host 10.0.0.214:5000 ssl:default [Connect call failed ('10.0.0.214', 5000)]*
** Error fetching information from http://ccab4aaf-frigate:5000/api/stats - Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]*
```
And

```
Logger: custom_components.frigate
Source: custom_components/frigate/config_flow.py:84
Integration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [issues](https://github.com/blakeblackshear/frigate-hass-integration/issues))
First occurred: 11:33:04 AM (4 occurrences)
Last logged: 11:37:42 AM
* Cannot connect to host frigate:5000 ssl:default [Try again]
* Cannot connect to host localhost:5000 ssl:default [Connect call failed ('127.0.0.1', 5000)]
* Cannot connect to host 10.0.0.214:5000 ssl:default [Connect call failed ('10.0.0.214', 5000)]
* Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]
```
Any help would be greatly appreciated.

**Comment by blakeblackshear** [comment]
The integration only serves a way to connect to the docker container. It does not do anything on its own.

**Comment by HSB-collab** [comment]
I am sorry but I am struggling to understand. I set up Home Assistant on a Raspberry Pi4 using the custom Home Assistant build for the Pi.
Are you saying I need to run Frigate in a docker container on a different machine from Raspberry Pi that is running Home Assistant? I thought that the HACS repository installed Frigate on my Home Assistant machine and that the docker container was for the older system called hass.io (I find the whole nomenclature for the 2 types of HA systems really confusing). 
Or do I need to install docker on the Raspberry Pi Home Assistant version? But I can't see any way of doing that.

**Comment by blakeblackshear** [comment]
HACS does not install Frigate. It installs a homeassistant integration for Frigate. If you used a supported install method for HomeAssistant, then you are definitely running it in docker already. How did you setup your Raspberry Pi?

**Comment by HSB-collab** [comment]
Hi Blake

Thanks for taking the trouble to reply to me. It must be very frustrating to have to deal with noobies who don't know what they are doing!

I installed Home Assistant on the Raspberry Pi according to the instructions at https://www.home-assistant.io/installation/raspberrypi. There is no mention of docker and it refers to "Home Assistant Operating System" so I assumed that it was running natively on the Pi.

Am I to assume that the Home Assistant Operating System has Docker built in and that I should add the container image to the Pi? I am not sure how to do that? Your documentation refers to HassOS but in the confusing nomenclature of HA, I thought I am running a newer architecture?

Sorry about all the questions.

Regards

**Comment by paularmstrong** [comment]
Home Assistant does, in fact, have Docker as part of it. However, it does not give you direct access to Docker.

In Home Assistant, it's rebranded under "Supervisor". The "Add-ons" that are available are configured wrappers around docker images.

Here's a step-by-step instruction for those using Home Assistant OS:

1. from the left side nav of Home Assistant, click "Supervisor". 
2. Around the center-top of the page, click "Add-on Store"
3. At the far right top of this page, three vertical dots will appear. Click this
4. From the dropdown that appears, click "Repositories"
5. At the bottom of the new modal that appears, paste `https://github.com/blakeblackshear/frigate-hass-addons` into the input box that says "Add repository", then click "Add"
6. Close this modal
7. Under "Frigate Hass.io addons", click "Frigate NVR"
8. On this new page, you should see a button near the bottom-left of the main content that says "Install" click this.
9. Before starting the add-on, you'll need to create a `frigate.yml` file in your Home Assistant configuration directory. Follow the format specified in the Frigate docs here: https://blakeblackshear.github.io/frigate/configuration/index
10. Now you should be ready to start the Frigate add-on. Head back to the Supervisor section, click "Frigate" and then "Start"

In order to get Home Assistant to actually have sensors and receive data from Frigate, you'll want to install the [integration](https://github.com/blakeblackshear/frigate-hass-integration) (via HACS or manually). (note: integrations are also sometimes called "custom components")

**Comment by HSB-collab** [comment]
Thank you @paularmstrong for this very detailed explanation. It was a huge help. I realise that I was confusing HassOS with Hass.io so I did not read the HassOS Addon documentation in the docs properly. My bad. 
I have installed the HassOS Addon as above, but for some reason, I now cannot find the Frigate Integration under /configuration/integrations on Home Assistant? I have started the Frigate NVR Addon,  installed the HACS Repository, the config/custom_components/frigate directory is there but there is no integration. 
Any advice?

**Comment by paularmstrong** [comment]
Did you click "+ Add Integration" in the bottom right and search for Frigate in the modal that pops up? If it still doesn't show up, you'll need to restart HA from Configuration > Server Controls, then check again.

**Comment by HSB-collab** [comment]
Once again thanks for taking the time to respond. I have added the repository in HACS and nothing appears in the Integrations list (as per the screenshots).
![integration](https://user-images.githubusercontent.com/72898374/107837463-0ac48b00-6df5-11eb-83e3-c0ef58ae2132.JPG)
![HACS repository](https://user-images.githubusercontent.com/72898374/107837464-0bf5b800-6df5-11eb-8e4f-a5c8317c4a0c.JPG)

 I have restarted multiple times.

**Comment by blakeblackshear** [comment]
I saw someone mention something about clearing the browser cache.

**Comment by HSB-collab** [comment]
Ah, thanks! That seems to have fixed it. The frigate integration has now appeared. Thanks for all your help.

**Comment by HSB-collab** [comment]
Thanks @blakeblackshear and @paularmstrong - I now have this working.
