### ISSUE TITLE
Consider Moving to PyCoral from TFLite for Coral Support

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate#786]
edgetpu from coral is deprecated, you can use the PyCoral library to reduce complexity of your edgetpu.py code

See -> https://github.com/google-coral/pycoral/blob/master/examples/detect_image.py

API -> https://coral.ai/docs/reference/py/

**Comment by blakeblackshear** [comment]
Maybe. I am not using the edgetpu library wrapper because it's slower. I am doing a lot of the prep work to resize and convert the image into a numpy matrix with the right dimensions in an entirely separate process. The detection process does nothing other than grab a presized/preformatted input from memory, run detection, and hand off the output. Since I am splitting the work across multiple processes, these wrapper libraries don't typically fit my use case.

**Comment by mitchross** [comment]
> Maybe. I am not using the edgetpu library wrapper because it's slower. I am doing a lot of the prep work to resize and convert the image into a numpy matrix with the right dimensions in an entirely separate process. The detection process does nothing other than grab a presized/preformatted input from memory, run detection, and hand off the output. Since I am splitting the work across multiple processes, these wrapper libraries don't typically fit my use case.

Thanks for explanation!
