### ISSUE TITLE
Feature Request - Runtime toggle for the full-time recording feature

### ISSUE THREAD

**Issue by mcd1992** [blakeblackshear/frigate#831]
**Describe the request**
Requesting the ability to toggle full-time recording via MQTT, HASS component, API, and Web UI like we have for motion/clips/snapshots. I may take a shot at implementing it whenever I get around to setting up a dev environment for it.

**Version of frigate**
0.8.3-d771726

**Comment by blakeblackshear** [comment]
It's different than the others because it requires stopping ffmpeg which is managed in an entirely separate python process. I am thinking about implementing a "required_motion" config option under 24/7 recording which would just delete any segments that didn't have any motion rather than renaming/moving the files. It would be simple to implement a switch that way and just delete them rather than rename/move, but the ffmpeg process will still be running and writing to disk.

**Comment by mcd1992** [comment]
I see. I guess that fits my use-case as well as long as the 'required_motion' check is effected by the 'detect' setting; in that no motion will ever be detected with it off.

I'm currently turning 'detect' on with HASS when I leave the house and off when I return. Basically wanting to disable recording on the inside cameras while home.
