### ISSUE TITLE
[Support]: Server returned 401 Authorization failed

### ISSUE THREAD

**Issue by lxtzfr** [blakeblackshear/frigate#9010]
### Describe the problem you are having

Frigate cannot connect to my camera.

"No frames have been received, check error logs"

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://testtest:testtest@192.168.0.221:554/stream1
          roles:
            - record
```

### Relevant log output

```shell
2023-12-18 22:34:50.115728938  [2023-12-18 22:34:50] ffmpeg.camera.detect           ERROR   : rtsp://*:*@192.168.0.221:554/stream1: Server returned 401 Unauthorized (authorization failed)
```

### FFprobe output from your camera

```shell
From Web Button:
Infinite loading

From Container Console:
[rtsp @ 0x560038e1a140] method DESCRIBE failed: 401 Unauthorized
rtsp://testtest:testtest@192.168.0.211:554/stream1: Server returned 401 Unauthorized (authorization failed)
```

### Frigate stats

```json
{"camera":{"camera_fps":0.0,"capture_pid":296,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1662,"pid":294,"process_fps":0.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"109":{"cpu":"0.3","mem":"2.0"},"118":{"cpu":"0.0","mem":"0.2"},"1202":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"144":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"1661":{"cpu":"0.0","mem":"0.0"},"1672":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"287":{"cpu":"0.0","mem":"0.1"},"288":{"cpu":"0.0","mem":"1.1"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.3","mem":"1.1"},"293":{"cpu":"0.0","mem":"0.2"},"294":{"cpu":"0.0","mem":"1.1"},"295":{"cpu":"0.0","mem":"0.2"},"296":{"cpu":"0.0","mem":"1.1"},"30":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"317":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"0.0","mem":"0.2"},"MiB":{"cpu":"6398.0","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"0.01,"}},"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":10.0,"pid":288}},"service":{"last_updated":1702937771,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":209.2,"mount_type":"tmpfs","total":209.7,"used":0.5},"/media/frigate/clips":{"free":994848.3,"mount_type":"exfat","total":1000185.3,"used":5337.0},"/media/frigate/recordings":{"free":994848.3,"mount_type":"exfat","total":1000185.3,"used":5337.0},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":1940,"version":"0.12.1-367d724"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Tapo C200

### Any other information that may be helpful

Works perfectly in VLC.
I cannot disable authentication on my camera.
I can ping my camera from the docker container.
I tried with different logins.

**Comment by geerlingguy** [comment]
I am running into this same issue on one of my two Annke C800 cameras. The first camera is fine (just unboxed it and set it up). The second camera, I have confirmed works in VLC, can ping from within the container, and I get:

```
2024-01-03 22:32:53.431466939  [2024-01-03 22:32:53] ffmpeg.front_yard.detect       ERROR   : [rtsp @ 0x55565816fea0] method DESCRIBE failed: 401 Unauthorized
2024-01-03 22:32:53.431469883  [2024-01-03 22:32:53] ffmpeg.front_yard.detect       ERROR   : rtsp://*:*@mycam:554/H264/ch1/sub/av_stream: Server returned 401 Unauthorized (authorization failed)
```

I _think_ the only difference here is the outside camera has a microSD card inserted... That's also the only difference in the camera's web UI config—the front_yard camera shows "Number of HDDs: 1", and it is set to record to that card continuously:

<img width="296" alt="Screenshot 2024-01-03 at 10 36 56 PM" src="https://github.com/blakeblackshear/frigate/assets/481677/c14366f1-9a3d-4269-8073-0f1aa2e92a8a">

I only mention this because over in https://github.com/blakeblackshear/frigate/issues/9068#issuecomment-1869132116 someone mentioned they removed the SD card from their camera and it started working... :/

**Comment by geerlingguy** [comment]
Update: rebooting the camera fixed it. I had originally entered the wrong credentials in the Frigate configuration. Because Frigate tries to connect every once in a while, after 7 attempts, the Frigate server's IP got blacklisted by the Annke camera's 'Illegal Login Lock' function:

<img width="634" alt="Screenshot 2024-01-03 at 10 43 19 PM" src="https://github.com/blakeblackshear/frigate/assets/481677/54ed524b-f468-4eda-a60f-f0b6f5749ca4">

I rebooted the Annke camera, and Frigate now has a clean signal. Yay!

**Comment by cuee101** [comment]
Had same issue with a Hik-Vision and yes that fixed for me too, turn off illegal login lock

**Comment by toxicantidote** [comment]
Same here with a Tp-Link 'Vigi' series camera, which strangely also gives a 404 when navigating to it via HTTP. Specific model is the C240I.

Fixed by:
1. Installing TP-Link's "VIGI Security Manager' (Windows) application.
2. Adding my camera to the application.
3. Navigate to Settings and then click the gear icon next to the relevant camera.
4. Navigate to Event -> Exception Event.
5. Disable 'Login Error Detection' option.

Leaving this here for anyone who finds this issue via Google. I was going insane copy-pasting the RTSP URL to and from VLC but only having it work in VLC.

**Comment by toxicantidote** [comment]
Same here with a Tp-Link 'Vigi' series camera, which strangely also gives a 404 when navigating to it via HTTPS (no HTTP available). Specific model is the C240I.

Fixed by:
1. Installing TP-Link's "VIGI Security Manager' (Windows) application.
2. Adding my camera to the application.
3. Navigate to Settings and then click the gear icon next to the relevant camera.
4. Navigate to Event -> Exception Event.
5. Disable 'Login Error Detection' option.

Leaving this here for anyone who finds this issue via Google. I was going insane copy-pasting the RTSP URL to and from VLC but only having it work in VLC.

**Comment by saschabrockel** [comment]
@lxtzfr did you ever fix it? Same issue here. With VLC Media Player it works fine.

**Comment by Salvatore76** [comment]
Restart my camera works for me too :)

**Comment by haldi4803** [comment]
Omfg
Yeah... Vlc worked. It should not have any issues... No connection.


Just because I used upercase as username which did not work via URL...  So I had too many tries with wrong username...
