### ISSUE TITLE
Motion Event (without Object detection)

### ISSUE THREAD

**Issue by MrSpoocy** [blakeblackshear/frigate#9041]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to react to a simple motion detection (e.g. via MQTT). Even if no object has been detected.

**Describe the solution you'd like**
Trigger an "Motion" event and save it too record as well.

**Describe alternatives you've considered**
- 
**Additional context**
I am currently using Frigate with CoralAI, but unfortunately it is not yet able to recognize a mouse (animal). That's why I use normal motion detection. Unfortunately I can't react when it is recognized because there is no event for it (at least what I could find out from the documentation).

In general, I find that having an event for motion opens up many new possibilities.

**Comment by NickM-27** [comment]
This is already possible via mqtt https://docs.frigate.video/integrations/mqtt#frigatecamera_namemotion

and motion based recording is already supported as well https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

**Comment by MrSpoocy** [comment]
Sorry, my misstake, have only see that "set" commands.

Regarding recording, yes it records, but it is not saved as a single event. It would be nice to have one event per motion which you can then click on if necessary.

<img width="458" alt="image" src="https://github.com/blakeblackshear/frigate/assets/3809439/82b137e2-edfe-4882-a14e-fb00a5301689">

**Comment by NickM-27** [comment]
motion activity will be shown on recordings in a future frigate version

**Comment by MrSpoocy** [comment]
Will a "box" also be visible around the motion? Sometimes I can't see on the recording why it was triggered. So that I can refine the settings a little.

**Comment by GeoHickle** [comment]
To see why it is triggered, I use ffmpeg and mediamtx to generate a stream from recorded video, and configure it as a camera at frigate. Then you can use debug view in the webpage to see the box.

**Comment by Kirkland-Pickles** [comment]
the lack of standard motion as an event, becomes a real issue. i have certain cameras that are positioned in a way that only standard motion detection would even matter for them, and frigates ai would never detect it as an event because nothing happening in it is classifiable enough. i have other cameras where, its 50/50, and a frigate "event" arrives too late. because it only comes after a determined event (person detected) happened, and not at the start of the movement.


i understand that frigate is not really designed as this, and these motion events from pixel changing is more in line with stock standard camera apps/systems. but please understand, that the ai detection is not the only thing about frigate that is unique. frigates ui and timeline scrubber are unmatched anywhere. i would like to be able to use frigate, as a "normal" camera system, where there is an option to have standard pixel change motion register as an event, on the same level/channel that the current person detected events happen on.   

(i use the android app [Phylax](https://github.com/sfortis/phylax), which is the primary place that i would like to receive these notifications. this app, and other 3rd party viewers, subscribe to the reviews channel, and can only show proper recognized events)

the mqtt/ha thing, where you can get standard motion notifications, is subpar. one of the reasons i love frigate is because of its amazing ui, and you lose that in home assistant. even the hacs frigate integration doesnt compare to the frigate ui itself. and with the mqtt sensor, the "motion detected" notification doesnt link to a part of the timeline, or have a snapshot/thumbnail or anything, its just a hacky sensor that you need to assign..


thanks, please consider.
