### ISSUE TITLE
Only record clip if movement is detected

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#935]
**Describe the bug**
I have cars in my driveway and frigate keeps recording clips of them - i only want to record clips when movement is detected. how do i do that?

https://i.imgur.com/3TcR09I.jpg

**Comment by HITChris** [comment]
Movement is being detected, hence the object detection kicking in, and an event being created. Configure a 'test' camera that loops through the clip, and observe that 'motion' via the test camera's debug stream. Adjust the motion-related sensitivity settings to counteract the shadows or whatever else is being interpreted as motion, or else add motion filters to the area so that said 'motion' is ignored. See https://github.com/blakeblackshear/frigate/issues/822#issuecomment-785474576

**Comment by Sloth-on-meth** [comment]
how do i add motion filters or change the sensitivity settings? docs arnt very clear

**Comment by it-is-just-me** [comment]
You can either try adjusting thresholds like https://blakeblackshear.github.io/frigate/configuration/false_positives , use masks to black out areas you don’t want Motion to be detected  https://blakeblackshear.github.io/frigate/configuration/false_positives or also try setting min and max sizes of objects for the detection https://blakeblackshear.github.io/frigate/configuration/false_positives
