### ISSUE TITLE
Feature suggestion for h265->h264 conversion on clips afterwards to enable viewing clips in browser

### ISSUE THREAD

**Issue by erikarenhill** [blakeblackshear/frigate#957]
Some cameras only support h265 codec on their main-stream, which makes the video clips not playable in web browsers. Doing a h264 conversion in real time requires lots of CPU and are problematic with some cheaper cameras with unstable video streams.

To try to solve this I created a simple script that monitors the clips-directory and then performs a conversion afterwards instead on the saved h265 -clip

It basically renames the original clip to FILE_h265.mp4 then launches a ffmpeg h264 conversion to the original filename so it will get picked up by the web interface on the event. I also reduce some quality and resolution on the h264 version (fullhd, crf 20, preset superfast). Right now it's a really naive (but working) nodejs script that uses chokidar for watching the directory and runs with pm2 outside of frigate, using ffmpeg on the host machine.

This way we can keep the original h265 files in full resolution/quality for certain security events if needed at the same time we get playable video-clips without continously performing a real time conversion on the CPU.

What do you think of this idea? Would it be considered if I'd help out making a PR for a built in and configurable feature like this?

**Comment by blakeblackshear** [comment]
It will need to be done in a way that supports additional types of post processing since there are other similar requests.

**Comment by no2chem** [comment]
Hi, haven't been around in a while since life got extremely busy. Sorry for any PRs that fell while I was away.

It looks like frigate has gotten quite extensible while I was away. If you have hardware/gpu acceleration encoding, it seems that you can hardware the recordings into h264 using output_args. I'm using a nvidia gpu.

For example my global output_args looks like this:
`  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_nvenc -an
    rtmp: -c copy -f flv
`

I also have hardware decoding:
`
        - path: rtsp://...
          input_args: -c:v hevc_cuvid
          roles:
            - clips
            - record
`

this seems to work pretty well. using very little CPU (but 10W of GPU power on my 1660 super). I could do it on the 24/7 record though, but that seems like it would negate the storage savings.

**Comment by kevin-david** [comment]
Hey @no2chem I realize this is an old issue, but I am looking to do the same thing. With the removal of `clips` did you figure out an alternative to send h264 to clients on-demand while preserving h265 for recordings? Thanks!
